# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -l class -d 'Defines the window class hint on Linux [default: Alacritty,Alacritty]  When o…'
complete -c alacritty -s e -l command -d 'Command and args to execute (must be last argument)'
complete -c alacritty -l config-file -d 'Specify alternative configuration file  Alacritty looks for the configuration…'
complete -c alacritty -l embed -d 'X11 window ID to embed Alacritty within (decimal or hexadecimal with "0x" pre…'
complete -c alacritty -s o -l option -d 'Override configuration file options [example: cursor. style=Beam]'
complete -c alacritty -l socket -d 'Path for IPC socket creation'
complete -c alacritty -s T -l title -d 'Defines the window title [default: Alacritty]'

