# alacritty-msg
# Autogenerated from man page /usr/share/man/man1/alacritty-msg.1.gz
complete -c alacritty-msg -s s -l socket -d 'Path for IPC socket creation MESSAGES'
complete -c alacritty-msg -l hold -d 'Remain open after child process exits'
complete -c alacritty-msg -l working-directory -d 'Start the shell in the specified working directory'
complete -c alacritty-msg -s e -l command -d 'Command and args to execute (must be last argument) config Update the Alacrit…'
complete -c alacritty-msg -s w -l window-id -d 'Window ID for the new config'

