# arping
# Autogenerated from man page /usr/share/man/man8/arping.8.gz
complete -c arping -s A -d 'The same as -U, but ARP REPLY packets used instead of ARP REQUEST'
complete -c arping -s b -d 'Send only MAC level broadcasts'
complete -c arping -s c -d 'Stop after sending count ARP REQUEST packets'
complete -c arping -s D -d 'Duplicate address detection mode (DAD).  See RFC2131, 4. 4. 1'
complete -c arping -s f -d 'Finish after the first reply confirming that target is alive'
complete -c arping -s I -d 'Name of network device where to send ARP REQUEST packets'
complete -c arping -s h -d 'Print help page and exit'
complete -c arping -s q -d 'Quiet output.  Nothing is displayed'
complete -c arping -s U -d 'Unsolicited ARP mode to update neighbours\\*(Aq ARP caches'
complete -c arping -s V -d 'Print version of the program and exit'
complete -c arping -s w -d 'Specify a timeout, in seconds, before arping exits regardless of how many pac…'
complete -c arping -s i -d 'Specify an interval, in seconds, between packets'
complete -c arping -s s

