# asn1Coding
# Autogenerated from man page /usr/share/man/man1/asn1Coding.1.gz
complete -c asn1Coding -s c -l check -d 'checks the syntax only'
complete -c asn1Coding -s o -l output -d 'output file'
complete -c asn1Coding -s h -l help -d 'display this help and exit'
complete -c asn1Coding -s v -l version -d 'output version information and exit AUTHOR Written by Fabio Fiorina'

