# asn1Parser
# Autogenerated from man page /usr/share/man/man1/asn1Parser.1.gz
complete -c asn1Parser -s c -l check -d 'checks the syntax only'
complete -c asn1Parser -s o -l output -d 'output file'
complete -c asn1Parser -s n -l name -d 'array name'
complete -c asn1Parser -s h -l help -d 'display this help and exit'
complete -c asn1Parser -s v -l version -d 'output version information and exit AUTHOR Written by Fabio Fiorina'

