# asn1Decoding
# Autogenerated from man page /usr/share/man/man1/asn1Decoding.1.gz
complete -c asn1Decoding -s b -l benchmark -d 'perform a benchmark on decoding'
complete -c asn1Decoding -s s -l strict -d 'use strict DER decoding'
complete -c asn1Decoding -s t -l no-time-strict -d 'use strict DER decoding but not in time fields'
complete -c asn1Decoding -s h -l help -d 'display this help and exit'
complete -c asn1Decoding -s v -l version -d 'output version information and exit AUTHOR Written by Fabio Fiorina'

