# attr
# Autogenerated from man page /usr/share/man/man1/attr.1.gz
complete -c attr -s g -d 'option tells attr to search the named object and print (to stdout) the value …'
complete -c attr -s q -d 'flag, stdout will be exactly and only the value of the attribute, suitable fo…'
complete -c attr -s l -d 'option tells attr to list the names of all the attributes that are associated…'
complete -c attr -s r -d 'option tells attr to remove an attribute with the given name from the object …'
complete -c attr -s s -d 'option tells attr to set the named attribute of the object to the value read …'
complete -c attr -s V -d 'flag, the attribute will be set to have a value of attrvalue and stdin will n…'
complete -c attr -s L -d 'option is given and the named object is a symbolic link, operate on the attri…'
complete -c attr -s R -d 'option is given and the process has appropriate privileges, operate in the ro…'
complete -c attr -s S -d 'option is similar, except it specifies use of the security attribute namespace'

