# auditd
# Autogenerated from man page /usr/share/man/man8/auditd.8.gz
complete -c auditd -s f -d 'leave the audit daemon in the foreground for debugging'
complete -c auditd -s l -d 'allow the audit daemon to follow symlinks for config files'
complete -c auditd -s n -d 'no fork.  This is useful for running off of inittab or systemd'
complete -c auditd -s s -d 'specify when starting if auditd should change the current value for the kerne…'
complete -c auditd -s c -d 'Specify alternate config file directory'

