# augenrules
# Autogenerated from man page /usr/share/man/man8/augenrules.8.gz
complete -c augenrules -l check -d 'test if rules have changed and need updating without overwriting audit. rules'
complete -c augenrules -l load -d 'load old or newly built rules into the kernel'

