# aulast
# Autogenerated from man page /usr/share/man/man8/aulast.8.gz
complete -c aulast -l bad -d 'Report on the bad logins'
complete -c aulast -l debug -d 'Print debug messages to stderr'
complete -c aulast -l extract -d 'Write raw audit records used to create the displayed report into a file aulast'
complete -c aulast -s f -d 'Use the file instead of the audit logs for input'
complete -c aulast -l proof -d 'Print out the audit event serial numbers used to determine the preceding line…'
complete -c aulast -l stdin -d 'Take audit records from stdin.  The audit events must be in the raw format'
complete -c aulast -l tty -d 'Limit the report to a specific tty\'s activity'
complete -c aulast -l user -d 'Limit the report to a specific user'

