# aulastlog
# Autogenerated from man page /usr/share/man/man8/aulastlog.8.gz
complete -c aulastlog -s u -l user -d 'Print the lastlog record for user with specified LOGIN only'
complete -c aulastlog -l stdin -d 'Use stdin as the source of audit records'

