# ausyscall
# Autogenerated from man page /usr/share/man/man8/ausyscall.8.gz
complete -c ausyscall -l dump -d 'Print all syscalls for the given arch'
complete -c ausyscall -s a -s S -s F -o EPERM -s k
complete -c ausyscall -l exact -d 'Instead of doing a partial word match, match the given syscall name exactly'

