# autoscan
# Autogenerated from man page /usr/share/man/man1/autoscan.1.gz
complete -c autoscan -s h -l help -d 'print this help, then exit'
complete -c autoscan -s V -l version -d 'print version number, then exit'
complete -c autoscan -s v -l verbose -d 'verbosely report processing'
complete -c autoscan -s d -l debug -d 'don\'t remove temporary files . SS "Library directories:"'
complete -c autoscan -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c autoscan -s I -l include -d 'append directory DIR to search path AUTHOR Written by David J'

