# autoheader
# Autogenerated from man page /usr/share/man/man1/autoheader.1.gz
complete -c autoheader -s h -l help -d 'print this help, then exit'
complete -c autoheader -s V -l version -d 'print version number, then exit'
complete -c autoheader -s v -l verbose -d 'verbosely report processing'
complete -c autoheader -s d -l debug -d 'don\'t remove temporary files'
complete -c autoheader -s f -l force -d 'consider all files obsolete'
complete -c autoheader -s W -l warnings -d 'report the warnings falling in CATEGORY . SS "Warning categories include:"'
complete -c autoheader -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c autoheader -s I -l include -d 'append directory DIR to search path AUTHOR Written by Roland McGrath and Akim…'

