# autoupdate
# Autogenerated from man page /usr/share/man/man1/autoupdate.1.gz
complete -c autoupdate -s h -l help -d 'print this help, then exit'
complete -c autoupdate -s V -l version -d 'print version number, then exit'
complete -c autoupdate -s v -l verbose -d 'verbosely report processing'
complete -c autoupdate -s d -l debug -d 'don\'t remove temporary files'
complete -c autoupdate -s f -l force -d 'consider all files obsolete . SS "Library directories:"'
complete -c autoupdate -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c autoupdate -s I -l include -d 'append directory DIR to search path AUTHOR Written by David J'

