# avahi-bookmarks
# Autogenerated from man page /usr/share/man/man1/avahi-bookmarks.1.gz
complete -c avahi-bookmarks -s p -l port -d 'Specify a TCP port number to listen on.  If omitted defaults to 8080'
complete -c avahi-bookmarks -s a -l address -d 'Specify an IP address to listen on.  If omitted defaults to 127. 0. 0. 1'
complete -c avahi-bookmarks -s H -l host-names -d 'Create links pointing to mDNS host names instead of resolved IP addreses'
complete -c avahi-bookmarks -s A -l addresses -d 'Create links pointing to numeric IP addresses instead of mDNS host names'
complete -c avahi-bookmarks -s d -l domain -d 'The domain to browse for services in'
complete -c avahi-bookmarks -s h -l help -d 'Show help AUTHORS The Avahi Developers <avahi (at) lists (dot) freedesktop (d…'

