# avahi-dnsconfd
# Autogenerated from man page /usr/share/man/man8/avahi-dnsconfd.8.gz
complete -c avahi-dnsconfd -s D -l daemonize -d 'Daemonize after startup and redirect log messages to syslog'
complete -c avahi-dnsconfd -s s -l syslog -d 'Log to syslog instead of STDERR.  Implied by --daemonize'
complete -c avahi-dnsconfd -s k -l kill -d 'Kill an already running avahi-dnsconfd.  (equivalent to sending a SIGTERM)'
complete -c avahi-dnsconfd -s r -l refresh -d 'Tell an already running avahi-dnsconfd to refresh the DNS server data'
complete -c avahi-dnsconfd -s c -l check -d 'Return 0 as return code when avahi-dnsconfd is already running'
complete -c avahi-dnsconfd -s h -l help -d 'Show help'
complete -c avahi-dnsconfd -s v -l version -d 'Show version information  FILES /etc/avahi/avahi-dnsconfd'

