# bond2team
# Autogenerated from man page /usr/share/man/man1/bond2team.1.gz
complete -c bond2team -l master -d 'Specify the interface name or ifcfg file to convert'
complete -c bond2team -l rename -d 'This is a convenient option to replace the original interface name by the spe…'
complete -c bond2team -l ifcfg -d 'Set the output format to ifcfg config style.  [default]'
complete -c bond2team -l json -d 'Set the output format to JSON style.  See  teamd'
complete -c bond2team -l bonding_opts -d 'Specify the bonding options to be converted instead of reading them from the …'
complete -c bond2team -l port -d 'Set the specified interface as a team port'
complete -c bond2team -l configdir -d 'Change the ifcfg configuration path from \\%/etc/sysconfig/network-scripts to …'
complete -c bond2team -l outputdir -d 'Set the output directory to <directory>'
complete -c bond2team -l stdout -d 'Print the result to the screen instead of writing to files'
complete -c bond2team -l debug -d 'Increase the debugging level'
complete -c bond2team -l quiet -d 'Disallow any messages to be printed to console'
complete -c bond2team -l version -d 'Print tool version to console and exit'
complete -c bond2team -l help -d 'Print help text to console and exit'
complete -c bond2team -l examples -d 'Print common usage examples to console and exit.  EXAMPLES'

