# bsdunzip
# Autogenerated from man page /usr/share/man/man1/bsdunzip.1.gz
complete -c bsdunzip -s a -d 'When extracting a text file, convert DOS-style line endings to Unix-style lin…'
complete -c bsdunzip -s C -d 'Match file names case-insensitively'
complete -c bsdunzip -s c -d 'Extract to stdout/screen'
complete -c bsdunzip -s d -d 'Extract files into the specified directory rather than the current directory'
complete -c bsdunzip -s f -d 'Update existing'
complete -c bsdunzip -s I
complete -c bsdunzip -s O -d 'Convert filenames from the specified encoding'
complete -c bsdunzip -s j -d 'Ignore directories stored in the zipfile; instead, extract all files directly…'
complete -c bsdunzip -s L -d 'Convert the names of the extracted files and directories to lowercase'
complete -c bsdunzip -s l -d 'List, rather than extract, the contents of the zipfile'
complete -c bsdunzip -s n -d 'No overwrite'
complete -c bsdunzip -s o -d Overwrite
complete -c bsdunzip -s p -d 'Extract to stdout'
complete -c bsdunzip -s P -d 'Extract encrypted files using a password'
complete -c bsdunzip -s q -d 'Quiet: print less information while extracting'
complete -c bsdunzip -s t -d 'Test: do not extract anything, but verify the checksum of every file in the a…'
complete -c bsdunzip -s u -d Update
complete -c bsdunzip -s v -d 'List verbosely, rather than extract, the contents of the zipfile'
complete -c bsdunzip -s x -d 'Exclude files matching the pattern pattern'
complete -c bsdunzip -s y -d 'Print four digit years in listings instead of two'
complete -c bsdunzip -s Z -d 'Emulate zipinfo 1L mode'

