# bshell
# Autogenerated from man page /usr/share/man/man1/bshell.1.gz
complete -c bshell -s s -l ssh -d 'Browse for SSH servers (and only SSH servers) regardless under which name the…'
complete -c bshell -s v -l vnc -d 'Browse for VNC servers (and only VNC servers) regardless under which name the…'
complete -c bshell -s S -l shell -d 'Browse for both VNC and SSH servers regardless under which name the binary is…'
complete -c bshell -s d -l domain -d 'Browse in the specified domain'
complete -c bshell -s h -l help -d 'Show help'

