# bssh
# Autogenerated from man page /usr/share/man/man1/bssh.1.gz
complete -c bssh -s s -l ssh -d 'Browse for SSH servers (and only SSH servers) regardless under which name the…'
complete -c bssh -s v -l vnc -d 'Browse for VNC servers (and only VNC servers) regardless under which name the…'
complete -c bssh -s S -l shell -d 'Browse for both VNC and SSH servers regardless under which name the binary is…'
complete -c bssh -s d -l domain -d 'Browse in the specified domain'
complete -c bssh -s h -l help -d 'Show help'

