# c_rehash.1ssl
# Autogenerated from man page /usr/share/man/man1/c_rehash.1ssl.gz
complete -c 'c_rehash.1ssl' -o help -s h -d 'X Item "-help -h" Display a brief usage message'
complete -c 'c_rehash.1ssl' -o old -d 'X Item "-old" Use old-style hashing (MD5, as opposed to SHA-1) for generating…'
complete -c 'c_rehash.1ssl' -s n -d 'X Item "-n" Do not remove existing links'
complete -c 'c_rehash.1ssl' -o compat -d 'X Item "-compat" Generate links for both old-style (MD5) and new-style (SHA1)…'
complete -c 'c_rehash.1ssl' -s v -d 'X Item "-v" Print messages about old links removed and new links created'
complete -c 'c_rehash.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'c_rehash.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'c_rehash.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7)'

