# cal
# Autogenerated from man page /usr/share/man/man1/cal.1.gz
complete -c cal -s 1 -l one
complete -c cal -s 3 -l three
complete -c cal -s n -l months
complete -c cal -s S -l span
complete -c cal -s s -l sunday
complete -c cal -s m -l monday
complete -c cal -s v -l vertical
complete -c cal -l iso
complete -c cal -s j -l julian
complete -c cal -l reform
complete -c cal -s y -l year
complete -c cal -s Y -l twelve
complete -c cal -s w -l week
complete -c cal -l color
complete -c cal -s c -l columns
complete -c cal -s h -l help
complete -c cal -s V -l version

