# captoinfo.1m
# Autogenerated from man page /usr/share/man/man1/captoinfo.1m.gz
complete -c 'captoinfo.1m' -s v -d 'print out tracing information on standard error as the program runs'
complete -c 'captoinfo.1m' -s V -d 'print out the version of the program in use on standard error and exit'
complete -c 'captoinfo.1m' -s 1 -d 'cause the fields to print out one to a line'
complete -c 'captoinfo.1m' -s w -d 'change the output to width characters.  FILES'

