# captree
# Autogenerated from man page /usr/share/man/man8/captree.8.gz
complete -c captree -l help -d 'Displays usage information and exits'
complete -c captree -l verbose -d 'Displays capability sets and IAB tuples even when they are empty, or redundant'
complete -c captree -l depth -d 'Displays the process tree to a depth of R n '
complete -c captree -l color -d 'Colo[u]rs the targeted PIDs, if stdout is a TTY, in red'

