# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
complete -c chfn -s f -l full-name
complete -c chfn -s o -l office
complete -c chfn -s p -l office-phone
complete -c chfn -s h -l home-phone
complete -c chfn -s u -l help
complete -c chfn -s V -l version

