# chroot
# Autogenerated from man page /usr/share/man/man1/chroot.1.gz
complete -c chroot -l groups -d 'specify supplementary groups as g1,g2,. ,gN'
complete -c chroot -l userspec -d 'specify user and group (ID or name) to use'
complete -c chroot -l skip-chdir -d 'do not change working directory to \'/\''
complete -c chroot -l help -d 'display this help and exit'
complete -c chroot -l version -d 'output version information and exit '

