# cjxl
# Autogenerated from man page /usr/share/man/man1/cjxl.1.gz
complete -c cjxl -s h -l help -d 'Displays the options that cjxl supports'
complete -c cjxl -s v -l verbose -d 'Increases verbosity'
complete -c cjxl -s d -l distance -d 'The preferred way to specify quality'
complete -c cjxl -s q -l quality -d 'Alternative way to indicate the desired quality'
complete -c cjxl -s e -l effort -d 'Controls the amount of effort that goes into producing an \\(lqoptimal\\(rq fil…'

