# clockdiff
# Autogenerated from man page /usr/share/man/man8/clockdiff.8.gz
complete -c clockdiff -s o -d 'Use IP TIMESTAMP with ICMP ECHO instead of ICMP TIMESTAMP messages'
complete -c clockdiff -o o1 -d 'Slightly different form of -o, namely it uses three-term IP TIMESTAMP with pr…'
complete -c clockdiff -s T -l time-format -d 'Print time stamp in output either ISO-8601 format or classical ctime format'
complete -c clockdiff -s I -d 'Alias of --time-format iso  option and argument'
complete -c clockdiff -s h -l help -d 'Print help and exit'
complete -c clockdiff -s V -l version -d 'Print version and exit'

