# cmsutil
# Autogenerated from man page /usr/share/man/man1/cmsutil.1.gz
complete -c cmsutil -s C
complete -c cmsutil -s D
complete -c cmsutil -s E
complete -c cmsutil -s O
complete -c cmsutil -s S
complete -c cmsutil -s b
complete -c cmsutil -s c
complete -c cmsutil -s d
complete -c cmsutil -s e
complete -c cmsutil -s f
complete -c cmsutil -s G
complete -c cmsutil -s H
complete -c cmsutil -s h
complete -c cmsutil -s i
complete -c cmsutil -s k
complete -c cmsutil -s N
complete -c cmsutil -s n
complete -c cmsutil -s o
complete -c cmsutil -s P
complete -c cmsutil -s p
complete -c cmsutil -s r
complete -c cmsutil -s T
complete -c cmsutil -s u
complete -c cmsutil -s v
complete -c cmsutil -s Y

