# col
# Autogenerated from man page /usr/share/man/man1/col.1.gz
complete -c col -s b -l no-backspaces
complete -c col -s f -l fine
complete -c col -s h -l tabs
complete -c col -s l -l lines
complete -c col -s p -l pass
complete -c col -s x -l spaces
complete -c col -l help
complete -c col -s V -l version

