# corelist.1perl
# Autogenerated from man page /usr/share/man/man1/corelist.1perl.gz
complete -c 'corelist.1perl' -s a -d 'X Item "-a" lists all versions of the given module (or the matching modules, …'
complete -c 'corelist.1perl' -s d -d 'X Item "-d" finds the first perl version where a module has been released by …'
complete -c 'corelist.1perl' -l diff -d 'X Item "--diff" Given two versions of perl, this prints a human-readable tabl…'
complete -c 'corelist.1perl' -s '?' -o help -d 'X Item "-? or -help" help! help! help! to see more help, try --man'
complete -c 'corelist.1perl' -o man -d 'X Item "-man" all of the help'
complete -c 'corelist.1perl' -s v -d 'X Item "-v" lists all of the perl release versions we got the CoreList for'
complete -c 'corelist.1perl' -s r -d 'X Item "-r" lists all of the perl releases and when they were released '
complete -c 'corelist.1perl' -l utils -d 'X Item "--utils" lists the first version of perl each named utility program w…'
complete -c 'corelist.1perl' -l feature -s f -d 'X Item "--feature, -f" lists the first version bundle of each named feature g…'
complete -c 'corelist.1perl' -l upstream -s u

