# cpan.1perl
# Autogenerated from man page /usr/share/man/man1/cpan.1perl.gz
complete -c 'cpan.1perl' -s a
complete -c 'cpan.1perl' -s A
complete -c 'cpan.1perl' -s c
complete -c 'cpan.1perl' -s C
complete -c 'cpan.1perl' -s D
complete -c 'cpan.1perl' -s f
complete -c 'cpan.1perl' -s i -d '        % cpan -f -i Module::Foo'
complete -c 'cpan.1perl' -s F
complete -c 'cpan.1perl' -s g
complete -c 'cpan.1perl' -s G
complete -c 'cpan.1perl' -s h
complete -c 'cpan.1perl' -s I
complete -c 'cpan.1perl' -s j
complete -c 'cpan.1perl' -s J
complete -c 'cpan.1perl' -s l
complete -c 'cpan.1perl' -s L
complete -c 'cpan.1perl' -s m
complete -c 'cpan.1perl' -s M
complete -c 'cpan.1perl' -s n
complete -c 'cpan.1perl' -s O
complete -c 'cpan.1perl' -s p
complete -c 'cpan.1perl' -s P
complete -c 'cpan.1perl' -s r
complete -c 'cpan.1perl' -s s
complete -c 'cpan.1perl' -s t
complete -c 'cpan.1perl' -s T
complete -c 'cpan.1perl' -s u
complete -c 'cpan.1perl' -s v
complete -c 'cpan.1perl' -s V
complete -c 'cpan.1perl' -s w
complete -c 'cpan.1perl' -s x
complete -c 'cpan.1perl' -s X

