# crlutil
# Autogenerated from man page /usr/share/man/man1/crlutil.1.gz
complete -c crlutil -s D
complete -c crlutil -s E
complete -c crlutil -s G
complete -c crlutil -s I
complete -c crlutil -s L
complete -c crlutil -s M
complete -c crlutil -s S
complete -c crlutil -s a
complete -c crlutil -s B
complete -c crlutil -s c
complete -c crlutil -s d
complete -c crlutil -s f
complete -c crlutil -s i
complete -c crlutil -s l
complete -c crlutil -s n
complete -c crlutil -s o
complete -c crlutil -s P
complete -c crlutil -s t
complete -c crlutil -s u
complete -c crlutil -s w
complete -c crlutil -s Z

