# cryptsetup-reencrypt
# Autogenerated from man page /usr/share/man/man8/cryptsetup-reencrypt.8.gz
complete -c cryptsetup-reencrypt -l block-size
complete -c cryptsetup-reencrypt -l cipher
complete -c cryptsetup-reencrypt -l debug
complete -c cryptsetup-reencrypt -l debug-json
complete -c cryptsetup-reencrypt -l decrypt
complete -c cryptsetup-reencrypt -l device-size
complete -c cryptsetup-reencrypt -l disable-locks
complete -c cryptsetup-reencrypt -l encrypt
complete -c cryptsetup-reencrypt -l force-offline-reencrypt
complete -c cryptsetup-reencrypt -l hash
complete -c cryptsetup-reencrypt -l header
complete -c cryptsetup-reencrypt -l hotzone-size
complete -c cryptsetup-reencrypt -l iter-time
complete -c cryptsetup-reencrypt -l init-only
complete -c cryptsetup-reencrypt -l keep-key
complete -c cryptsetup-reencrypt -l key-file
complete -c cryptsetup-reencrypt -l key-size
complete -c cryptsetup-reencrypt -l key-slot
complete -c cryptsetup-reencrypt -l keyfile-offset
complete -c cryptsetup-reencrypt -l keyfile-size
complete -c cryptsetup-reencrypt -l tries
complete -c cryptsetup-reencrypt -l timeout
complete -c cryptsetup-reencrypt -l pbkdf
complete -c cryptsetup-reencrypt -l pbkdf-force-iterations
complete -c cryptsetup-reencrypt -l pbkdf-memory
complete -c cryptsetup-reencrypt -l pbkdf-parallel
complete -c cryptsetup-reencrypt -l progress-frequency
complete -c cryptsetup-reencrypt -l progress-json
complete -c cryptsetup-reencrypt -l reduce-device-size
complete -c cryptsetup-reencrypt -l resilience
complete -c cryptsetup-reencrypt -l resilience-hash
complete -c cryptsetup-reencrypt -l resume-only
complete -c cryptsetup-reencrypt -l sector-size
complete -c cryptsetup-reencrypt -l use-directio
complete -c cryptsetup-reencrypt -l use-random
complete -c cryptsetup-reencrypt -l use-urandom
complete -c cryptsetup-reencrypt -l use-fsync
complete -c cryptsetup-reencrypt -l uuid
complete -c cryptsetup-reencrypt -l verbose
complete -c cryptsetup-reencrypt -l volume-key-file
complete -c cryptsetup-reencrypt -l write-log -d 'LUKS2 REENCRYPTION'
complete -c cryptsetup-reencrypt -l type
complete -c cryptsetup-reencrypt -s h
complete -c cryptsetup-reencrypt -s c
complete -c cryptsetup-reencrypt -l verify-passphrase -s y
complete -c cryptsetup-reencrypt -s d
complete -c cryptsetup-reencrypt -s l
complete -c cryptsetup-reencrypt -l master-key-file
complete -c cryptsetup-reencrypt -s S
complete -c cryptsetup-reencrypt -s s
complete -c cryptsetup-reencrypt -l offset -s o
complete -c cryptsetup-reencrypt -s i
complete -c cryptsetup-reencrypt -s t
complete -c cryptsetup-reencrypt -s T
complete -c cryptsetup-reencrypt -l align-payload
complete -c cryptsetup-reencrypt -l force-password
complete -c cryptsetup-reencrypt -l disable-keyring
complete -c cryptsetup-reencrypt -l label -l subsystem
complete -c cryptsetup-reencrypt -l luks2-metadata-size
complete -c cryptsetup-reencrypt -l luks2-keyslots-size
complete -c cryptsetup-reencrypt -l keyslot-cipher
complete -c cryptsetup-reencrypt -l keyslot-key-size
complete -c cryptsetup-reencrypt -l new -s N
complete -c cryptsetup-reencrypt -l batch-mode -s q
complete -c cryptsetup-reencrypt -l version -s V
complete -c cryptsetup-reencrypt -l usage
complete -c cryptsetup-reencrypt -l help -s '?'

