# cryptsetup-bitlkDump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-bitlkDump.8.gz
complete -c cryptsetup-bitlkDump -l keyfile-offset -l keyfile-size -l timeout -d OPTIONS
complete -c cryptsetup-bitlkDump -l key-file -s d
complete -c cryptsetup-bitlkDump -s l
complete -c cryptsetup-bitlkDump -l volume-key-file -l master-key-file
complete -c cryptsetup-bitlkDump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-bitlkDump -s t
complete -c cryptsetup-bitlkDump -l batch-mode -s q
complete -c cryptsetup-bitlkDump -l debug -l debug-json
complete -c cryptsetup-bitlkDump -l version -s V
complete -c cryptsetup-bitlkDump -l usage
complete -c cryptsetup-bitlkDump -l help -s '?'

