# cryptsetup-luksChangeKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksChangeKey.8.gz
complete -c cryptsetup-luksChangeKey -l new-keyfile-offset -l iter-time -l pbkdf -l pbkdf-force-iterations
complete -c cryptsetup-luksChangeKey -l pbkdf-memory -l pbkdf-parallel -l new-keyfile-size -l key-slot
complete -c cryptsetup-luksChangeKey -l force-password -l hash -l header -l disable-locks -l type
complete -c cryptsetup-luksChangeKey -l keyslot-cipher -l keyslot-key-size -l timeout -l verify-passphrase -d OPTIONS
complete -c cryptsetup-luksChangeKey -s h
complete -c cryptsetup-luksChangeKey -s y
complete -c cryptsetup-luksChangeKey -l key-file -s d
complete -c cryptsetup-luksChangeKey -l keyfile-offset
complete -c cryptsetup-luksChangeKey -l keyfile-size -s l
complete -c cryptsetup-luksChangeKey -s S
complete -c cryptsetup-luksChangeKey -s i
complete -c cryptsetup-luksChangeKey -s t
complete -c cryptsetup-luksChangeKey -l batch-mode -s q
complete -c cryptsetup-luksChangeKey -l debug -l debug-json
complete -c cryptsetup-luksChangeKey -l version -s V
complete -c cryptsetup-luksChangeKey -l usage
complete -c cryptsetup-luksChangeKey -l help -s '?'

