# cryptsetup-convert
# Autogenerated from man page /usr/share/man/man8/cryptsetup-convert.8.gz
complete -c cryptsetup-convert -l type
complete -c cryptsetup-convert -l header
complete -c cryptsetup-convert -l disable-locks
complete -c cryptsetup-convert -l batch-mode -s q
complete -c cryptsetup-convert -l debug -l debug-json
complete -c cryptsetup-convert -l version -s V
complete -c cryptsetup-convert -l usage
complete -c cryptsetup-convert -l help -s '?'

