# cryptsetup-luksUUID
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksUUID.8.gz
complete -c cryptsetup-luksUUID -l type
complete -c cryptsetup-luksUUID -l uuid
complete -c cryptsetup-luksUUID -l header
complete -c cryptsetup-luksUUID -l disable-locks
complete -c cryptsetup-luksUUID -l batch-mode -s q
complete -c cryptsetup-luksUUID -l debug -l debug-json
complete -c cryptsetup-luksUUID -l version -s V
complete -c cryptsetup-luksUUID -l usage
complete -c cryptsetup-luksUUID -l help -s '?'

