# cryptsetup-luksHeaderBackup
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksHeaderBackup.8.gz
complete -c cryptsetup-luksHeaderBackup -l header
complete -c cryptsetup-luksHeaderBackup -l header-backup-file
complete -c cryptsetup-luksHeaderBackup -l disable-locks
complete -c cryptsetup-luksHeaderBackup -l batch-mode -s q
complete -c cryptsetup-luksHeaderBackup -l debug -l debug-json
complete -c cryptsetup-luksHeaderBackup -l version -s V
complete -c cryptsetup-luksHeaderBackup -l usage
complete -c cryptsetup-luksHeaderBackup -l help -s '?'

