# cryptsetup-close
# Autogenerated from man page /usr/share/man/man8/cryptsetup-close.8.gz
complete -c cryptsetup-close -l header
complete -c cryptsetup-close -l deferred
complete -c cryptsetup-close -l cancel-deferred
complete -c cryptsetup-close -l disable-locks
complete -c cryptsetup-close -l batch-mode -s q
complete -c cryptsetup-close -l debug -l debug-json
complete -c cryptsetup-close -l version -s V
complete -c cryptsetup-close -l usage
complete -c cryptsetup-close -l help -s '?'

