# cryptsetup-erase
# Autogenerated from man page /usr/share/man/man8/cryptsetup-erase.8.gz
complete -c cryptsetup-erase -l header
complete -c cryptsetup-erase -l disable-locks
complete -c cryptsetup-erase -l batch-mode -s q
complete -c cryptsetup-erase -l debug -l debug-json
complete -c cryptsetup-erase -l version -s V
complete -c cryptsetup-erase -l usage
complete -c cryptsetup-erase -l help -s '?'

