# cryptsetup-luksAddKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksAddKey.8.gz
complete -c cryptsetup-luksAddKey -l new-keyfile -l new-keyfile-offset -l new-keyfile-size -l key-slot
complete -c cryptsetup-luksAddKey -l new-key-slot -l volume-key-file -l force-password -l hash -l header
complete -c cryptsetup-luksAddKey -l disable-locks -l iter-time -l pbkdf -l pbkdf-force-iterations
complete -c cryptsetup-luksAddKey -l pbkdf-memory -l pbkdf-parallel -l unbound -l type -l keyslot-cipher
complete -c cryptsetup-luksAddKey -l keyslot-key-size -l key-size -l timeout -l token-id -l token-type
complete -c cryptsetup-luksAddKey -l token-only -l new-token-id -l verify-passphrase -d OPTIONS
complete -c cryptsetup-luksAddKey -s h
complete -c cryptsetup-luksAddKey -s y
complete -c cryptsetup-luksAddKey -l key-file -s d
complete -c cryptsetup-luksAddKey -l keyfile-offset
complete -c cryptsetup-luksAddKey -l keyfile-size -s l
complete -c cryptsetup-luksAddKey -l master-key-file
complete -c cryptsetup-luksAddKey -s S
complete -c cryptsetup-luksAddKey -s s
complete -c cryptsetup-luksAddKey -s i
complete -c cryptsetup-luksAddKey -s t
complete -c cryptsetup-luksAddKey -l batch-mode -s q
complete -c cryptsetup-luksAddKey -l debug -l debug-json
complete -c cryptsetup-luksAddKey -l version -s V
complete -c cryptsetup-luksAddKey -l usage
complete -c cryptsetup-luksAddKey -l help -s '?'

