# cryptsetup-config
# Autogenerated from man page /usr/share/man/man8/cryptsetup-config.8.gz
complete -c cryptsetup-config -l subsystem
complete -c cryptsetup-config -l header -l disable-locks -d OPTIONS
complete -c cryptsetup-config -l key-slot -s S
complete -c cryptsetup-config -l priority
complete -c cryptsetup-config -l label
complete -c cryptsetup-config -l batch-mode -s q
complete -c cryptsetup-config -l debug -l debug-json
complete -c cryptsetup-config -l version -s V
complete -c cryptsetup-config -l usage
complete -c cryptsetup-config -l help -s '?'

