# cryptsetup-luksFormat
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksFormat.8.gz
complete -c cryptsetup-luksFormat -l key-slot -l key-file
complete -c cryptsetup-luksFormat -l keyfile-offset -l keyfile-size -l use-random -l use-urandom -l uuid
complete -c cryptsetup-luksFormat -l volume-key-file -l iter-time -l header -l pbkdf-force-iterations
complete -c cryptsetup-luksFormat -l force-password -l disable-locks -l timeout -l type -l offset
complete -c cryptsetup-luksFormat -l align-payload
complete -c cryptsetup-luksFormat -l integrity-no-wipe -l sector-size -l label -l subsystem -l pbkdf
complete -c cryptsetup-luksFormat -l pbkdf-memory -l pbkdf-parallel -l disable-keyring
complete -c cryptsetup-luksFormat -l luks2-metadata-size -l luks2-keyslots-size -l keyslot-cipher
complete -c cryptsetup-luksFormat -l keyslot-key-size -l integrity-legacy-padding
complete -c cryptsetup-luksFormat -l hash -s h
complete -c cryptsetup-luksFormat -l cipher -s c
complete -c cryptsetup-luksFormat -l verify-passphrase -s y
complete -c cryptsetup-luksFormat -s d
complete -c cryptsetup-luksFormat -s l
complete -c cryptsetup-luksFormat -l master-key-file
complete -c cryptsetup-luksFormat -s S
complete -c cryptsetup-luksFormat -l key-size -s s
complete -c cryptsetup-luksFormat -s o
complete -c cryptsetup-luksFormat -s i
complete -c cryptsetup-luksFormat -l progress-frequency
complete -c cryptsetup-luksFormat -l progress-json
complete -c cryptsetup-luksFormat -s t
complete -c cryptsetup-luksFormat -l integrity
complete -c cryptsetup-luksFormat -l batch-mode -s q
complete -c cryptsetup-luksFormat -l debug -l debug-json
complete -c cryptsetup-luksFormat -l version -s V
complete -c cryptsetup-luksFormat -l usage
complete -c cryptsetup-luksFormat -l help -s '?'

