# cryptsetup-luksDump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksDump.8.gz
complete -c cryptsetup-luksDump -l key-slot -d 'interactively or via --key-file'
complete -c cryptsetup-luksDump -l keyfile-offset -l keyfile-size -l header -l disable-locks
complete -c cryptsetup-luksDump -l volume-key-file -l type -l unbound -l timeout
complete -c cryptsetup-luksDump -l key-file -s d
complete -c cryptsetup-luksDump -s l
complete -c cryptsetup-luksDump -l master-key-file
complete -c cryptsetup-luksDump -l dump-json-metadata
complete -c cryptsetup-luksDump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-luksDump -s S
complete -c cryptsetup-luksDump -s t
complete -c cryptsetup-luksDump -l batch-mode -s q
complete -c cryptsetup-luksDump -l debug -l debug-json
complete -c cryptsetup-luksDump -l version -s V
complete -c cryptsetup-luksDump -l usage
complete -c cryptsetup-luksDump -l help -s '?'

