# cryptsetup-luksHeaderRestore
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksHeaderRestore.8.gz
complete -c cryptsetup-luksHeaderRestore -l header
complete -c cryptsetup-luksHeaderRestore -l header-backup-file
complete -c cryptsetup-luksHeaderRestore -l disable-locks
complete -c cryptsetup-luksHeaderRestore -l batch-mode -s q
complete -c cryptsetup-luksHeaderRestore -l debug -l debug-json
complete -c cryptsetup-luksHeaderRestore -l version -s V
complete -c cryptsetup-luksHeaderRestore -l usage
complete -c cryptsetup-luksHeaderRestore -l help -s '?'

