# cryptsetup-luksKillSlot
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksKillSlot.8.gz
complete -c cryptsetup-luksKillSlot -l header -l disable-locks -l type -l verify-passphrase -l timeout
complete -c cryptsetup-luksKillSlot -l key-file -s q -d 'removed without any other warning.  OPTIONS'
complete -c cryptsetup-luksKillSlot -s y
complete -c cryptsetup-luksKillSlot -s d
complete -c cryptsetup-luksKillSlot -l keyfile-offset
complete -c cryptsetup-luksKillSlot -l keyfile-size -s l
complete -c cryptsetup-luksKillSlot -s t
complete -c cryptsetup-luksKillSlot -l batch-mode
complete -c cryptsetup-luksKillSlot -l debug -l debug-json
complete -c cryptsetup-luksKillSlot -l version -s V
complete -c cryptsetup-luksKillSlot -l usage
complete -c cryptsetup-luksKillSlot -l help -s '?'

