# cryptsetup
# Autogenerated from man page /usr/share/man/man8/cryptsetup.8.gz
complete -c cryptsetup -l disable-veracrypt
complete -c cryptsetup -l tcrypt-hidden
complete -c cryptsetup -s s
complete -c cryptsetup -l keyfile-size -d 'Passphrase processing for LUKS'
complete -c cryptsetup -l use-urandom -d 'entropy sources can cause luksFormat to block until the requested amount of r…'

