# cryptsetup-token
# Autogenerated from man page /usr/share/man/man8/cryptsetup-token.8.gz
complete -c cryptsetup-token -l json-file
complete -c cryptsetup-token -l disable-external-tokens -l disable-locks -l disable-keyring
complete -c cryptsetup-token -l token-replace -l unbound -d OPTIONS
complete -c cryptsetup-token -l token-id
complete -c cryptsetup-token -l key-slot -s S
complete -c cryptsetup-token -l header
complete -c cryptsetup-token -l key-description
complete -c cryptsetup-token -l batch-mode -s q
complete -c cryptsetup-token -l debug -l debug-json
complete -c cryptsetup-token -l version -s V
complete -c cryptsetup-token -l usage
complete -c cryptsetup-token -l help -s '?'

