# cryptsetup-luksResume
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksResume.8.gz
complete -c cryptsetup-luksResume -l key-file
complete -c cryptsetup-luksResume -l key-slot -l header -l disable-keyring -l disable-locks -l token-id
complete -c cryptsetup-luksResume -l token-only -l token-type -l disable-external-tokens -l type -l tries
complete -c cryptsetup-luksResume -l timeout -l verify-passphrase -d OPTIONS
complete -c cryptsetup-luksResume -s y
complete -c cryptsetup-luksResume -s d
complete -c cryptsetup-luksResume -l keyfile-offset
complete -c cryptsetup-luksResume -l keyfile-size -s l
complete -c cryptsetup-luksResume -s S
complete -c cryptsetup-luksResume -s t
complete -c cryptsetup-luksResume -s T
complete -c cryptsetup-luksResume -l batch-mode -s q
complete -c cryptsetup-luksResume -l debug -l debug-json
complete -c cryptsetup-luksResume -l version -s V
complete -c cryptsetup-luksResume -l usage
complete -c cryptsetup-luksResume -l help -s '?'

