# cryptsetup-resize
# Autogenerated from man page /usr/share/man/man8/cryptsetup-resize.8.gz
complete -c cryptsetup-resize -l token-type -l key-slot -l key-file -l keyfile-size -l keyfile-offset
complete -c cryptsetup-resize -l timeout -l disable-external-tokens -l disable-locks -l disable-keyring
complete -c cryptsetup-resize -l verify-passphrase -d OPTIONS
complete -c cryptsetup-resize -s y
complete -c cryptsetup-resize -s d
complete -c cryptsetup-resize -s l
complete -c cryptsetup-resize -s S
complete -c cryptsetup-resize -l size -s b
complete -c cryptsetup-resize -l device-size
complete -c cryptsetup-resize -s t
complete -c cryptsetup-resize -l header
complete -c cryptsetup-resize -l token-id
complete -c cryptsetup-resize -l token-only
complete -c cryptsetup-resize -l batch-mode -s q
complete -c cryptsetup-resize -l debug -l debug-json
complete -c cryptsetup-resize -l version -s V
complete -c cryptsetup-resize -l usage
complete -c cryptsetup-resize -l help -s '?'

