# cryptsetup-tcryptDump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-tcryptDump.8.gz
complete -c cryptsetup-tcryptDump -l tcrypt-system -l tcrypt-backup -l veracrypt -l disable-veracrypt
complete -c cryptsetup-tcryptDump -l veracrypt-pim -l veracrypt-query-pim -l cipher -l hash -l header
complete -c cryptsetup-tcryptDump -l verify-passphrase -l timeout
complete -c cryptsetup-tcryptDump -s h
complete -c cryptsetup-tcryptDump -s c
complete -c cryptsetup-tcryptDump -s y
complete -c cryptsetup-tcryptDump -l key-file -s d
complete -c cryptsetup-tcryptDump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-tcryptDump -s t
complete -c cryptsetup-tcryptDump -l tcrypt-hidden
complete -c cryptsetup-tcryptDump -l batch-mode -s q
complete -c cryptsetup-tcryptDump -l debug -l debug-json
complete -c cryptsetup-tcryptDump -l version -s V
complete -c cryptsetup-tcryptDump -l usage
complete -c cryptsetup-tcryptDump -l help -s '?'

