# cryptsetup-refresh
# Autogenerated from man page /usr/share/man/man8/cryptsetup-refresh.8.gz
complete -c cryptsetup-refresh -l perf-same_cpu_crypt -l perf-submit_from_crypt_cpus
complete -c cryptsetup-refresh -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-refresh -l allow-discards
complete -c cryptsetup-refresh -l header -l disable-keyring
complete -c cryptsetup-refresh -l disable-locks -l persistent -l integrity-no-journal -d OPTIONS
complete -c cryptsetup-refresh -l batch-mode -s q
complete -c cryptsetup-refresh -l debug -l debug-json
complete -c cryptsetup-refresh -l version -s V
complete -c cryptsetup-refresh -l usage
complete -c cryptsetup-refresh -l help -s '?'

