# cryptsetup-status
# Autogenerated from man page /usr/share/man/man8/cryptsetup-status.8.gz
complete -c cryptsetup-status -l header
complete -c cryptsetup-status -l disable-locks
complete -c cryptsetup-status -l batch-mode -s q
complete -c cryptsetup-status -l debug -l debug-json
complete -c cryptsetup-status -l version -s V
complete -c cryptsetup-status -l usage
complete -c cryptsetup-status -l help -s '?'

