# cryptsetup-luksConvertKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksConvertKey.8.gz
complete -c cryptsetup-luksConvertKey -l key-slot -l hash -l header -l disable-locks -l iter-time -l pbkdf
complete -c cryptsetup-luksConvertKey -l pbkdf-force-iterations -l pbkdf-memory -l pbkdf-parallel
complete -c cryptsetup-luksConvertKey -l keyslot-cipher -l keyslot-key-size -l timeout -l verify-passphrase -d OPTIONS
complete -c cryptsetup-luksConvertKey -s h
complete -c cryptsetup-luksConvertKey -s y
complete -c cryptsetup-luksConvertKey -l key-file -s d
complete -c cryptsetup-luksConvertKey -l keyfile-offset
complete -c cryptsetup-luksConvertKey -l keyfile-size -s l
complete -c cryptsetup-luksConvertKey -l new-keyfile-offset
complete -c cryptsetup-luksConvertKey -l new-keyfile-size
complete -c cryptsetup-luksConvertKey -s S
complete -c cryptsetup-luksConvertKey -s i
complete -c cryptsetup-luksConvertKey -s t
complete -c cryptsetup-luksConvertKey -l force-password
complete -c cryptsetup-luksConvertKey -l batch-mode -s q
complete -c cryptsetup-luksConvertKey -l debug -l debug-json
complete -c cryptsetup-luksConvertKey -l version -s V
complete -c cryptsetup-luksConvertKey -l usage
complete -c cryptsetup-luksConvertKey -l help -s '?'

