# cryptsetup-luksSuspend
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksSuspend.8.gz
complete -c cryptsetup-luksSuspend -l header
complete -c cryptsetup-luksSuspend -l disable-locks
complete -c cryptsetup-luksSuspend -l batch-mode -s q
complete -c cryptsetup-luksSuspend -l debug -l debug-json
complete -c cryptsetup-luksSuspend -l version -s V
complete -c cryptsetup-luksSuspend -l usage
complete -c cryptsetup-luksSuspend -l help -s '?'

