# cryptsetup-isLuks
# Autogenerated from man page /usr/share/man/man8/cryptsetup-isLuks.8.gz
complete -c cryptsetup-isLuks -l verbose -s v
complete -c cryptsetup-isLuks -l type
complete -c cryptsetup-isLuks -l header
complete -c cryptsetup-isLuks -l disable-locks
complete -c cryptsetup-isLuks -l batch-mode -s q
complete -c cryptsetup-isLuks -l debug -l debug-json
complete -c cryptsetup-isLuks -l version -s V
complete -c cryptsetup-isLuks -l usage
complete -c cryptsetup-isLuks -l help -s '?'

