# cryptsetup-open
# Autogenerated from man page /usr/share/man/man8/cryptsetup-open.8.gz
complete -c cryptsetup-open -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-open -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-open -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-open -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-open -l test-passphrase -l header -l key-slot
complete -c cryptsetup-open -l volume-key-file -l token-only
complete -c cryptsetup-open -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-open -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-open -l persistent -d loopAES
complete -c cryptsetup-open -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-open -l tcrypt-backup
complete -c cryptsetup-open -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-open -l veracrypt-query-pim
complete -c cryptsetup-open -l cipher
complete -c cryptsetup-open -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-open -s h
complete -c cryptsetup-open -s c
complete -c cryptsetup-open -s y
complete -c cryptsetup-open -s d
complete -c cryptsetup-open -s l
complete -c cryptsetup-open -l master-key-file
complete -c cryptsetup-open -s S
complete -c cryptsetup-open -s s
complete -c cryptsetup-open -s b
complete -c cryptsetup-open -s o
complete -c cryptsetup-open -s p
complete -c cryptsetup-open -s r
complete -c cryptsetup-open -s t
complete -c cryptsetup-open -s T
complete -c cryptsetup-open -l perf-same_cpu_crypt
complete -c cryptsetup-open -l perf-submit_from_crypt_cpus
complete -c cryptsetup-open -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-open -l sector-size
complete -c cryptsetup-open -l integrity-no-journal -d persistently
complete -c cryptsetup-open -l tcrypt-system
complete -c cryptsetup-open -l batch-mode -s q
complete -c cryptsetup-open -l debug -l debug-json
complete -c cryptsetup-open -l version -s V
complete -c cryptsetup-open -l usage
complete -c cryptsetup-open -l help -s '?'

