# cryptsetup-luksRemoveKey
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksRemoveKey.8.gz
complete -c cryptsetup-luksRemoveKey -l header -l disable-locks -l type -l timeout -l verify-passphrase
complete -c cryptsetup-luksRemoveKey -s y
complete -c cryptsetup-luksRemoveKey -l key-file -s d
complete -c cryptsetup-luksRemoveKey -l keyfile-offset
complete -c cryptsetup-luksRemoveKey -l keyfile-size -s l
complete -c cryptsetup-luksRemoveKey -s t
complete -c cryptsetup-luksRemoveKey -l batch-mode -s q
complete -c cryptsetup-luksRemoveKey -l debug -l debug-json
complete -c cryptsetup-luksRemoveKey -l version -s V
complete -c cryptsetup-luksRemoveKey -l usage
complete -c cryptsetup-luksRemoveKey -l help -s '?'

