# cryptsetup-fvault2Dump
# Autogenerated from man page /usr/share/man/man8/cryptsetup-fvault2Dump.8.gz
complete -c cryptsetup-fvault2Dump -l keyfile-offset -l keyfile-size -l timeout -d OPTIONS
complete -c cryptsetup-fvault2Dump -l key-file -s d
complete -c cryptsetup-fvault2Dump -s l
complete -c cryptsetup-fvault2Dump -l volume-key-file -l master-key-file
complete -c cryptsetup-fvault2Dump -l dump-volume-key -l dump-master-key
complete -c cryptsetup-fvault2Dump -s t
complete -c cryptsetup-fvault2Dump -l batch-mode -s q
complete -c cryptsetup-fvault2Dump -l debug -l debug-json
complete -c cryptsetup-fvault2Dump -l version -s V
complete -c cryptsetup-fvault2Dump -l usage
complete -c cryptsetup-fvault2Dump -l help -s '?'

