# dbus-binding-tool
# Autogenerated from man page /usr/share/man/man1/dbus-binding-tool.1.gz
complete -c dbus-binding-tool -l force -d 'Overwrite the output file if it already exists with a newer timestamp than th…'
complete -c dbus-binding-tool -l help -d 'Display usage information'
complete -c dbus-binding-tool -l ignore-unsupported -d 'If set, then unsupported signatures for <method> parameters are ignored'
complete -c dbus-binding-tool -l mode -d 'If the value is "glib-client", then client bindings are generated'
complete -c dbus-binding-tool -l output -d 'Specify the output file'
complete -c dbus-binding-tool -l prefix -d 'Functions in the generated output are prefixed with the symbol-prefix value'
complete -c dbus-binding-tool -l version -d 'Display the version number of the dbus-binding-tool command.  OPERANDS'

