# debugedit
# Autogenerated from man page /usr/share/man/man1/debugedit.1.gz
complete -c debugedit -s b -l base-dir -d 'base build directory of objects'
complete -c debugedit -s d -l dest-dir -d 'directory to rewrite base-dir into'
complete -c debugedit -s l -l list-file -d 'file where to put list of source and header file names'
complete -c debugedit -s i -l build-id -d 'recompute build ID note and print ID on stdout'
complete -c debugedit -s s -l build-id-seed -d 'if recomputing the build ID note use this string as hash seed'
complete -c debugedit -s n -l no-recompute-build-id -d 'do not recompute build ID note even when-i or -s are given '
complete -c debugedit -s '?' -l help -d 'Show this help message'
complete -c debugedit -s u -l usage -d 'Display brief usage message'
complete -c debugedit -s V -l version -d 'Show debugedit version'

