# derb
# Autogenerated from man page /usr/share/man/man1/derb.1.gz
complete -c derb -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c derb -s V -l version -d 'Print the version of  derb and exit'
complete -c derb -s v -l verbose -d 'Display extra informative messages during execution'
complete -c derb -s A -l suppressAliases -d 'Don\'t follow aliases when producing output'
complete -c derb -s e -l encoding -d 'Set the encoding used to write output files to R encoding '
complete -c derb -l bom -d 'Write a byte order mark (BOM) at the beginning of the file'
complete -c derb -s l -l locale -d 'Set the  locale for the resource bundle, which is used both in the generated …'
complete -c derb -s t -l truncate -d 'Truncate individual resources (strings or binary data) to  size bytes'
complete -c derb -s s -l sourcedir -d 'Set the source directory to R source '
complete -c derb -s d -l destdir -d 'Set the destination directory to R destination '
complete -c derb -s i -l icudatadir -d 'Look for any necessary ICU data files in R directory '
complete -c derb -l to-stdout -s c -d 'option is used, however, the text will be written on the standard output'

