# djxl
# Autogenerated from man page /usr/share/man/man1/djxl.1.gz
complete -c djxl -s h -l help -d 'Displays the options that djxl supports'
complete -c djxl -s j -l pixels_to_jpeg -d 'By default, if the input JPEG XL contains a recompressed JPEG file, djxl reco…'
complete -c djxl -s q -l jpeg_quality -d 'When decoding to . jpg, use this output quality'

