# dmeventd
# Autogenerated from man page /usr/share/man/man8/dmeventd.8.gz
complete -c dmeventd -s d -d 'Repeat from 1 to 3 times '
complete -c dmeventd -s f -d 'Don\'t fork, run in the foreground'
complete -c dmeventd -s h -d 'Show help information'
complete -c dmeventd -s l -d 'Log through stdout and stderr instead of syslog'
complete -c dmeventd -s '?' -d 'Show help information on stderr'
complete -c dmeventd -s R -d 'Replace a running dmeventd instance.  The running dmeventd must be version 2'
complete -c dmeventd -o dd
complete -c dmeventd -o ddd -d 'to increase the detail of debug messages sent to syslog'
complete -c dmeventd -s V -d 'Show version of dmeventd'

