# dumpiso
# Autogenerated from man page /usr/share/man/man1/dumpiso.1.gz
complete -c dumpiso -s c -l channels -d 'Sets the channels to listen on'
complete -c dumpiso -s p -l port -d 'Choose port PORT for receiving'
complete -c dumpiso -s h -l help -d 'Show help text and exit'

