# efibootdump
# Autogenerated from man page /usr/share/man/man8/efibootdump.8.gz
complete -c efibootdump -s g -l guid -d 'Any variables specified by name have the specified GUID'
complete -c efibootdump -s f -l file -d 'Read a single boot variable from the specified file'

