# efivar
# Autogenerated from man page /usr/share/man/man1/efivar.1.gz
complete -c efivar -s A -l attributes -d 'attributes to use on append'
complete -c efivar -s l -l list -d 'list current variables'
complete -c efivar -s p -l print -d 'print variable specified by --name'
complete -c efivar -s D -l dmpstore -d 'use DMPSTORE format when exporting'
complete -c efivar -s d -l print-decimal -d 'print variable in decimal format values specified by --name'
complete -c efivar -s n -l name -d 'variable to manipulate, in the form 8be4df61-93ca-11d2-aa0d-00e098032b8c-Boot…'
complete -c efivar -s a -l append -d 'append to variable specified by --name'
complete -c efivar -s f -l datafile -d 'load or save variable contents from <file>'
complete -c efivar -s e -l export -d 'export variable to <file>'
complete -c efivar -s i -l import -d 'import variable from <file>'
complete -c efivar -s L -l list-guids -d 'show internal guid list'
complete -c efivar -s w -l write -d 'write to variable specified by --name . SS "Help options:"'
complete -c efivar -s '?' -l help -d 'Show this help message'
complete -c efivar -l usage -d 'Display brief usage message'

