# fadvise
# Autogenerated from man page /usr/share/man/man1/fadvise.1.gz
complete -c fadvise -s d -l fd
complete -c fadvise -s a -l advice
complete -c fadvise -s o -l offset
complete -c fadvise -s l -l length
complete -c fadvise -s h -l help
complete -c fadvise -s V -l version

