# fakeroot
# Autogenerated from man page /usr/share/man/man1/fakeroot.1.gz
complete -c fakeroot -s l -l lib -d 'Specify an alternative wrapper library'
complete -c fakeroot -l faked -d 'Specify an alternative binary to use as faked'
complete -c fakeroot -s s -d 'Save the fakeroot environment to save-file on exit'
complete -c fakeroot -s i -d 'Load a fakeroot environment previously saved using -s from load-file'
complete -c fakeroot -s u -l unknown-is-real -d 'Use the real ownership of files previously unknown to fakeroot instead of pre…'
complete -c fakeroot -s b -d 'Specify fd base (TCP mode only)'
complete -c fakeroot -s h -d 'Display help'
complete -c fakeroot -s v -d 'Display version'
complete -c fakeroot -o rw-r--r--

