# faked
# Autogenerated from man page /usr/share/man/man1/faked.1.gz
complete -c faked -l debug -d 'Print debugging information on stderr'
complete -c faked -l foreground -d 'Don\'t fork into the background'
complete -c faked -l cleanup -d 'Cleanup the semaphores'
complete -c faked -l key -d 'Don\'t allocate a new communication channel, but use channel specified by key'
complete -c faked -l save-file -d 'Save the environment to save-file on exit'
complete -c faked -l load -d 'Load a previously saved environment from the standard input'
complete -c faked -l unknown-is-real -d 'Use real ownership of previously-unknown files instead of setting them to roo…'
complete -c faked -l port -d 'Use TCP port tcp-port'

