# fax2ps
# Autogenerated from man page /usr/share/man/man1/fax2ps.1.gz
complete -c fax2ps -s p -d 'Print only the indicated page'
complete -c fax2ps -s x -d 'Use resolution as the horizontal resolution, in dots/inch, of the image data'
complete -c fax2ps -s y -d 'Use resolution as the vertical resolution, in lines/inch, of the image data'
complete -c fax2ps -s S -d 'Scale each page of image data to fill the output page dimensions'
complete -c fax2ps -s W -d 'Use width as the width, in inches, of the output page'
complete -c fax2ps -s H -d 'Use height as the height, in inches, of the output page'

