# fc-list
# Autogenerated from man page /usr/share/man/man1/fc-list.1.gz
complete -c fc-list -s v -l verbose -d 'Print verbose output of the whole font pattern for each match, or elements if…'
complete -c fc-list -s f -l format -d 'Format output according to the format specifier format'
complete -c fc-list -s q -l quiet -d 'Suppress all normal output.  returns 1 as the error code if no fonts matched'
complete -c fc-list -s V -l version -d 'Show version of the program and exit'
complete -c fc-list -s h -l help -d 'Show summary of options'

