# fc-pattern
# Autogenerated from man page /usr/share/man/man1/fc-pattern.1.gz
complete -c fc-pattern -s c -l config -d 'Perform config substitution on pattern'
complete -c fc-pattern -s d -l default -d 'Perform default substitution on pattern'
complete -c fc-pattern -s f -l format -d 'Format output according to the format specifier format'
complete -c fc-pattern -s V -l version -d 'Show version of the program and exit'
complete -c fc-pattern -s h -l help -d 'Show summary of options'

