# fc-query
# Autogenerated from man page /usr/share/man/man1/fc-query.1.gz
complete -c fc-query -s b -l ignore-blanks -d 'Ignore blanks to compute languages'
complete -c fc-query -s i -l index -d 'Only query face indexed index of each file'
complete -c fc-query -s f -l format -d 'Format output according to the format specifier format'
complete -c fc-query -s V -l version -d 'Show version of the program and exit'
complete -c fc-query -s h -l help -d 'Show summary of options'

