# fc-scan
# Autogenerated from man page /usr/share/man/man1/fc-scan.1.gz
complete -c fc-scan -s f -l format -d 'Format output according to the format specifier format'
complete -c fc-scan -s V -l version -d 'Show version of the program and exit'
complete -c fc-scan -s h -l help -d 'Show summary of options'

