# fish
# Autogenerated from man page /usr/share/man/man1/fish.1.gz
complete -c fish -s c -l command -d 'Evaluate the specified commands instead of reading from the commandline, pass…'
complete -c fish -s C -l init-command -d 'Evaluate specified commands after reading the configuration but before execut…'
complete -c fish -s d -l debug -d 'Enables debug output and specify a pattern for matching debug categories'
complete -c fish -s o -l debug-output -d 'Specifies a file path to receive the debug output, including categories and  …'
complete -c fish -s i -l interactive -d 'The shell is interactive'
complete -c fish -s l -l login -d 'Act as if invoked as a login shell'
complete -c fish -s N -l no-config -d 'Do not read configuration files'
complete -c fish -s n -l no-execute -d 'Do not execute any commands, only perform syntax checking'
complete -c fish -s p -l profile -d 'when fish exits, output timing information on all executed commands to the sp…'
complete -c fish -l profile-startup -d 'Will write timing for fish startup to specified file'
complete -c fish -s P -l private -d 'Enables \\%private mode: fish will not access old or store new history'
complete -c fish -l print-rusage-self -d 'When fish exits, output stats from getrusage'
complete -c fish -l print-debug-categories -d 'Print all debug categories, and then exit'
complete -c fish -s v -l version -d 'Print version and exit'
complete -c fish -s f -l features -d 'Enables one or more comma-separated %feature flags'

