# fish_indent
# Autogenerated from man page /usr/share/man/man1/fish_indent.1.gz
complete -c fish_indent -s w -l write -d 'Indents a specified file and immediately writes to that file'
complete -c fish_indent -s i -l no-indent -d 'Do not indent commands; only reformat to one job per line'
complete -c fish_indent -s c -l check -d 'Do not indent, only return 0 if the code is already indented as fish_indent w…'
complete -c fish_indent -s v -l version -d 'Displays the current fish version and then exits'
complete -c fish_indent -l ansi -d 'Colorizes the output using ANSI escape sequences, appropriate for the current…'
complete -c fish_indent -l html -d 'Outputs HTML, which supports syntax highlighting if the appropriate CSS is de…'
complete -c fish_indent -s d -l debug -d 'Enable debug output and specify a pattern for matching debug categories'
complete -c fish_indent -s o -l debug-output -d 'Specify a file path to receive the debug output, including categories and fis…'
complete -c fish_indent -l dump-parse-tree -d 'Dumps information about the parsed statements to standard error'
complete -c fish_indent -s h -l help -d 'Displays help about using this command'

