# fsck.minix
# Autogenerated from man page /usr/share/man/man8/fsck.minix.8.gz
complete -c 'fsck.minix' -s l -l list
complete -c 'fsck.minix' -s r -l repair
complete -c 'fsck.minix' -s a -l auto
complete -c 'fsck.minix' -s v -l verbose
complete -c 'fsck.minix' -s s -l super
complete -c 'fsck.minix' -s m -l uncleared
complete -c 'fsck.minix' -s f -l force
complete -c 'fsck.minix' -s h -l help
complete -c 'fsck.minix' -s V -l version

