# fsck.cramfs
# Autogenerated from man page /usr/share/man/man8/fsck.cramfs.8.gz
complete -c 'fsck.cramfs' -s v -l verbose
complete -c 'fsck.cramfs' -s b -l blocksize
complete -c 'fsck.cramfs' -l extract
complete -c 'fsck.cramfs' -s a
complete -c 'fsck.cramfs' -s y
complete -c 'fsck.cramfs' -s h -l help
complete -c 'fsck.cramfs' -s V -l version

