# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.8.gz
complete -c fsck -s l
complete -c fsck -s r
complete -c fsck -s s
complete -c fsck -s t
complete -c fsck -s A
complete -c fsck -s C
complete -c fsck -s M
complete -c fsck -s N
complete -c fsck -s P
complete -c fsck -s R
complete -c fsck -s T
complete -c fsck -s V
complete -c fsck -s '?' -l help
complete -c fsck -l version

