# gcov-dump
# Autogenerated from man page /usr/share/man/man1/gcov-dump.1.gz
complete -c gcov-dump -s h -d 'X Item "-h"'
complete -c gcov-dump -l help -d 'X Item "--help" '
complete -c gcov-dump -s l -d 'X Item "-l"'
complete -c gcov-dump -l long -d 'X Item "--long" . PD Dump content of records'
complete -c gcov-dump -s p -d 'X Item "-p"'
complete -c gcov-dump -l positions -d 'X Item "--positions" . PD Dump positions of records'
complete -c gcov-dump -s r -d 'X Item "-r"'
complete -c gcov-dump -l raw -d 'X Item "--raw" . PD Print content records in raw format'
complete -c gcov-dump -s s -d 'X Item "-s"'
complete -c gcov-dump -l stable -d 'X Item "--stable" . PD Print content in stable format usable for comparison'
complete -c gcov-dump -s v -d 'X Item "-v"'
complete -c gcov-dump -l version -d 'Display the gcov-dump version number (on the standard output), and exit witho…'

