# gdbmtool
# Autogenerated from man page /usr/share/man/man1/gdbmtool.1.gz
complete -c gdbmtool -s b -l block-size -d 'Set block size'
complete -c gdbmtool -s c -l cache-size -d 'Set cache size'
complete -c gdbmtool -s f -l file -d 'Read commands from FILE, instead of from the standard input'
complete -c gdbmtool -s l -l no-lock -d 'Disable file locking'
complete -c gdbmtool -s m -l no-mmap -d 'Do not use  mmap (2)'
complete -c gdbmtool -s n -l newdb -d 'Create the database, truncating it if it already exists'
complete -c gdbmtool -s q -l quiet -d 'Don\'t print initial banner'
complete -c gdbmtool -s r -l read-only -d 'Open database in read-only mode'
complete -c gdbmtool -s s -l synchronize -d 'Synchronize to disk after each write'
complete -c gdbmtool -s h -l help -d 'Print a short usage summary'
complete -c gdbmtool -l usage -d 'Print a list of available options'
complete -c gdbmtool -s V -l version -d 'Print program version SHELL COMMANDS'

