# gdbm_dump
# Autogenerated from man page /usr/share/man/man1/gdbm_dump.1.gz
complete -c gdbm_dump -s H -l format -d 'Select dump format'
complete -c gdbm_dump -s h -l help -d 'Print a short usage summary'
complete -c gdbm_dump -l usage -d 'Print a list of available options'
complete -c gdbm_dump -s V -l version -d 'Print program version SEE ALSO gdbm_load (1), gdbmtool (1), gdbm (3)'

