# genbrk
# Autogenerated from man page /usr/share/man/man1/genbrk.1.gz
complete -c genbrk -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c genbrk -s V -l version -d 'Print the version of  genbrk and exit'
complete -c genbrk -s c -l copyright -d 'Embeds the standard ICU copyright into the R output-file '
complete -c genbrk -s v -l verbose -d 'Display extra informative messages during execution'
complete -c genbrk -s d -l destdir -d 'Set the destination directory of the R output-file to R destination '
complete -c genbrk -s i -l icudatadir -d 'Look for any necessary ICU data files in R directory '
complete -c genbrk -s r -l rules -d 'The source file to read'
complete -c genbrk -s o -l out -d 'The output data file to write'

