# gencmn
# Autogenerated from man page /usr/share/man/man8/gencmn.8.gz
complete -c gencmn -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c gencmn -s v -l verbose -d 'Display extra informative messages during execution'
complete -c gencmn -s c -l copyright -d 'Include the ICU copyright notice in the resulting data'
complete -c gencmn -s C -l comment -d 'Include the specified  comment in the resulting data instead of the ICU copyr…'
complete -c gencmn -s d -l destdir -d 'Set the destination directory to R destination '
complete -c gencmn -s n -l name -d 'Set the data name to  name instead of the default'
complete -c gencmn -s t -l type -d 'Use  type as the type of the data'
complete -c gencmn -s S -l source -d 'Write a C source file with the table of contents of the data'
complete -c gencmn -s e -l entrypoint -d 'Set the data entry point (used for linking against the data in a shared libra…'

