# gencnval
# Autogenerated from man page /usr/share/man/man1/gencnval.1.gz
complete -c gencnval -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c gencnval -s v -l verbose -d 'Display verbose output'
complete -c gencnval -s c -l copyright -d 'Include a copyright notice in the binary data'
complete -c gencnval -s s -l sourcedir -d 'Set the source directory to R source '
complete -c gencnval -s d -l destdir -d 'Set the destination directory to destination '

