# genccode
# Autogenerated from man page /usr/share/man/man8/genccode.8.gz
complete -c genccode -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c genccode -s a -l assembly -d 'Output assembly code instead of C code'
complete -c genccode -s d -l destdir -d 'Set the destination directory to R destination '
complete -c genccode -s n -l name -d 'Set the data name to  name instead of the default'
complete -c genccode -s f -l filename -d 'Normally, an ICU data file such as mydata. icu will be turned into mydata_icu'
complete -c genccode -s e -l entrypoint -d 'Set the data entry point (used for linking against the data in a shared libra…'
complete -c genccode -s t -l type -d 'option).  VERSION 73. 2 COPYRIGHT Copyright (C) 2000-2004 IBM, Inc'

