# genl-ctrl-list
# Autogenerated from man page /usr/share/man/man8/genl-ctrl-list.8.gz
complete -c genl-ctrl-list -s h -l help -d 'Print help text to console and exit'
complete -c genl-ctrl-list -s v -l version -d 'Print versioning information to console and exit'
complete -c genl-ctrl-list -s d -l details -d 'Include additional detailed information for each Generic Netlink family that …'

