# genrb
# Autogenerated from man page /usr/share/man/man1/genrb.1.gz
complete -c genrb -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c genrb -s V -l version -d 'Print the version of  genrb and exit'
complete -c genrb -s v -l verbose -d 'Display extra informative messages during execution'
complete -c genrb -s e -l encoding -d 'Set the encoding used to read input files to R encoding '
complete -c genrb -s j -l write-java -d 'Generate a Java source code for use with ICU4J'
complete -c genrb -s s -l sourcedir -d 'Set the source directory to R source '
complete -c genrb -s d -l destdir -d 'Set the destination directory to R destination '
complete -c genrb -s i -l icudatadir -d 'Look for any necessary ICU data files in directory '

