# gensprep
# Autogenerated from man page /usr/share/man/man8/gensprep.8.gz
complete -c gensprep -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c gensprep -s v -l verbose -d 'Display extra informative messages during execution'
complete -c gensprep -s c -l copyright -d 'Include a copyright notice into the binary data'
complete -c gensprep -s s -l sourcedir -d 'Set the source directory to R source '
complete -c gensprep -s d -l destdir -d 'Set the destination directory to destination '

