# getfattr
# Autogenerated from man page /usr/share/man/man1/getfattr.1.gz
complete -c getfattr -s n -l name -d 'Dump the value of the named extended attribute'
complete -c getfattr -s d -l dump -d 'Dump the values of all matched extended attributes'
complete -c getfattr -s e -l encoding -d 'Encode values after retrieving them'
complete -c getfattr -s h -l no-dereference -d 'Do not dereference symlinks'
complete -c getfattr -s m -l match -d 'Only include attributes with names matching the regular expression R pattern '
complete -c getfattr -l absolute-names -d 'Do not strip leading slash characters (\'/\')'
complete -c getfattr -l only-values -d 'Dump out the raw extended attribute value(s) without encoding them'
complete -c getfattr -s R -l recursive -d 'List the attributes of all files and directories recursively'
complete -c getfattr -s L -l logical -d 'Logical walk, follow symbolic links to directories'
complete -c getfattr -s P -l physical -d 'Physical walk, do not follow symbolic links to directories'
complete -c getfattr -l version -d 'Print the version of  getfattr and exit'
complete -c getfattr -l help -d 'Print help explaining the command line options'

