# getsubids
# Autogenerated from man page /usr/share/man/man1/getsubids.1.gz
complete -c getsubids -s g -d 'List the subordinate group ID ranges'
complete -c getsubids -s h -d 'Display help message and exit'

