# gettextize
# Autogenerated from man page /usr/share/man/man1/gettextize.1.gz
complete -c gettextize -l help -d 'print this help and exit'
complete -c gettextize -l version -d 'print version information and exit'
complete -c gettextize -s f -l force -d 'force writing of new files even if old exist'
complete -c gettextize -l po-dir -d 'specify directory with PO files'
complete -c gettextize -l no-changelog -d 'don\'t update or create ChangeLog files'
complete -c gettextize -l symlink -d 'make symbolic links instead of copying files'
complete -c gettextize -s n -l dry-run -d 'print modifications but don\'t perform them AUTHOR Written by Ulrich Drepper R…'

