# getunimap
# Autogenerated from man page /usr/share/man/man8/getunimap.8.gz
complete -c getunimap -s C -d 'option may be used with Linux 2. 6'
complete -c getunimap -s s -d 'option will sort and merge elements, sorting on font character'

