# gif2webp
# Autogenerated from man page /usr/share/man/man1/gif2webp.1.gz
complete -c gif2webp -s o -d 'Specify the name of the output WebP file'
complete -c gif2webp -s h -o help -d 'Usage information'
complete -c gif2webp -o version -d 'Print the version number (as major. minor. revision) and exit'
complete -c gif2webp -o lossy -d 'Encode the image using lossy compression'
complete -c gif2webp -o mixed -d 'Mixed compression mode: optimize compression of the image by picking either l…'
complete -c gif2webp -s q -d 'Specify the compression factor for RGB channels between 0 and 100'
complete -c gif2webp -s m -d 'Specify the compression method to use'
complete -c gif2webp -o min_size -d 'Encode image to achieve smallest size'
complete -c gif2webp -o kmax -d 'Specify the minimum and maximum distance between consecutive key frames (inde…'
complete -c gif2webp -o metadata -d 'A comma separated list of metadata to copy from the input to the output if pr…'
complete -c gif2webp -s f -d 'For lossy encoding only (specified by the -lossy option)'
complete -c gif2webp -o mt -d 'Use multi-threading for encoding, if possible'
complete -c gif2webp -o loop_compatibility -d 'If enabled, handle the loop information in a compatible fashion for Chrome ve…'
complete -c gif2webp -s v -d 'Print extra information'
complete -c gif2webp -o kmin
complete -c gif2webp -o quiet -d 'Do not print anything'

