# gif2rgb
# Autogenerated from man page /usr/share/man/man1/gif2rgb.1.gz
complete -c gif2rgb -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gif2rgb -s 1 -d 'Only one file in the format of RGBRGB'
complete -c gif2rgb -s c -d 'Specifies number of colors to use in RGB-to-GIF conversions, in bits per pixe…'
complete -c gif2rgb -s s -d 'Sets RGB-to-GIF conversion mode and specifies the size of the image to read'
complete -c gif2rgb -s o -d 'specifies the name of the out file (see also `-1\\*(Aq above)'
complete -c gif2rgb -s h -d 'Print one line of command line help, similar to Usage above'

