# gifbg
# Autogenerated from man page /usr/share/man/man1/gifbg.1.gz
complete -c gifbg -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gifbg -s l -d 'Numeric, nmber of levels the color will be scaled to.  Default is 16'
complete -c gifbg -s c -d 'What to use as the primary background color to scale'
complete -c gifbg -s m -d 'Minimum intensity (in percent) to scale color.  Default 10%'
complete -c gifbg -s M -d 'Maximum intensity (in percent) to scale color.  Default 100%'
complete -c gifbg -s s -d 'Size of image to create.  Default 640 by 350'
complete -c gifbg -s h -d 'Print one line of command line help, similar to Usage above'
complete -c gifbg -s d

