# gifclrmp
# Autogenerated from man page /usr/share/man/man1/gifclrmp.1.gz
complete -c gifclrmp -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gifclrmp -s s -d 'Select the global screen color map'
complete -c gifclrmp -s l -d 'Load color map from this file instead of selected color map'
complete -c gifclrmp -s t -d 'Change color index values'
complete -c gifclrmp -s g -d 'Apply gamma correction to selected color map'
complete -c gifclrmp -s i -d 'Select the color map of the numbered image'
complete -c gifclrmp -s h -d 'Print one command line help, similar to Usage above'

