# giffix
# Autogenerated from man page /usr/share/man/man1/giffix.1.gz
complete -c giffix -s t -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c giffix -s h -d 'Print one line of command line help, similar to Usage above'

