# gifhisto
# Autogenerated from man page /usr/share/man/man1/gifhisto.1.gz
complete -c gifhisto -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gifhisto -s t -d 'Force output to be text file of the following form: (colormap size) lines eac…'
complete -c gifhisto -s s -d 'Size of GIF histogram file'
complete -c gifhisto -s n -d 'Image number to test.  Default is one'
complete -c gifhisto -s b -d 'Zeros the background color count'
complete -c gifhisto -s h -d 'Print one line of command line help, similar to Usage above'

