# gifwedge
# Autogenerated from man page /usr/share/man/man1/gifwedge.1.gz
complete -c gifwedge -s v -d 'Verbose mode (show progress).  Enables printout of running scan lines'
complete -c gifwedge -s l -d 'Set number of intensity levels per color'
complete -c gifwedge -s s -d 'Force image size to be SizeX by SizeY pixels'
complete -c gifwedge -s h -d 'Print one line command line help, similar to Usage above'

