# git-archive
# Autogenerated from man page /usr/share/man/man1/git-archive.1.gz
complete -c git-archive -l format -d 'Format of the resulting archive.  Possible values are tar, zip, tar'
complete -c git-archive -s l -l list -d 'Show all available formats'
complete -c git-archive -s v -l verbose -d 'Report progress to stderr'
complete -c git-archive -l prefix -d 'Prepend <prefix>/ to paths in the archive'
complete -c git-archive -s o -l output -d 'Write the archive to <file> instead of stdout'
complete -c git-archive -l add-file -d 'Add a non-tracked file to the archive.  Can be repeated to add multiple files'
complete -c git-archive -l add-virtual-file -d 'Add the specified contents to the archive'
complete -c git-archive -l worktree-attributes -d 'Look for attributes in '
complete -c git-archive -l mtime -d 'Set modification time of archive entries'
complete -c git-archive -l remote -d 'Instead of making a tar archive from the local repository, retrieve a tar arc…'
complete -c git-archive -l exec -d 'Used with --remote to specify the path to the git-upload-archive on the remot…'
complete -c git-archive -o '<digit>'
complete -c git-archive -s 0 -d '(store-only) to'
complete -c git-archive -s 9 -d '(best ratio).  Default is'
complete -c git-archive -s 6 -d 'if not given'
complete -c git-archive -o '<number>'

