# git-commit-graph
# Autogenerated from man page /usr/share/man/man1/git-commit-graph.1.gz
complete -c git-commit-graph -l object-dir -d 'Use given directory for the location of packfiles and commit-graph file'
complete -c git-commit-graph -l progress -d 'Turn progress on/off explicitly'
complete -c git-commit-graph -l stdin-packs -d 'option, generate the new commit graph by walking objects only in the specifie…'
complete -c git-commit-graph -l stdin-commits -d or
complete -c git-commit-graph -l reachable
complete -c git-commit-graph -l append -d 'option, include all commits that are present in the existing commit-graph file'
complete -c git-commit-graph -l changed-paths -d 'option, compute and write information about the paths changed between a commi…'
complete -c git-commit-graph -l no-changed-paths -d 'to stop storing this data'
complete -c git-commit-graph -l max-new-filters -d 'option, generate at most n new Bloom filters (if'
complete -c git-commit-graph -s 1
complete -c git-commit-graph -l split -d 'commitGraph. maxNewFilters configuration'
complete -c git-commit-graph -l size-multiple -d 'is not specified, let X equal 2'
complete -c git-commit-graph -l max-commits -d 'is specified with M a positive integer, and the new tip file would have more …'
complete -c git-commit-graph -l expire-time -d 'is not specified, let datetime be the current time'
complete -c git-commit-graph -l shallow -d 'option, only check the tip commit-graph file in a chain of split commit-graphs'

