# git-difftool
# Autogenerated from man page /usr/share/man/man1/git-difftool.1.gz
complete -c git-difftool -s d -l dir-diff -d 'Copy the modified files to a temporary location and perform a directory diff …'
complete -c git-difftool -s y -l no-prompt -d 'Do not prompt before launching a diff tool'
complete -c git-difftool -l prompt -d 'Prompt before each invocation of the diff tool'
complete -c git-difftool -l rotate-to -d 'Start showing the diff for the given path, the paths before it will move to e…'
complete -c git-difftool -l skip-to -d 'Start showing the diff for the given path, skipping all the paths before it'
complete -c git-difftool -s t -l tool -d 'Use the diff tool specified by <tool>'
complete -c git-difftool -l tool-help -d 'Print a list of diff tools that may be used with --tool'
complete -c git-difftool -l symlinks -d 'git difftool\\*(Aqs default behavior is create symlinks to the working tree wh…'
complete -c git-difftool -s x -l extcmd -d 'Specify a custom command for viewing diffs'
complete -c git-difftool -s g -l gui -d 'When git-difftool is invoked with the -g or --gui option the default diff too…'
complete -c git-difftool -l trust-exit-code -d 'git-difftool invokes a diff tool individually on each file'
complete -c git-difftool -l no-symlinks -d 'instructs git difftool to create copies instead'
complete -c git-difftool -l no-gui -d 'option can be used to override these settings.  If diff'

