# git-column
# Autogenerated from man page /usr/share/man/man1/git-column.1.gz
complete -c git-column -l command -d 'Look up layout mode using configuration variable column. <name> and column'
complete -c git-column -l mode -d 'Specify layout mode.  See configuration variable column'
complete -c git-column -l raw-mode -d 'Same as --mode but take mode encoded as a number'
complete -c git-column -l width -d 'Specify the terminal width'
complete -c git-column -l indent -d 'String to be printed at the beginning of each line'
complete -c git-column -l nl -d 'String to be printed at the end of each line, including newline character'
complete -c git-column -l padding -d 'The number of spaces between columns.  One space by default'

