# git-mktag
# Autogenerated from man page /usr/share/man/man1/git-mktag.1.gz
complete -c git-mktag -l strict -d 'By default mktag turns on the equivalent of git-fsck(1) --strict mode'
complete -c git-mktag -l no-strict -d 'to disable it'

