# git-rm
# Autogenerated from man page /usr/share/man/man1/git-rm.1.gz
complete -c git-rm -s f -l force -d 'Override the up-to-date check'
complete -c git-rm -s n -l dry-run -d 'Don\'t actually remove any file(s)'
complete -c git-rm -s r -d 'Allow recursive removal when a leading directory name is given'
complete -c git-rm -l cached -d 'Use this option to unstage and remove paths only from the index'
complete -c git-rm -l ignore-unmatch -d 'Exit with a zero status even if no files matched'
complete -c git-rm -l sparse -d 'Allow updating index entries outside of the sparse-checkout cone'
complete -c git-rm -s q -l quiet -d 'git rm normally outputs one line (in the form of an rm command) for each file…'
complete -c git-rm -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-rm -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-rm -l literal-pathspecs

