# git-help
# Autogenerated from man page /usr/share/man/man1/git-help.1.gz
complete -c git-help -s a -l all -d 'Prints all the available commands on the standard output'
complete -c git-help -l no-external-commands -d 'When used with --all, exclude the listing of external "git-*" commands found …'
complete -c git-help -l no-aliases -d 'When used with --all, exclude the listing of configured aliases'
complete -c git-help -l verbose -d 'When used with --all print description for all recognized commands'
complete -c git-help -s c -l config -d 'List all available configuration variables'
complete -c git-help -s g -l guides -d 'Prints a list of the Git concept guides on the standard output'
complete -c git-help -l user-interfaces -d 'Prints a list of the repository, command and file interfaces documentation on…'
complete -c git-help -l developer-interfaces -d 'Print list of file formats, protocols and other developer interfaces document…'
complete -c git-help -s i -l info -d 'Display manual page for the command in the info format'
complete -c git-help -s m -l man -d 'Display manual page for the command in the man format'
complete -c git-help -s w -l web -d 'Display manual page for the command in the web (HTML) format'

