# git-check-attr
# Autogenerated from man page /usr/share/man/man1/git-check-attr.1.gz
complete -c git-check-attr -s a -l all -d 'List all attributes that are associated with the specified paths'
complete -c git-check-attr -l cached -d 'Consider . gitattributes in the index only, ignoring the working tree'
complete -c git-check-attr -l stdin -d 'Read pathnames from the standard input, one per line, instead of from the com…'
complete -c git-check-attr -s z -d 'The output format is modified to be machine-parsable'
complete -c git-check-attr -l source -d 'Check attributes against the specified tree-ish'

