# git-mailsplit
# Autogenerated from man page /usr/share/man/man1/git-mailsplit.1.gz
complete -c git-mailsplit -o 'o<directory>' -d 'Directory in which to place the individual messages'
complete -c git-mailsplit -s b -d 'If any file doesn\'t begin with a From line, assume it is a single mail messag…'
complete -c git-mailsplit -o 'd<prec>' -d 'Instead of the default 4 digits with leading zeros, different precision can b…'
complete -c git-mailsplit -o 'f<nn>' -d 'Skip the first <nn> numbers, for example if -f3 is specified, start the numbe…'
complete -c git-mailsplit -l keep-cr -d 'Do not remove r from lines ending with rn'
complete -c git-mailsplit -l mboxrd -d 'Input is of the "mboxrd" format and "^>+From " line escaping is reversed'

