# git-multi-pack-index
# Autogenerated from man page /usr/share/man/man1/git-multi-pack-index.1.gz
complete -c git-multi-pack-index -l object-dir -d 'Use given directory for the location of Git objects'
complete -c git-multi-pack-index -l progress -d 'Turn progress on/off explicitly'
complete -c git-multi-pack-index -l preferred-pack -d 'Optionally specify the tie-breaking pack used when multiple packs contain the…'
complete -c git-multi-pack-index -l bitmap -d 'Control whether or not a multi-pack bitmap is written'
complete -c git-multi-pack-index -l stdin-packs -d 'Write a multi-pack index containing only the set of line-delimited pack index…'
complete -c git-multi-pack-index -l refs-snapshot -d 'With --bitmap, optionally specify a file which contains a "refs snapshot" tak…'
complete -c git-multi-pack-index -l batch-size -d 'argument is zero, then create a pack containing all objects referenced by the…'

