# git-cvsserver
# Autogenerated from man page /usr/share/man/man1/git-cvsserver.1.gz
complete -c git-cvsserver -l base-path -d 'Prepend path to requested CVSROOT'
complete -c git-cvsserver -l strict-paths -d 'Don\'t allow recursing into subdirectories'
complete -c git-cvsserver -l export-all -d 'Don\'t check for gitcvs. enabled in config'
complete -c git-cvsserver -s V -l version -d 'Print version information and exit'
complete -c git-cvsserver -s h -s H -l help -d 'Print usage information and exit'
complete -c git-cvsserver -s d -d 'master branch to the project-master directory:    cvs co -d project-master ma…'

