# git-for-each-repo
# Autogenerated from man page /usr/share/man/man1/git-for-each-repo.1.gz
complete -c git-for-each-repo -l config -d 'Use the given config variable as a multi-valued list storing absolute path na…'

