# git-receive-pack
# Autogenerated from man page /usr/share/man/man1/git-receive-pack.1.gz
complete -c git-receive-pack -l http-backend-info-refs -d 'Used by git-http-backend(1) to serve up $GIT_URL/info/refs?service=git-receiv…'

