# git-mergetool
# Autogenerated from man page /usr/share/man/man1/git-mergetool.1.gz
complete -c git-mergetool -s t -l tool -d 'Use the merge resolution program specified by <tool>'
complete -c git-mergetool -l tool-help -d 'Print a list of merge tools that may be used with --tool'
complete -c git-mergetool -s y -l no-prompt -d 'Don\'t prompt before each invocation of the merge resolution program'
complete -c git-mergetool -l prompt -d 'Prompt before each invocation of the merge resolution program to give the use…'
complete -c git-mergetool -s g -l gui -d 'When git-mergetool is invoked with the -g or --gui option the default merge t…'
complete -c git-mergetool -l no-gui -d 'This overrides a previous -g or --gui setting or mergetool'
complete -c git-mergetool -o 'O<orderfile>' -d 'Process files in the order specified in the <orderfile>, which has one shell …'
complete -c git-mergetool -o O/dev/null
complete -c git-mergetool -l output -d 'option.  Git will attempt to detect whether meld supports'
complete -c git-mergetool -l auto-merge -d 'is given, meld will merge all non-conflicting parts automatically, highlight …'
complete -c git-mergetool -l ---------------------------------------- -d '|             |           |              | |   LOCAL     |   BASE    |   REMO…'
complete -c git-mergetool -l ------------------------------------------- -d '|  TAB #1  |  TAB #2  |  TAB #3  | <TAB #4> |'

