# git-ls-remote
# Autogenerated from man page /usr/share/man/man1/git-ls-remote.1.gz
complete -c git-ls-remote -s h -l heads -s t -l tags -d 'Limit to only refs/heads and refs/tags, respectively'
complete -c git-ls-remote -l refs -d 'Do not show peeled tags or pseudorefs like HEAD in the output'
complete -c git-ls-remote -s q -l quiet -d 'Do not print remote URL to stderr'
complete -c git-ls-remote -l upload-pack -d 'Specify the full path of git-upload-pack on the remote host'
complete -c git-ls-remote -l exit-code -d 'Exit with status "2" when no matching refs are found in the remote repository'
complete -c git-ls-remote -l get-url -d 'Expand the URL of the given remote repository taking into account any "url'
complete -c git-ls-remote -l symref -d 'In addition to the object pointed by it, show the underlying ref pointed by i…'
complete -c git-ls-remote -l sort -d 'Sort based on the key given'
complete -c git-ls-remote -s o -l server-option -d 'Transmit the given string to the server when communicating using protocol ver…'

