# git-sparse-checkout
# Autogenerated from man page /usr/share/man/man1/git-sparse-checkout.1.gz
complete -c git-sparse-checkout -l stdin -d 'option is provided, the directories or patterns are read from standard in as …'
complete -c git-sparse-checkout -l cone -d 'needed to be specified or core. sparseCheckoutCone needed to be enabled'
complete -c git-sparse-checkout -l no-cone -d 'is passed, the input list is considered a list of patterns'
complete -c git-sparse-checkout -l sparse-index
complete -c git-sparse-checkout -l rules-file -d 'flag the input files are matched against the sparse checkout rules found in <…'
complete -c git-sparse-checkout -s z -d 'flag, the format of the paths input on stdin as well as the output paths are …'

