# git-count-objects
# Autogenerated from man page /usr/share/man/man1/git-count-objects.1.gz
complete -c git-count-objects -s v -l verbose -d 'Report in more detail: . sp count: the number of loose objects '
complete -c git-count-objects -s H -l human-readable -d 'Print sizes in human readable format'

