# git-replace
# Autogenerated from man page /usr/share/man/man1/git-replace.1.gz
complete -c git-replace -s f -l force -d 'If an existing replace ref for the same object exists, it will be overwritten…'
complete -c git-replace -s d -l delete -d 'Delete existing replace refs for the given objects'
complete -c git-replace -l edit -d 'Edit an object\'s content interactively'
complete -c git-replace -l raw -d 'When editing, provide the raw object contents rather than pretty-printed ones'
complete -c git-replace -l graft -d 'Create a graft commit'
complete -c git-replace -l convert-graft-file -d 'Creates graft commits for all entries in $GIT_DIR/info/grafts and deletes tha…'
complete -c git-replace -s l -l list -d 'List replace refs for objects that match the given pattern (or all if no patt…'
complete -c git-replace -l format -d 'When listing, use the specified <format>, which can be one of short, medium a…'

