# git-symbolic-ref
# Autogenerated from man page /usr/share/man/man1/git-symbolic-ref.1.gz
complete -c git-symbolic-ref -s d -l delete -d 'Delete the symbolic ref <name>'
complete -c git-symbolic-ref -s q -l quiet -d 'Do not issue an error message if the <name> is not a symbolic ref but a detac…'
complete -c git-symbolic-ref -l short -d 'When showing the value of <name> as a symbolic ref, try to shorten the value,…'
complete -c git-symbolic-ref -l recurse -l no-recurse -d 'When showing the value of <name> as a symbolic ref, if <name> refers to anoth…'
complete -c git-symbolic-ref -s m -d 'Update the reflog for <name> with <reason>'

