# git-unpack-objects
# Autogenerated from man page /usr/share/man/man1/git-unpack-objects.1.gz
complete -c git-unpack-objects -s n -d 'Dry run.  Check the pack file without actually unpacking the objects'
complete -c git-unpack-objects -s q -d 'The command usually shows percentage progress.  This flag suppresses it'
complete -c git-unpack-objects -s r -d 'When unpacking a corrupt packfile, the command dies at the first corruption'
complete -c git-unpack-objects -l strict -d 'Don\'t write objects with broken content or links'
complete -c git-unpack-objects -l max-input-size -d 'Die, if the pack is larger than <size>'

