# git-mailinfo
# Autogenerated from man page /usr/share/man/man1/git-mailinfo.1.gz
complete -c git-mailinfo -s k -d 'Usually the program removes email cruft from the Subject: header line to extr…'
complete -c git-mailinfo -s b -d 'When -k is not in effect, all leading strings bracketed with [ and ] pairs ar…'
complete -c git-mailinfo -s u -d 'The commit log message, author name and author email are taken from the e-mai…'
complete -c git-mailinfo -l encoding -d 'Similar to -u'
complete -c git-mailinfo -s n -d 'Disable all charset re-coding of the metadata'
complete -c git-mailinfo -s m -l message-id -d 'Copy the Message-ID header at the end of the commit message'
complete -c git-mailinfo -l scissors -d 'Remove everything in body before a scissors line (e. g.  "-- >8 --")'
complete -c git-mailinfo -l no-scissors -d 'Ignore scissors lines.  Useful for overriding mailinfo. scissors settings'
complete -c git-mailinfo -l quoted-cr -d 'Action when processes email messages sent with base64 or quoted-printable enc…'

