# git-archimport
# Autogenerated from man page /usr/share/man/man1/git-archimport.1.gz
complete -c git-archimport -s h -d 'Display usage'
complete -c git-archimport -s v -d 'Verbose output'
complete -c git-archimport -s T -d 'Many tags'
complete -c git-archimport -s f -d 'Use the fast patchset import strategy'
complete -c git-archimport -s o -d 'Use this for compatibility with old-style branch names used by earlier versio…'
complete -c git-archimport -s D -d 'Follow merge ancestry and attempt to import trees that have been merged from'
complete -c git-archimport -s a -d 'Attempt to auto-register archives at http://mirrors. sourcecontrol'
complete -c git-archimport -s t -d 'Override the default tempdir'

