# git-mktree
# Autogenerated from man page /usr/share/man/man1/git-mktree.1.gz
complete -c git-mktree -s z -d 'Read the NUL-terminated ls-tree -z output instead'
complete -c git-mktree -l missing -d 'Allow missing objects'
complete -c git-mktree -l batch -d 'Allow building of more than one tree object before exiting'

