# git-ls-tree
# Autogenerated from man page /usr/share/man/man1/git-ls-tree.1.gz
complete -c git-ls-tree -s d -d 'Show only the named tree entry itself, not its children'
complete -c git-ls-tree -s r -d 'Recurse into sub-trees'
complete -c git-ls-tree -s t -d 'Show tree entries even when going to recurse them'
complete -c git-ls-tree -s l -l long -d 'Show object size of blob (file) entries'
complete -c git-ls-tree -s z -d '0 line termination on output and do not quote filenames'
complete -c git-ls-tree -l name-only -l name-status -d 'List only filenames (instead of the "long" output), one per line'
complete -c git-ls-tree -l object-only -d 'List only names of the objects, one per line'
complete -c git-ls-tree -l abbrev -d 'Instead of showing the full 40-byte hexadecimal object lines, show the shorte…'
complete -c git-ls-tree -l full-name -d 'Instead of showing the path names relative to the current working directory, …'
complete -c git-ls-tree -l full-tree -d 'Do not limit the listing to the current working directory'
complete -c git-ls-tree -l format -d 'A string that interpolates %(fieldname) from the result being shown'

