# git-revert
# Autogenerated from man page /usr/share/man/man1/git-revert.1.gz
complete -c git-revert -s e -l edit -d 'With this option, git revert will let you edit the commit message prior to co…'
complete -c git-revert -s m -l mainline -d 'Usually you cannot revert a merge because you do not know which side of the m…'
complete -c git-revert -l no-edit -d 'With this option, git revert will not start the commit message editor'
complete -c git-revert -l cleanup -d 'This option determines how the commit message will be cleaned up before being…'
complete -c git-revert -s n -l no-commit -d 'Usually the command automatically creates some commits with commit log messag…'
complete -c git-revert -s S -l gpg-sign -l no-gpg-sign -d 'GPG-sign commits'
complete -c git-revert -s s -l signoff -d 'Add a Signed-off-by trailer at the end of the commit message'
complete -c git-revert -l strategy -d 'Use the given merge strategy.  Should only be used once'
complete -c git-revert -o 'X<option>' -l strategy-option -d 'Pass the merge strategy-specific option through to the merge strategy'
complete -c git-revert -l rerere-autoupdate -l no-rerere-autoupdate -d 'After the rerere mechanism reuses a recorded resolution on the current confli…'
complete -c git-revert -l reference -d 'Instead of starting the body of the log message with "This reverts <full obje…'
complete -c git-revert -l no-walk -d option
complete -c git-revert -l continue
complete -c git-revert -l skip
complete -c git-revert -l quit
complete -c git-revert -l abort

