# git-quiltimport
# Autogenerated from man page /usr/share/man/man1/git-quiltimport.1.gz
complete -c git-quiltimport -s n -l dry-run -d 'Walk through the patches in the series and warn if we cannot find all of the …'
complete -c git-quiltimport -l author -d 'The author name and email address to use when no author information can be fo…'
complete -c git-quiltimport -l patches -d 'The directory to find the quilt patches'
complete -c git-quiltimport -l series -d 'The quilt series file'
complete -c git-quiltimport -l keep-non-patch -d 'Pass -b flag to git mailinfo (see git-mailinfo(1))'
complete -c git-quiltimport -s b -d 'flag to git mailinfo (see git-mailinfo(1))'

