# git-fsck
# Autogenerated from man page /usr/share/man/man1/git-fsck.1.gz
complete -c git-fsck -l unreachable -d 'Print out objects that exist but that aren\'t reachable from any of the refere…'
complete -c git-fsck -l dangling -d 'Print objects that exist but that are never directly used (default)'
complete -c git-fsck -l root -d 'Report root nodes'
complete -c git-fsck -l tags -d 'Report tags'
complete -c git-fsck -l cache -d 'Consider any object recorded in the index also as a head node for an unreacha…'
complete -c git-fsck -l no-reflogs -d 'Do not consider commits that are referenced only by an entry in a reflog to b…'
complete -c git-fsck -l full -d 'Check not just objects in GIT_OBJECT_DIRECTORY ($GIT_DIR/objects), but also t…'
complete -c git-fsck -l connectivity-only -d 'Check only the connectivity of reachable objects, making sure that any object…'
complete -c git-fsck -l strict -d 'Enable more strict checking, namely to catch a file mode recorded with g+w bi…'
complete -c git-fsck -l verbose -d 'Be chatty'
complete -c git-fsck -l lost-found -d 'Write dangling objects into . git/lost-found/commit/ or '
complete -c git-fsck -l name-objects -d 'When displaying names of reachable objects, in addition to the SHA-1 also dis…'
complete -c git-fsck -l progress -d 'Progress status is reported on the standard error stream by default when it i…'
complete -c git-fsck -l no-dangling -d 'can be used to omit this information from the output'

