# git-check-ignore
# Autogenerated from man page /usr/share/man/man1/git-check-ignore.1.gz
complete -c git-check-ignore -s q -l quiet -d 'Don\'t output anything, just set exit status'
complete -c git-check-ignore -s v -l verbose -d 'Instead of printing the paths that are excluded, for each path that matches a…'
complete -c git-check-ignore -l stdin -d 'Read pathnames from the standard input, one per line, instead of from the com…'
complete -c git-check-ignore -s z -d 'The output format is modified to be machine-parsable (see below)'
complete -c git-check-ignore -s n -l non-matching -d 'Show given paths which don\'t match any pattern'
complete -c git-check-ignore -l no-index -d 'Don\'t look in the index when undertaking the checks'

