# git-maintenance
# Autogenerated from man page /usr/share/man/man1/git-maintenance.1.gz
complete -c git-maintenance -l auto -d 'When combined with the run subcommand, run maintenance tasks only if certain …'
complete -c git-maintenance -l schedule -d 'When combined with the run subcommand, run maintenance tasks only if certain …'
complete -c git-maintenance -l quiet -d 'Do not report progress or other information over stderr'
complete -c git-maintenance -l task -d 'If this option is specified one or more times, then only run the specified ta…'
complete -c git-maintenance -l scheduler -d 'When combined with the start subcommand, specify the scheduler for running th…'
complete -c git-maintenance -l force -d 'option to return success even when the current repository is not registered'
complete -c git-maintenance -l batch-size -d 'option for the repack subcommand in git-multi-pack-index(1)'

