# git-reset
# Autogenerated from man page /usr/share/man/man1/git-reset.1.gz
complete -c git-reset -s q -l quiet -d 'Be quiet, only report errors'
complete -c git-reset -l refresh -l no-refresh -d 'Refresh the index after a mixed reset.  Enabled by default'
complete -c git-reset -l pathspec-from-file -d 'Pathspec is passed in <file> instead of commandline args'
complete -c git-reset -l pathspec-file-nul -d 'Only meaningful with --pathspec-from-file'
complete -c git-reset -l source -d 'git reset (--patch | -p) [<tree-ish>] [--] [<pathspec>. ]'
complete -c git-reset -l patch -d 'mode.  git reset [<mode>] [<commit>]'
complete -c git-reset -l mixed -d '<mode> must be one of the following:'
complete -c git-reset -l soft
complete -c git-reset -s N -d 'is specified, removed paths are marked as intent-to-add (see git-add(1))'
complete -c git-reset -l hard
complete -c git-reset -l merge
complete -c git-reset -l keep
complete -c git-reset -l recurse-submodules
complete -c git-reset -l literal-pathspecs
complete -c git-reset -s C -d 'option instead'
complete -c git-reset -l amend -d 'option to git-commit(1)'
complete -c git-reset -s c -d 'option specifies to pre-populate the commit message from the original message…'
complete -c git-reset -l -------------------------------------------------- -d ' A       B     C    D     --soft   A       B     D                           …'

