# git-fmt-merge-msg
# Autogenerated from man page /usr/share/man/man1/git-fmt-merge-msg.1.gz
complete -c git-fmt-merge-msg -l log -d 'In addition to branch names, populate the log message with one-line descripti…'
complete -c git-fmt-merge-msg -l no-log -d 'Do not list one-line descriptions from the actual commits being merged'
complete -c git-fmt-merge-msg -l summary -d 'Synonyms to --log and --no-log; these are deprecated and will be removed in t…'
complete -c git-fmt-merge-msg -s m -l message -d 'Use <message> instead of the branch names for the first line of the log messa…'
complete -c git-fmt-merge-msg -l into-name -d 'Prepare the merge message as if merging to the branch <branch>, instead of th…'
complete -c git-fmt-merge-msg -s F -l file -d 'Take the list of merged objects from <file> instead of stdin'

