# git-http-push
# Autogenerated from man page /usr/share/man/man1/git-http-push.1.gz
complete -c git-http-push -l all -d 'Do not assume that the remote repository is complete in its current state, an…'
complete -c git-http-push -l force -d 'Usually, the command refuses to update a remote ref that is not an ancestor o…'
complete -c git-http-push -l dry-run -d 'Do everything except actually send the updates'
complete -c git-http-push -l verbose -d 'Report the list of objects being walked locally and the list of objects succe…'
complete -c git-http-push -s d -s D -d 'Remove <ref> from remote repository'

