# git-upload-pack
# Autogenerated from man page /usr/share/man/man1/git-upload-pack.1.gz
complete -c git-upload-pack -l strict -d 'Do not try <directory>/. git/ if <directory> is no Git directory'
complete -c git-upload-pack -l timeout -d 'Interrupt transfer after <n> seconds of inactivity'
complete -c git-upload-pack -l stateless-rpc -d 'Perform only a single read-write cycle with stdin and stdout'
complete -c git-upload-pack -l http-backend-info-refs -d 'Used by git-http-backend(1) to serve up $GIT_URL/info/refs?service=git-upload…'

