# git-cvsexportcommit
# Autogenerated from man page /usr/share/man/man1/git-cvsexportcommit.1.gz
complete -c git-cvsexportcommit -s c -d 'Commit automatically if the patch applied cleanly'
complete -c git-cvsexportcommit -s p -d 'Be pedantic (paranoid) when applying patches.  Invokes patch with --fuzz=0'
complete -c git-cvsexportcommit -s a -d 'Add authorship information'
complete -c git-cvsexportcommit -s d -d 'Set an alternative CVSROOT to use.  This corresponds to the CVS -d parameter'
complete -c git-cvsexportcommit -s f -d 'Force the merge even if the files are not up to date'
complete -c git-cvsexportcommit -s P -d 'Force the parent commit, even if it is not a direct parent'
complete -c git-cvsexportcommit -s m -d 'Prepend the commit message with the provided prefix'
complete -c git-cvsexportcommit -s u -d 'Update affected files from CVS repository before attempting export'
complete -c git-cvsexportcommit -s k -d 'Reverse CVS keyword expansion (e. g.  $Revision: 1. 2. 3'
complete -c git-cvsexportcommit -s w -d 'Specify the location of the CVS checkout to use for the export'
complete -c git-cvsexportcommit -s W -d 'Tell cvsexportcommit that the current working directory is not only a Git che…'
complete -c git-cvsexportcommit -s v -d Verbose

