# git-imap-send
# Autogenerated from man page /usr/share/man/man1/git-imap-send.1.gz
complete -c git-imap-send -s v -l verbose -d 'Be verbose'
complete -c git-imap-send -s q -l quiet -d 'Be quiet'
complete -c git-imap-send -l curl -d 'Use libcurl to communicate with the IMAP server, unless tunneling into it'
complete -c git-imap-send -l no-curl -d 'Talk to the IMAP server using git\'s own IMAP routines instead of using libcurl'

