# git-pack-refs
# Autogenerated from man page /usr/share/man/man1/git-pack-refs.1.gz
complete -c git-pack-refs -l all -d 'The command by default packs all tags and refs that are already packed, and l…'
complete -c git-pack-refs -l no-prune -d 'The command usually removes loose refs under $GIT_DIR/refs hierarchy after pa…'
complete -c git-pack-refs -l include -d 'Pack refs based on a glob(7) pattern'
complete -c git-pack-refs -l exclude -d 'Do not pack refs matching the given glob(7) pattern'
complete -c git-pack-refs -l no-include -d 'to clear and reset the list of patterns'
complete -c git-pack-refs -l no-exclude -d 'to clear and reset the list of patterns'

