# git-merge-tree
# Autogenerated from man page /usr/share/man/man1/git-merge-tree.1.gz
complete -c git-merge-tree -s z -d 'Do not quote filenames in the <Conflicted file info> section, and end each fi…'
complete -c git-merge-tree -l name-only -d 'In the Conflicted file info section, instead of writing a list of (mode, oid,…'
complete -c git-merge-tree -l messages -d 'Write any informational messages such as "Auto-merging <path>" or CONFLICT no…'
complete -c git-merge-tree -l allow-unrelated-histories -d 'merge-tree will by default error out if the two branches specified share no c…'
complete -c git-merge-tree -l merge-base -d 'Instead of finding the merge-bases for <branch1> and <branch2>, specify a mer…'
complete -c git-merge-tree -l stdin

