# git-http-fetch
# Autogenerated from man page /usr/share/man/man1/git-http-fetch.1.gz
complete -c git-http-fetch -s a -s c -s t -d 'These options are ignored for historical reasons'
complete -c git-http-fetch -s v -d 'Report what is downloaded'
complete -c git-http-fetch -s w -d 'Writes the commit-id into the filename under $GIT_DIR/refs/<filename> on the …'
complete -c git-http-fetch -l stdin -d 'Instead of a commit id on the command line (which is not expected in this cas…'
complete -c git-http-fetch -l packfile -d 'For internal use only'
complete -c git-http-fetch -l index-pack-args -d 'For internal use only'
complete -c git-http-fetch -l recover -d 'Verify that everything reachable from target is fetched'

