# git-hash-object
# Autogenerated from man page /usr/share/man/man1/git-hash-object.1.gz
complete -c git-hash-object -s t -d 'Specify the type of object to be created (default: "blob")'
complete -c git-hash-object -s w -d 'Actually write the object into the object database'
complete -c git-hash-object -l stdin -d 'Read the object from standard input instead of from a file'
complete -c git-hash-object -l stdin-paths -d 'Read file names from the standard input, one per line, instead of from the co…'
complete -c git-hash-object -l path -d 'Hash object as it were located at the given path'
complete -c git-hash-object -l no-filters -d 'Hash the contents as is, ignoring any input filter that would have been chose…'
complete -c git-hash-object -l literally -d 'Allow --stdin to hash any garbage into a loose object which might not otherwi…'

