# git-show-index
# Autogenerated from man page /usr/share/man/man1/git-show-index.1.gz
complete -c git-show-index -l object-format -d 'Specify the given object format (hash algorithm) for the index file'

