# git-clean
# Autogenerated from man page /usr/share/man/man1/git-clean.1.gz
complete -c git-clean -s d -d 'Normally, when no <pathspec> is specified, git clean will not recurse into un…'
complete -c git-clean -s f -l force -d 'If the Git configuration variable clean'
complete -c git-clean -s i -l interactive -d 'Show what would be done and clean files interactively'
complete -c git-clean -s n -l dry-run -d 'Don\'t actually remove anything, just show what would be done'
complete -c git-clean -s q -l quiet -d 'Be quiet, only report errors, but not the files that are successfully removed'
complete -c git-clean -s e -l exclude -d 'Use the given exclude pattern in addition to the standard ignore rules (see g…'
complete -c git-clean -s x -d 'Don\'t use the standard ignore rules (see gitignore(5)), but still use the ign…'
complete -c git-clean -s X -d 'Remove only files ignored by Git'

