# git-commit-tree
# Autogenerated from man page /usr/share/man/man1/git-commit-tree.1.gz
complete -c git-commit-tree -s p -d 'Each -p indicates the id of a parent commit object'
complete -c git-commit-tree -s m -d 'A paragraph in the commit log message'
complete -c git-commit-tree -s F -d 'Read the commit log message from the given file'
complete -c git-commit-tree -s S -l gpg-sign -l no-gpg-sign -d 'GPG-sign commits'

