# git-pack-redundant
# Autogenerated from man page /usr/share/man/man1/git-pack-redundant.1.gz
complete -c git-pack-redundant -l all -d 'Processes all packs.  Any filenames on the command line are ignored'
complete -c git-pack-redundant -l alt-odb -d 'Don\'t require objects present in packs from alternate object database (odb) d…'
complete -c git-pack-redundant -l verbose -d 'Outputs some statistics to stderr.  Has a small performance penalty'

