# git-stash
# Autogenerated from man page /usr/share/man/man1/git-stash.1.gz
complete -c git-stash -s a -l all -d 'This option is only valid for push and save commands'
complete -c git-stash -s u -l include-untracked -l no-include-untracked -d 'When used with the push and save commands, all untracked files are also stash…'
complete -c git-stash -l only-untracked -d 'This option is only valid for the show command'
complete -c git-stash -l index -d 'This option is only valid for pop and apply commands'
complete -c git-stash -s k -l keep-index -l no-keep-index -d 'This option is only valid for push and save commands'
complete -c git-stash -s p -l patch -d 'This option is only valid for push and save commands'
complete -c git-stash -s S -l staged -d 'This option is only valid for push and save commands'
complete -c git-stash -l pathspec-from-file -d 'This option is only valid for push command'
complete -c git-stash -l pathspec-file-nul -d 'This option is only valid for push command'
complete -c git-stash -s q -l quiet -d 'This option is only valid for apply, drop, pop, push, save, store commands'
complete -c git-stash -l literal-pathspecs
complete -c git-stash -l ---H----I -d 'where H is the HEAD commit, I is a commit that records the state of the index…'

