# git-hook
# Autogenerated from man page /usr/share/man/man1/git-hook.1.gz
complete -c git-hook -l to-stdin -d 'For "run"; Specify a file which will be streamed into the hook\'s stdin'
complete -c git-hook -l ignore-missing -d 'Ignore any missing hook by quietly returning zero'
complete -c git-hook -l end-of-options -d 'gitcli(7)).  See githooks(5) for arguments hooks might expect (if any)'

