# git-range-diff
# Autogenerated from man page /usr/share/man/man1/git-range-diff.1.gz
complete -c git-range-diff -l no-dual-color -d 'When the commit diffs differ, \\(oqgit range-diff` recreates the original diff…'
complete -c git-range-diff -l creation-factor -d 'Set the creation/deletion cost fudge factor to <percent>.  Defaults to 60'
complete -c git-range-diff -l left-only -d 'Suppress commits that are missing from the first specified range (or the "lef…'
complete -c git-range-diff -l right-only -d 'Suppress commits that are missing from the second specified range (or the "ri…'
complete -c git-range-diff -l notes -d 'This flag is passed to the git log program (see git-log(1)) that generates th…'
complete -c git-range-diff -l ----- -d '1:  c0debee = 2:  cab005e Add a helpful message at the start 2:  f00dbal ! 3:…'

