# git-init
# Autogenerated from man page /usr/share/man/man1/git-init.1.gz
complete -c git-init -s q -l quiet -d 'Only print error and warning messages; all other output will be suppressed'
complete -c git-init -l bare -d 'Create a bare repository'
complete -c git-init -l object-format -d 'Specify the given object format (hash algorithm) for the repository'
complete -c git-init -l template -d 'Specify the directory from which templates will be used'
complete -c git-init -l separate-git-dir -d 'Instead of initializing the repository as a directory to either $GIT_DIR or '
complete -c git-init -s b -l initial-branch -d 'Use the specified name for the initial branch in the newly created repository'
complete -c git-init -l shared

