# gitk
# Autogenerated from man page /usr/share/man/man1/gitk.1.gz
complete -c gitk -l all -d 'Show all refs (branches, tags, etc. )'
complete -c gitk -l branches -l tags -l remotes -d 'Pretend as if all the branches (tags, remote branches, resp'
complete -c gitk -l since -d 'Show commits more recent than a specific date'
complete -c gitk -l until -d 'Show commits older than a specific date'
complete -c gitk -l date-order -d 'Sort commits by date when possible'
complete -c gitk -l merge -d 'After an attempt to merge stops with conflicts, show the commits on the histo…'
complete -c gitk -l left-right -d 'Mark which side of a symmetric difference a commit is reachable from'
complete -c gitk -l full-history -d 'When filtering history with <path>. , does not prune some history'
complete -c gitk -l simplify-merges -d 'Additional option to --full-history to remove some needless merges from the r…'
complete -c gitk -l ancestry-path -d 'When given a range of commits to display (e. g.  commit1'
complete -c gitk -o 'L<start>' -o 'L:<funcname>:<file>' -d 'Trace the evolution of the line range given by <start>,<end>, or by the funct…'
complete -c gitk -l argscmd -d 'Command to be run each time gitk has to determine the revision range to show'
complete -c gitk -l select-commit -d 'Select the specified commit after loading the graph'
complete -c gitk -l patch
complete -c gitk -l no-patch
complete -c gitk -l raw
complete -c gitk -l numstat
complete -c gitk -l shortstat
complete -c gitk -l dirstat
complete -c gitk -l summary
complete -c gitk -l name-only
complete -c gitk -l name-status
complete -c gitk -l check
complete -c gitk -s L -d 'range, if any, otherwise from the start of file'

