# glib-mkenums
# Autogenerated from man page /usr/share/man/man1/glib-mkenums.1.gz
complete -c glib-mkenums -l fhead -d 'Emits TEXT prior to processing input files'
complete -c glib-mkenums -l fprod -d 'Emits TEXT every time a new input file is being processed'
complete -c glib-mkenums -l ftail -d 'Emits TEXT after all input files have been processed'
complete -c glib-mkenums -l eprod -d 'Emits TEXT every time an enum is encountered in the input files'
complete -c glib-mkenums -l vhead -d 'Emits TEXT before iterating over the set of values of an enum'
complete -c glib-mkenums -l vprod -d 'Emits TEXT for every value of an enum'
complete -c glib-mkenums -l vtail -d 'Emits TEXT after iterating over all values of an enum'
complete -c glib-mkenums -l comments -d 'Template for auto-generated comments, the default (for C code generations) is…'
complete -c glib-mkenums -l template -d 'Read templates from the given file'
complete -c glib-mkenums -l identifier-prefix -d 'Indicates what portion of the enum name should be interpreted as the prefix (…'
complete -c glib-mkenums -l symbol-prefix -d 'Indicates what prefix should be used to correspond to the identifier prefix i…'
complete -c glib-mkenums -l help -d 'Print brief help and exit'
complete -c glib-mkenums -l version -d 'Print version and exit'
complete -c glib-mkenums -l output -d 'Write output to FILE instead of stdout'

