# glib-gettextize
# Autogenerated from man page /usr/share/man/man1/glib-gettextize.1.gz
complete -c glib-gettextize -l help -d 'print help and exit'
complete -c glib-gettextize -l version -d 'print version information and exit'
complete -c glib-gettextize -s c -l copy -d 'copy files instead of making symlinks'
complete -c glib-gettextize -s f -l force -d 'force writing of new files even if old ones exist'
complete -c glib-gettextize -l no-changelog -d 'option).  OPTIONS'

