# gobject-query
# Autogenerated from man page /usr/share/man/man1/gobject-query.1.gz
complete -c gobject-query -s r -d 'specify the root type'
complete -c gobject-query -s n -d 'don\\*(Aqt descend type tree'
complete -c gobject-query -s b -d 'specify indent string'
complete -c gobject-query -s i -d 'specify incremental indent string'
complete -c gobject-query -s s -d 'specify line spacing'
complete -c gobject-query -s h -l help -d 'Print brief help and exit'
complete -c gobject-query -s v -l version -d 'Print version and exit'

