# gp-collect-app
# Autogenerated from man page /usr/share/man/man1/gp-collect-app.1.gz
complete -c gp-collect-app -l version -d 'X Item "--version" Print the version number and exit'
complete -c gp-collect-app -l help -d 'X Item "--help" Print usage information and exit'
complete -c gp-collect-app -s p -d 'X Item "-p {off|on|lo|hi|<value>}" Disable (off) or enable (on) clock-profili…'
complete -c gp-collect-app -s h -d 'X Item "-h {<ctr_def>'
complete -c gp-collect-app -s o -d 'X Item "-o <exp_name>" Specify the name for the experiment directory'
complete -c gp-collect-app -s O -d 'X Item "-O <exp_name>" This is the same as the -o option, but unlike this opt…'
complete -c gp-collect-app -s C -d 'X Item "-C <comment_string>" Add up to 10 comment strings to the experiment'
complete -c gp-collect-app -s j -d 'X Item "-j {on|off|<path>}" Controls Java profiling when the target is a JVM …'
complete -c gp-collect-app -s J -d 'X Item "-J <jvm-options>" Specifies additional options to be passed to the JV…'
complete -c gp-collect-app -s t -d 'X Item "-t <duration>[m|s]" Collects data for the specified duration'
complete -c gp-collect-app -s n -d 'X Item "-n" This is used for a dry run'
complete -c gp-collect-app -s F -d 'X Item "-F {off|on|=regex}" Control whether descendant processes should have …'
complete -c gp-collect-app -s a -d 'X Item "-a {off|on|ldobjects|src|usedldobjects|usedsrc}" Specify archiving of…'
complete -c gp-collect-app -s S -d 'X Item "-S {off|on|<seconds>}" Disable (off), or enable (on) periodic samplin…'
complete -c gp-collect-app -s y -d 'X Item "-y <signal>[,r]" Controls recording of data with the signal named <si…'
complete -c gp-collect-app -s l -d 'X Item "-l <signal>" Specify a signal that will trigger a sample of process-w…'
complete -c gp-collect-app -s s -d 'X Item "-s <option>[,<API>]" Enable synchronization wait tracing, where <opti…'
complete -c gp-collect-app -s H -d 'X Item "-H {off|on}" Disable (off), or enable (on) heap tracing'
complete -c gp-collect-app -s i

