# gp-display-html
# Autogenerated from man page /usr/share/man/man1/gp-display-html.1.gz
complete -c gp-display-html -l version -d 'X Item "--version" Print the version number and exit'
complete -c gp-display-html -l help -d 'X Item "--help" Print usage information and exit'
complete -c gp-display-html -l verbose -d 'X Item "--verbose {on|off}" Enable (on) or disable (off) verbose mode'
complete -c gp-display-html -l debug -d 'X Item "--debug {on|s|m|l|xl|off}"'
complete -c gp-display-html -s d -d 'X Item "-d {on|s|m|l|xl|off}" '
complete -c gp-display-html -l -highlight-percentage -d 'X Item "---highlight-percentage value"'
complete -c gp-display-html -o hp -d 'X Item "-hp value" '
complete -c gp-display-html -l output -d 'X Item "--output dirname"'
complete -c gp-display-html -s o -d 'X Item "-o dirname" '
complete -c gp-display-html -l overwrite -d 'X Item "--overwrite dirname"'
complete -c gp-display-html -s O -d 'X Item "-O dirname" '
complete -c gp-display-html -l quiet -d 'X Item "--quiet {on|off}"'
complete -c gp-display-html -s q -d 'X Item "-q {on|off}" '
complete -c gp-display-html -l warnings -d 'X Item "--warnings {on|off}"'
complete -c gp-display-html -s w -d 'Enable (on), or disable (off) run time warning messages from the tool'

