# gpg-check-pattern
# Autogenerated from man page /usr/share/man/man1/gpg-check-pattern.1.gz
complete -c gpg-check-pattern -l verbose -d 'Enable extra informational output'
complete -c gpg-check-pattern -l check -d 'Run only a syntax check on the patternfile'
complete -c gpg-check-pattern -l null -d 'Input is expected to be null delimited.  SEE ALSO gpg-agent(1),'

