# gpg-wks-client
# Autogenerated from man page /usr/share/man/man1/gpg-wks-client.1.gz
complete -c gpg-wks-client -l send -d 'Directly send created mails using the sendmail command'
complete -c gpg-wks-client -l with-colons -d 'This option has currently only an effect on the --supported command'
complete -c gpg-wks-client -l output -d 'TQ   -o Write the created mail to file instead of stdout'
complete -c gpg-wks-client -l status-fd -d 'Write special status strings to the file descriptor n'
complete -c gpg-wks-client -s C -d 'TQ   --directory dir Use dir as top level directory for the commands --mirror…'
complete -c gpg-wks-client -l blacklist -d 'This option is used to exclude certain mail addresses from a mirror operation'
complete -c gpg-wks-client -l add-revocs -d 'If enabled append revocation certificates for the same addrspec as used in th…'
complete -c gpg-wks-client -l verbose -d 'Enable extra informational output'
complete -c gpg-wks-client -l quiet -d 'Disable almost all informational output'
complete -c gpg-wks-client -l version -d 'Print version of the program and exit'
complete -c gpg-wks-client -l create
complete -c gpg-wks-client -l remove-key -d 'argument is a user-id'
complete -c gpg-wks-client -s o -d 'Write the created mail to file instead of stdout'
complete -c gpg-wks-client -l directory -d 'Use dir as top level directory for the commands'
complete -c gpg-wks-client -l mirror -l install-key -d 'The default is `openpgpkey\''
complete -c gpg-wks-client -l help -d 'Display a brief help page and exit.  SEE ALSO gpg-wks-server(1)'

