# gpgrt-config
# Autogenerated from man page /usr/share/man/man1/gpgrt-config.1.gz
complete -c gpgrt-config -l libdir -d 'Parent directory path of pkgconfig file search path.  e. g'
complete -c gpgrt-config -l exists -d 'Test whether the pkg-config file \\(oqmodule'
complete -c gpgrt-config -l modversion -d 'Print the currently installed version of module on the standard output'
complete -c gpgrt-config -l libs -d 'Print the linker flags that are necessary to link a program using the module'
complete -c gpgrt-config -l cflags -d 'Print the compiler flags that are necessary to compile a program using the mo…'
complete -c gpgrt-config -l static -d 'Modifies output if linking statically instead of dynamically'
complete -c gpgrt-config -l variable -d 'Output variable VARNAME from the module\'s pkg-config file'

