# groupmod
# Autogenerated from man page /usr/share/man/man8/groupmod.8.gz
complete -c groupmod -s a -l appendGID -d 'If group members are specified with -U, append them to the existing member li…'
complete -c groupmod -s g -l gidGID -d 'The group ID of the given GROUP will be changed to GID'
complete -c groupmod -s h -l help -d 'Display help message and exit'
complete -c groupmod -s n -l new-nameNEW_GROUP -d 'The name of the group will be changed from GROUP to NEW_GROUP name'
complete -c groupmod -s o -l non-unique -d 'When used with the -g option, allow to change the group GID to a non-unique v…'
complete -c groupmod -s p -l passwordPASSWORD -d 'The encrypted password, as returned by crypt(3)'
complete -c groupmod -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c groupmod -s P -l prefixPREFIX_DIR -d 'Apply changes in the PREFIX_DIR directory and use the configuration files fro…'
complete -c groupmod -s U -l users -d 'A list of usernames to add as members of the group'
complete -c groupmod -l append
complete -c groupmod -l gid
complete -c groupmod -l new-name
complete -c groupmod -l password
complete -c groupmod -l root
complete -c groupmod -l prefix
complete -c groupmod -s N

