# grub-sparc64-setup
# Autogenerated from man page /usr/share/man/man8/grub-sparc64-setup.8.gz
complete -c grub-sparc64-setup -s a -l allow-floppy -d 'make the drive also bootable as floppy (default for fdX devices)'
complete -c grub-sparc64-setup -s b -l boot-image -d 'use FILE as the boot image [default=boot. img]'
complete -c grub-sparc64-setup -s c -l core-image -d 'use FILE as the core image [default=core. img]'
complete -c grub-sparc64-setup -s d -l directory -d 'use GRUB files in the directory DIR [default=//boot/grub]'
complete -c grub-sparc64-setup -s f -l force -d 'install even if problems are detected'
complete -c grub-sparc64-setup -s m -l device-map -d 'use FILE as the device map [default=//boot/grub/device. map]'
complete -c grub-sparc64-setup -l no-rs-codes -d 'Do not apply any reed-solomon codes when embedding core. img'
complete -c grub-sparc64-setup -s s -l skip-fs-probe -d 'do not probe for filesystems in DEVICE'
complete -c grub-sparc64-setup -s v -l verbose -d 'print verbose messages'
complete -c grub-sparc64-setup -s '?' -l help -d 'give this help list'
complete -c grub-sparc64-setup -l usage -d 'give a short usage message'
complete -c grub-sparc64-setup -s V -l version -d 'print program version'

