# gtester
# Autogenerated from man page /usr/share/man/man1/gtester.1.gz
complete -c gtester -s h -l help -d 'print help and exit'
complete -c gtester -s v -l version -d 'print version information and exit'
complete -c gtester -l g-fatal-warnings -d 'make warnings fatal'
complete -c gtester -s k -l keep-going -d 'continue running after tests failed'
complete -c gtester -s l -d 'list paths of available test cases'
complete -c gtester -s p -d 'only run test cases matching TESTPATH'
complete -c gtester -s s -d 'skip test cases matching TESTPATH'
complete -c gtester -l seed -d 'run all test cases with random number seed SEEDSTRING'
complete -c gtester -s o -d 'write the test log to LOGFILE'
complete -c gtester -s q -l quiet -d 'suppress per test binary output'
complete -c gtester -l verbose -d 'report success per testcase'
complete -c gtester -s m

