# guile
# Autogenerated from man page /usr/share/man/man1/guile.1.gz
complete -c guile -s L -d 'Add DIRECTORY to the front of Guile\'s module load path'
complete -c guile -s l -d 'Load Scheme source code from FILE'
complete -c guile -s e -d 'After reading SCRIPT, apply FUNCTION to command-line arguments'
complete -c guile -s c -d 'Stop argument processing, and evaluate EXPR as a Scheme expression'
complete -c guile -s s -d 'Load Scheme source from SCRIPT-FILE and execute as a script'
complete -c guile -o ds -d 'Carry out -s SCRIPT at this point in the option sequence'
complete -c guile -l debug -d 'Start  guile with the debugging VM'
complete -c guile -l no-debug -d 'Start  guile without the debugging VM, even if  guile is being run interactiv…'
complete -c guile -l auto-compile -d 'Compile source files automatically (default behavior)'
complete -c guile -l no-auto-compile -d 'Disable automatic source file compilation'
complete -c guile -l listen -d 'Listen on a port or socket for remote REPL connections'
complete -c guile -l use-srfi -d 'Load SRFI extensions N, M, etc.  For example,  --use-srfi=8,13'
complete -c guile -s x -d 'Add EXTENSION to the  guile load extension list'
complete -c guile -s h -l help -d 'Describe command-line options and exit'
complete -c guile -s v -l version -d 'Display guile version and exit'
complete -c guile -s q -d 'In interactive mode, suppress loading the user\'s initialization file, ~/'

