# h2ph.1perl
# Autogenerated from man page /usr/share/man/man1/h2ph.1perl.gz
complete -c 'h2ph.1perl' -s d -d 'X Item "-d destination_dir" Put the resulting '
complete -c 'h2ph.1perl' -s r -d 'X Item "-r" Run recursively; if any of headerfiles are directories, then run …'
complete -c 'h2ph.1perl' -s a -d 'X Item "-a" Run automagically; convert headerfiles, as well as any '
complete -c 'h2ph.1perl' -s l -d 'X Item "-l" Symbolic links will be replicated in the destination directory'
complete -c 'h2ph.1perl' -s h -d 'X Item "-h" Put \'hints\' in the '
complete -c 'h2ph.1perl' -s e -d 'X Item "-e" If an error is encountered during conversion, output file will be…'
complete -c 'h2ph.1perl' -s D -d 'X Item "-D" Include the code from the . h file as a comment in the . ph file'
complete -c 'h2ph.1perl' -s Q

