# hardlink
# Autogenerated from man page /usr/share/man/man1/hardlink.1.gz
complete -c hardlink -s h -l help
complete -c hardlink -s V -l version
complete -c hardlink -s c -l content
complete -c hardlink -s b -l io-size
complete -c hardlink -s d -l respect-dir
complete -c hardlink -s f -l respect-name
complete -c hardlink -s i -l include
complete -c hardlink -s m -l maximize
complete -c hardlink -s M -l minimize
complete -c hardlink -s n -l dry-run
complete -c hardlink -s o -l ignore-owner
complete -c hardlink -s O -l keep-oldest
complete -c hardlink -s p -l ignore-mode
complete -c hardlink -s q -l quiet
complete -c hardlink -s r -l cache-size
complete -c hardlink -s s -l minimum-size
complete -c hardlink -s S -l maximum-size
complete -c hardlink -s t -l ignore-time
complete -c hardlink -s v -l verbose
complete -c hardlink -s x -l exclude
complete -c hardlink -s X -l respect-xattrs
complete -c hardlink -s y -l method
complete -c hardlink -l reflink
complete -c hardlink -l skip-reflinks

