# icupkg
# Autogenerated from man page /usr/share/man/man8/icupkg.8.gz
complete -c icupkg -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c icupkg -o tl -l type -d 'Output for little-endian/ASCII charset family'
complete -c icupkg -o tb -d 'Output for big-endian/ASCII charset family'
complete -c icupkg -o te -d 'Output for big-endian/EBCDIC charset family'
complete -c icupkg -s c -l copyright -d 'Include the ICU copyright notice in the resulting data'
complete -c icupkg -s C -l comment -d 'Include the specified  comment in the resulting data instead of the ICU copyr…'
complete -c icupkg -s a -l add -d 'Add items from the  list to the package'
complete -c icupkg -s r -l remove -d 'Remove items from the  list from the package'
complete -c icupkg -s x -l extract -d 'Extract items from the  list from the package'
complete -c icupkg -s m -l matchmode -d 'Set the matching mode for item names with wildcards'
complete -c icupkg -s s -l sourcedir -d 'Set the source directory to R source '
complete -c icupkg -s d -l destdir -d 'Set the destination directory to R destination '
complete -c icupkg -s w -l writepkg -d 'option is set'
complete -c icupkg -s t -d option
complete -c icupkg -s l -l list -d 'List the package items to stdout (after modifying the package)'

