# idevicediagnostics
# Autogenerated from man page /usr/share/man/man1/idevicediagnostics.1.gz
complete -c idevicediagnostics -s u -l udid -d 'target specific device by UDID'
complete -c idevicediagnostics -s n -l network -d 'connect to network device'
complete -c idevicediagnostics -s d -l debug -d 'enable communication debugging'
complete -c idevicediagnostics -s h -l help -d 'prints usage information'
complete -c idevicediagnostics -s v -l version -d 'prints version information'

