# idevicedate
# Autogenerated from man page /usr/share/man/man1/idevicedate.1.gz
complete -c idevicedate -s u -l udid -d 'target specific device by UDID'
complete -c idevicedate -s n -l network -d 'connect to network device'
complete -c idevicedate -s d -l debug -d 'enable communication debugging'
complete -c idevicedate -s s -l set -d 'set UTC time described by TIMESTAMP'
complete -c idevicedate -s c -l sync -d 'set time of device to current system time'
complete -c idevicedate -s h -l help -d 'prints usage information'
complete -c idevicedate -s v -l version -d 'prints version information'

