# idevicesyslog
# Autogenerated from man page /usr/share/man/man1/idevicesyslog.1.gz
complete -c idevicesyslog -s u -l udid -d 'target specific device by UDID'
complete -c idevicesyslog -s n -l network -d 'connect to network device'
complete -c idevicesyslog -s x -l exit -d 'exit when device disconnects'
complete -c idevicesyslog -s d -l debug -d 'enable communication debugging'
complete -c idevicesyslog -s h -l help -d 'prints usage information'
complete -c idevicesyslog -s v -l version -d 'prints version information'
complete -c idevicesyslog -l no-colors -d 'disable colored output'
complete -c idevicesyslog -s m -l match -d 'only print messages that contain STRING'
complete -c idevicesyslog -s t -l trigger -d 'start logging when matching STRING'
complete -c idevicesyslog -s T -l untrigger
complete -c idevicesyslog -s p -l process -d 'only print messages from matching process(es)'
complete -c idevicesyslog -s e -l exclude -d 'print all messages except matching process(es)'
complete -c idevicesyslog -s q -l quiet -d 'set a filter to exclude common noisy processes'
complete -c idevicesyslog -l quiet-list -d 'prints the list of processes for --quiet and exits'
complete -c idevicesyslog -s k -l kernel -d 'only print kernel messages'
complete -c idevicesyslog -s K -l no-kernel -d 'suppress kernel messages'

