# idevicenotificationproxy
# Autogenerated from man page /usr/share/man/man1/idevicenotificationproxy.1.gz
complete -c idevicenotificationproxy -s u -l udid -d 'target specific device by UDID'
complete -c idevicenotificationproxy -s n -l network -d 'connect to network device'
complete -c idevicenotificationproxy -s d -l debug -d 'enable communication debugging'
complete -c idevicenotificationproxy -s h -l help -d 'prints usage information'
complete -c idevicenotificationproxy -s v -l version -d 'prints version information'

