# idevicedebug
# Autogenerated from man page /usr/share/man/man1/idevicedebug.1.gz
complete -c idevicedebug -s u -l udid -d 'target specific device by UDID'
complete -c idevicedebug -s n -l network -d 'connect to network device'
complete -c idevicedebug -s e -l env -d 'set environment variable NAME to VALUE'
complete -c idevicedebug -s d -l debug -d 'enable communication debugging'
complete -c idevicedebug -s h -l help -d 'prints usage information'
complete -c idevicedebug -s v -l version -d 'prints version information'

