# idevicescreenshot
# Autogenerated from man page /usr/share/man/man1/idevicescreenshot.1.gz
complete -c idevicescreenshot -s u -l udid -d 'target specific device by UDID'
complete -c idevicescreenshot -s n -l network -d 'connect to network device'
complete -c idevicescreenshot -s d -l debug -d 'enable communication debugging'
complete -c idevicescreenshot -s h -l help -d 'prints usage information'
complete -c idevicescreenshot -s v -l version -d 'prints version information'

