# idevicename
# Autogenerated from man page /usr/share/man/man1/idevicename.1.gz
complete -c idevicename -s u -l udid -d 'target specific device by UDID'
complete -c idevicename -s n -l network -d 'connect to network device'
complete -c idevicename -s d -l debug -d 'enable communication debugging'
complete -c idevicename -s h -l help -d 'prints usage information'
complete -c idevicename -s v -l version -d 'prints version information'

