# idevicebackup2
# Autogenerated from man page /usr/share/man/man1/idevicebackup2.1.gz
complete -c idevicebackup2 -s u -l udid -d 'target specific device by UDID'
complete -c idevicebackup2 -s s -l source -d 'use backup data from device specified by UDID'
complete -c idevicebackup2 -s i -l interactive -d 'request passwords interactively on the command line'
complete -c idevicebackup2 -s n -l network -d 'connect to network device'
complete -c idevicebackup2 -s d -l debug -d 'enable communication debugging'
complete -c idevicebackup2 -s h -l help -d 'prints usage information'
complete -c idevicebackup2 -s v -l version -d 'prints version information'

