# idevicesetlocation
# Autogenerated from man page /usr/share/man/man1/idevicesetlocation.1.gz
complete -c idevicesetlocation -s u -l udid -d 'target specific device by UDID'
complete -c idevicesetlocation -s n -l network -d 'connect to network device'
complete -c idevicesetlocation -s d -l debug -d 'enable communication debugging'
complete -c idevicesetlocation -s h -l help -d 'prints usage information'
complete -c idevicesetlocation -s v -l version -d 'prints version information'

