# idevicedebugserverproxy
# Autogenerated from man page /usr/share/man/man1/idevicedebugserverproxy.1.gz
complete -c idevicedebugserverproxy -s u -l udid -d 'target specific device by UDID'
complete -c idevicedebugserverproxy -s n -l network -d 'connect to network device'
complete -c idevicedebugserverproxy -s d -l debug -d 'enable communication debugging'
complete -c idevicedebugserverproxy -s h -l help -d 'prints usage information'
complete -c idevicedebugserverproxy -s v -l version -d 'prints version information'

