# ideviceprovision
# Autogenerated from man page /usr/share/man/man1/ideviceprovision.1.gz
complete -c ideviceprovision -s u -l udid -d 'target specific device by UDID'
complete -c ideviceprovision -s n -l network -d 'connect to network device'
complete -c ideviceprovision -s x -l xml -d 'print XML output when using the \'dump\' command'
complete -c ideviceprovision -s d -l debug -d 'enable communication debugging'
complete -c ideviceprovision -s h -l help -d 'prints usage information'
complete -c ideviceprovision -s v -l version -d 'prints version information'

