# idevice_id
# Autogenerated from man page /usr/share/man/man1/idevice_id.1.gz
complete -c idevice_id -s l -l list -d 'List UDIDs of all devices attached via USB'
complete -c idevice_id -s n -l network -d 'List UDIDs of all devices available via network'
complete -c idevice_id -s d -l debug -d 'Enable communication debugging'
complete -c idevice_id -s h -l help -d 'Prints usage information'
complete -c idevice_id -s v -l version -d 'Prints version information'

