# idevicecrashreport
# Autogenerated from man page /usr/share/man/man1/idevicecrashreport.1.gz
complete -c idevicecrashreport -s u -l udid -d 'target specific device by UDID'
complete -c idevicecrashreport -s n -l network -d 'connect to network device'
complete -c idevicecrashreport -s e -l extract -d 'extract raw crash report into separate \'. crash\' files'
complete -c idevicecrashreport -s k -l keep -d 'copy but do not remove crash reports from device'
complete -c idevicecrashreport -s d -l debug -d 'enable communication debugging'
complete -c idevicecrashreport -s h -l help -d 'prints usage information'
complete -c idevicecrashreport -s v -l version -d 'prints version information'

