# ideviceinfo
# Autogenerated from man page /usr/share/man/man1/ideviceinfo.1.gz
complete -c ideviceinfo -s s -l simple -d 'use a simple connection to avoid auto-pairing with the device'
complete -c ideviceinfo -s u -l udid -d 'target specific device by UDID'
complete -c ideviceinfo -s n -l network -d 'connect to network device'
complete -c ideviceinfo -s d -l debug -d 'enable communication debugging'
complete -c ideviceinfo -s q -l domain -d 'set domain of query to NAME.  Default: None'
complete -c ideviceinfo -s k -l key -d 'only query key specified by NAME.  Default: All keys'
complete -c ideviceinfo -s x -l xml -d 'output information as xml plist instead of key/value pairs'
complete -c ideviceinfo -s h -l help -d 'prints usage information'
complete -c ideviceinfo -s v -l version -d 'prints version information'

