# idevicebackup
# Autogenerated from man page /usr/share/man/man1/idevicebackup.1.gz
complete -c idevicebackup -s u -l udid -d 'target specific device by UDID'
complete -c idevicebackup -s n -l network -d 'connect to network device'
complete -c idevicebackup -s d -l debug -d 'enable communication debugging'
complete -c idevicebackup -s h -l help -d 'prints usage information'
complete -c idevicebackup -s v -l version -d 'prints version information'

