# ideviceimagemounter
# Autogenerated from man page /usr/share/man/man1/ideviceimagemounter.1.gz
complete -c ideviceimagemounter -s u -l udid -d 'target specific device by UDID'
complete -c ideviceimagemounter -s n -l network -d 'connect to network device'
complete -c ideviceimagemounter -s d -l debug -d 'enable communication debugging'
complete -c ideviceimagemounter -s l -l list -d 'list mount information'
complete -c ideviceimagemounter -s t -l imagetype -d 'the image type to use, default is \'Developer\''
complete -c ideviceimagemounter -s x -l xml -d 'use XML output'
complete -c ideviceimagemounter -s h -l help -d 'prints usage information'
complete -c ideviceimagemounter -s v -l version -d 'prints version information'

