# idn2
# Autogenerated from man page /usr/share/man/man1/idn2.1.gz
complete -c idn2 -s h -l help -d 'Print help and exit'
complete -c idn2 -s V -l version -d 'Print version and exit'
complete -c idn2 -s d -l decode -d 'Decode (punycode) domain name'
complete -c idn2 -s l -l lookup -d 'Lookup domain name (default)'
complete -c idn2 -s r -l register -d 'Register label'
complete -c idn2 -s T -l tr46t -d 'Enable TR46 transitional processing'
complete -c idn2 -s N -l tr46nt -d 'Enable TR46 non-transitional processing'
complete -c idn2 -l no-tr46 -d 'Disable TR46 processing'
complete -c idn2 -l usestd3asciirules -d 'Enable STD3 ASCII rules'
complete -c idn2 -l no-alabelroundtrip -d 'Disable A-label roundtrip for lookups'
complete -c idn2 -l debug -d 'Print debugging information'
complete -c idn2 -l quiet -d 'Silent operation AUTHOR Written by Simon Josefsson, Tim Ruehsen'

