# ifnames
# Autogenerated from man page /usr/share/man/man1/ifnames.1.gz
complete -c ifnames -s h -l help -d 'print this help, then exit'
complete -c ifnames -s V -l version -d 'print version number, then exit AUTHOR Written by David J'

