# ifstat
# Autogenerated from man page /usr/share/man/man8/ifstat.8.gz
complete -c ifstat -s h -l help -d 'Show summary of options'
complete -c ifstat -s V -l version -d 'Show version of program'
complete -c ifstat -s a -l ignore -d 'Ignore the history file'
complete -c ifstat -s d -l scan -d 'Sample statistics every SECS second'
complete -c ifstat -s e -l errors -d 'Show errors'
complete -c ifstat -s n -l nooutput -d 'Don\'t display any output.   Update the history file only'
complete -c ifstat -s r -l reset -d 'Reset history'
complete -c ifstat -s s -l noupdate -d 'Don\'t update the history file'
complete -c ifstat -s t -l interval -d 'Report average over the last SECS seconds'
complete -c ifstat -s z -l zeros -d 'Show entries with zero activity'
complete -c ifstat -s j -l json -d 'Display results in JSON format'
complete -c ifstat -s p -l pretty -d 'If combined with  --json , pretty print the output'
complete -c ifstat -s x -l extended -d 'Show extended stats of TYPE.  Supported types are: cpu_hits'

