# img2webp
# Autogenerated from man page /usr/share/man/man1/img2webp.1.gz
complete -c img2webp -s o -d 'Specify the name of the output WebP file'
complete -c img2webp -o min_size -d 'Encode images to achieve smallest size'
complete -c img2webp -o mixed
complete -c img2webp -o kmin
complete -c img2webp -o kmax -d 'Specify the minimum and maximum distance between consecutive key frames (inde…'
complete -c img2webp -o near_lossless -d 'Specify the level of near-lossless image preprocessing'
complete -c img2webp -o sharp_yuv -d 'Use more accurate and sharper RGB->YUV conversion if needed'
complete -c img2webp -o loop -d 'Specifies the number of times the animation should loop'
complete -c img2webp -s v -d 'Be more verbose'
complete -c img2webp -s h -o help -d 'A short usage summary'
complete -c img2webp -o version -d 'Print the version numbers of the relevant libraries used'
complete -c img2webp -s d -d 'Specify the image duration in milliseconds'
complete -c img2webp -o lossless -o lossy -d 'Compress the next image(s) using lossless or lossy compression mode'
complete -c img2webp -s q -d 'Specify the compression factor between 0 and 100.  The default is 75'
complete -c img2webp -s m -d 'Specify the compression method to use'

