# inetcat
# Autogenerated from man page /usr/share/man/man1/inetcat.1.gz
complete -c inetcat -s u -l udid -d 'Target specific device by UDID'
complete -c inetcat -s n -l network -d 'Connect to network device'
complete -c inetcat -s l -l local -d 'Connect to USB device.  This is the default if no option is passed'
complete -c inetcat -s h -l help -d 'Prints usage information'
complete -c inetcat -s d -l debug -d 'Increase debug level'

