# integritysetup
# Autogenerated from man page /usr/share/man/man8/integritysetup.8.gz
complete -c integritysetup -l journal-size -l interleave-sectors -l tag-size -l integrity
complete -c integritysetup -l integrity-key-size -l integrity-key-file -l sector-size
complete -c integritysetup -l progress-frequency -l progress-json -d OPEN
complete -c integritysetup -l journal-commit-time -l buffer-sectors
complete -c integritysetup -l integrity-no-journal
complete -c integritysetup -l integrity-recalculate
complete -c integritysetup -l integrity-recalculate-reset -l integrity-recovery-mode
complete -c integritysetup -l allow-discards -d CLOSE
complete -c integritysetup -l no-wipe
complete -c integritysetup -l wipe
complete -c integritysetup -s j
complete -c integritysetup -l journal-watermark
complete -c integritysetup -s t
complete -c integritysetup -l data-device
complete -c integritysetup -s s
complete -c integritysetup -s I
complete -c integritysetup -s D
complete -c integritysetup -l integrity-bitmap-mode -s B
complete -c integritysetup -l bitmap-sectors-per-bit
complete -c integritysetup -l bitmap-flush-time
complete -c integritysetup -s R
complete -c integritysetup -l journal-integrity
complete -c integritysetup -l journal-integrity-key-size
complete -c integritysetup -l journal-integrity-key-file
complete -c integritysetup -l journal-crypt
complete -c integritysetup -l journal-crypt-key-size
complete -c integritysetup -l journal-crypt-key-file
complete -c integritysetup -l deferred
complete -c integritysetup -l cancel-deferred
complete -c integritysetup -l verbose -s v
complete -c integritysetup -l debug
complete -c integritysetup -l version -s V
complete -c integritysetup -l batch-mode -s q
complete -c integritysetup -l usage
complete -c integritysetup -l help -s '?'
complete -c integritysetup -l integrity-legacy-padding
complete -c integritysetup -l integrity-legacy-hmac
complete -c integritysetup -l integrity-legacy-recalculate

