# iproxy
# Autogenerated from man page /usr/share/man/man1/iproxy.1.gz
complete -c iproxy -s u -l udid -d 'Target specific device by UDID'
complete -c iproxy -s n -l network -d 'Connect to network device'
complete -c iproxy -s l -l local -d 'Connect to USB device.  This is the default if no option is passed'
complete -c iproxy -s s -l source -d 'Allows setting a source address for the listening socket.  The default is 127'
complete -c iproxy -s h -l help -d 'Prints usage information'
complete -c iproxy -s d -l debug -d 'Increase debug level.  EXAMPLES'

