# ir-keytable
# Autogenerated from man page /usr/share/man/man1/ir-keytable.1.gz
complete -c ir-keytable -s a -l auto-load -d 'Auto-load keymaps, based on a configuration file.  Only works with --sysdev'
complete -c ir-keytable -s c -l clear -d 'Clears the scancode to keycode mappings'
complete -c ir-keytable -s D -l delay -d 'Sets the delay before repeating a keystroke'
complete -c ir-keytable -s k -l set-key -d 'Set scancode to keycode mapping'
complete -c ir-keytable -s p -l protocol -d 'Comma separated list of kernel protocols or BPF protocol to enable'
complete -c ir-keytable -s e -l parameter -d 'Comma separated list of parameters for the BPF protocol'
complete -c ir-keytable -s P -l 'period\\' -d 'Sets the period to repeat a keystroke'
complete -c ir-keytable -s r -l read -d 'Read and show the current scancode to keycode mapping'
complete -c ir-keytable -s s -l sysdev -d 'rc device to control, defaults to rc0 if not specified'
complete -c ir-keytable -s t -l test -d 'test if the rc device is generating events'
complete -c ir-keytable -s v -l verbose -d 'Enables debug messages'
complete -c ir-keytable -s w -l write -d 'Reads the protocols and scancode to keycode mapping from the KEYMAP file, and…'
complete -c ir-keytable -s '?' -l help -d 'Prints the help message'
complete -c ir-keytable -l usage -d 'Give a short usage message'
complete -c ir-keytable -s V -l version -d 'print the v4l2-utils version '
complete -c ir-keytable -l period -d 'Sets the period to repeat a keystroke'

