# json_pp.1perl
# Autogenerated from man page /usr/share/man/man1/json_pp.1perl.gz
complete -c 'json_pp.1perl' -s f -d '    -f from_format Reads a data in the given format from STDIN'
complete -c 'json_pp.1perl' -s t
complete -c 'json_pp.1perl' -o json_opt
complete -c 'json_pp.1perl' -s v
complete -c 'json_pp.1perl' -s V

