# kbdinfo
# Autogenerated from man page /usr/share/man/man1/kbdinfo.1.gz
complete -c kbdinfo -s C -l console -d 'the console device to be used;'
complete -c kbdinfo -s V -l version -d 'print version number;'
complete -c kbdinfo -s h -l help -d 'print this usage message.  AUTHORS Written by Alexey Gladkov'

