# kdestroy
# Autogenerated from man page /usr/share/man/man1/kdestroy.1.gz
complete -c kdestroy -s A -d 'Destroys all caches in the collection, if a cache collection is available'
complete -c kdestroy -s q -d 'Run quietly'
complete -c kdestroy -s c -d 'Use cache_name as the credentials (ticket) cache name and location; if this o…'
complete -c kdestroy -s p -d 'If a cache collection is available, destroy the cache for princ_name instead …'

