# kernel-install
# Autogenerated from man page /usr/share/man/man8/kernel-install.8.gz
complete -c kernel-install -l esp-path -d 'Path to the EFI System Partition (ESP)'
complete -c kernel-install -l boot-path -d 'Path to the Extended Boot Loader partition, as defined in the \\m[blue]Boot Lo…'
complete -c kernel-install -l make-entry-directory -d 'Controls creation and deletion of the \\m[blue]Boot Loader Specification\\m[]\\s…'
complete -c kernel-install -l entry-token -d 'Controls how to name and identify boot loader entries for this kernel install…'
complete -c kernel-install -s v -l verbose -d 'Output additional information about operations being performed'
complete -c kernel-install -s h -l help -d 'Print a short help text and exit'
complete -c kernel-install -l version -d 'Print a short version string and exit'

