# kpropd
# Autogenerated from man page /usr/share/man/man8/kpropd.8.gz
complete -c kpropd -s r -d 'Specifies the realm of the primary server'
complete -c kpropd -s A -d 'Specifies the server to be contacted for incremental updates; by default, the…'
complete -c kpropd -s f -d 'Specifies the filename where the dumped principal database file is to be stor…'
complete -c kpropd -s F -d 'Path to the Kerberos database file, if not the default'
complete -c kpropd -s p -d 'Allows the user to specify the pathname to the kdb5_util(8) program; by defau…'
complete -c kpropd -s D -d 'In this mode, kpropd will not detach itself from the current job and run in t…'
complete -c kpropd -s d -d 'Turn on debug mode'
complete -c kpropd -s P -d 'Allow for an alternate port number for kpropd to listen on'
complete -c kpropd -s a -d 'Allows the user to specify the path to the kpropd'
complete -c kpropd -l pid-file -d 'In standalone mode, write the process ID of the daemon into pid_file'
complete -c kpropd -s s -d 'Path to a keytab to use for acquiring acceptor credentials'
complete -c kpropd -s x -d 'Database-specific arguments'

