# krb5-config
# Autogenerated from man page /usr/share/man/man1/krb5-config.1.gz
complete -c krb5-config -l help -d 'prints a usage message'
complete -c krb5-config -l all -d 'prints the version, vendor, prefix, and exec-prefix'
complete -c krb5-config -l version -d 'prints the version number of the Kerberos installation'
complete -c krb5-config -l vendor -d 'prints the name of the vendor of the Kerberos installation'
complete -c krb5-config -l prefix -d 'prints the prefix for which the Kerberos installation was built'
complete -c krb5-config -l exec-prefix -d 'prints the prefix for executables for which the Kerberos installation was bui…'
complete -c krb5-config -l defccname -d 'prints the built-in default credentials cache location'
complete -c krb5-config -l defktname -d 'prints the built-in default keytab location'
complete -c krb5-config -l defcktname -d 'prints the built-in default client (initiator) keytab location'
complete -c krb5-config -l cflags -d 'prints the compilation flags used to build the Kerberos installation'
complete -c krb5-config -l libs -d 'prints the compiler options needed to link against library'
complete -c krb5-config -o L/opt/krb5/lib -o Wl -o rpath -o Wl -o L/usr/local/lib -o lkrb5 -o lk5crypto -o lcom_err -d 'SEE ALSO'

