# ksu
# Autogenerated from man page /usr/share/man/man1/ksu.1.gz
complete -c ksu -s n -d 'Specify a Kerberos target principal name'
complete -c ksu -s k -d 'Do not delete the target cache upon termination of the target shell or a comm…'
complete -c ksu -s z -d 'Restrict the copy of tickets from the source cache to the target cache to onl…'
complete -c ksu -s Z -d 'Don\\(aqt copy any tickets from the source cache to the target cache'
complete -c ksu -s q -d 'Suppress the printing of status messages'
complete -c ksu -s l -s r -s p -s P -s f -s F -d 'The ticket granting ticket options only apply to the case where there are no …'
complete -c ksu -s e -d 'ksu proceeds exactly the same as if it was invoked without the -e option, exc…'
complete -c ksu -s a -d 'Specify arguments to be passed to the target shell'
complete -c ksu -s c -d 'Specify source cache name (e. g. , -c FILE:/tmp/my_cache).   If'

