# kvno
# Autogenerated from man page /usr/share/man/man1/kvno.1.gz
complete -c kvno -s c -d 'Specifies the name of a credentials cache to use (if not the default)'
complete -c kvno -s e -d 'Specifies the enctype which will be requested for the session key of all the …'
complete -c kvno -s k -d 'Decrypt the acquired tickets using keytab to confirm their validity'
complete -c kvno -s q -d 'Suppress printing output when successful'
complete -c kvno -s u -d 'Use the unknown name type in requested service principal names'
complete -c kvno -s P -d 'Specifies that the service1 service2 '
complete -c kvno -s S -d 'Specifies that the service1 service2 '
complete -c kvno -s I -d 'Specifies that protocol transition (S4U2Self) is to be used to acquire a tick…'
complete -c kvno -s U -d 'Same as -I, but treats for_user as an enterprise name'
complete -c kvno -s F -d 'Specifies that protocol transition is to be used, identifying the client prin…'
complete -c kvno -l cached-only -d 'Only retrieve credentials already present in the cache, not from the KDC'
complete -c kvno -l no-store -d 'Do not store retrieved credentials in the cache'
complete -c kvno -l out-cache -d 'Initialize ccache and store all retrieved credentials into it'
complete -c kvno -l u2u -d 'Requests a user-to-user ticket'

