# libevdev-tweak-device
# Autogenerated from man page /usr/share/man/man1/libevdev-tweak-device.1.gz
complete -c libevdev-tweak-device -l abs -d 'Change the given named ABS_ kernel axis, e. g.  ABS_X'
complete -c libevdev-tweak-device -l min -d 'Set the absinfo minimum to the value v'
complete -c libevdev-tweak-device -l max -d 'Set the absinfo maximum to the value v'
complete -c libevdev-tweak-device -l res -d 'Set the absinfo resolution to the value v'
complete -c libevdev-tweak-device -l fuzz -d 'Set the absinfo fuzz to the value v'
complete -c libevdev-tweak-device -l flat -d 'Set the absinfo flat to the value v . PP . SS Changing the x/y resolution'
complete -c libevdev-tweak-device -l resolution -d 'Changes the resolution of the ABS_X, ABS_MT_POSITION_X, ABS_Y, and ABS_MT_POS…'
complete -c libevdev-tweak-device -l led -d 'Change the given LED, e. g.  LED_NUML.  For a full list, see linux/input. h'
complete -c libevdev-tweak-device -l on -d 'Change the LED state to on'
complete -c libevdev-tweak-device -l off -d 'Change the LED state to off NOTES'

