# libinput-measure-touchpad-pressure
# Autogenerated from man page /usr/share/man/man1/libinput-measure-touchpad-pressure.1.gz
complete -c libinput-measure-touchpad-pressure -l help -d 'Print help'
complete -c libinput-measure-touchpad-pressure -l touch-thresholds -d 'Set the logical touch pressure thresholds to  down and  up, respectively'
complete -c libinput-measure-touchpad-pressure -l palm-threshold -d 'Assume a palm threshold of  N'
complete -c libinput-measure-touchpad-pressure -l thumb-threshold -d 'Assume a thumb threshold of N'

