# libinput
# Autogenerated from man page /usr/share/man/man1/libinput.1.gz
complete -c libinput -l help -d 'Print help and exit'
complete -c libinput -l version -d 'Print the version and exit COMMANDS'

