# libinput-quirks-list
# Autogenerated from man page /usr/share/man/man1/libinput-quirks-list.1.gz
complete -c libinput-quirks-list -l data-dir -d 'Use the given directory as data directory for quirks files'
complete -c libinput-quirks-list -l help -d 'Print help'
complete -c libinput-quirks-list -l verbose -d 'Use verbose output, useful for debugging'

