# libinput-analyze-per-slot-delta
# Autogenerated from man page /usr/share/man/man1/libinput-analyze-per-slot-delta.1.gz
complete -c libinput-analyze-per-slot-delta -l help -d 'Print help'
complete -c libinput-analyze-per-slot-delta -l ignore-below -d 'Ignore any movement below the given threshold'
complete -c libinput-analyze-per-slot-delta -l threshold -d 'Color any movement above this threshold in red'
complete -c libinput-analyze-per-slot-delta -l use-mm -d 'Print data in mm instead of device units'
complete -c libinput-analyze-per-slot-delta -l use-st -d 'Use the single-touch ABS_X/ABS_Y instead of the multitouch axes'
complete -c libinput-analyze-per-slot-delta -l use-absolute -d 'Print absolute coordinates, not deltas OUTPUT An example output for a single …'
complete -c libinput-analyze-per-slot-delta -l ---- -d 'indicates the finger has lifted'

