# libinput-test-suite
# Autogenerated from man page /usr/share/man/man1/libinput-test-suite.1.gz
complete -c libinput-test-suite -l filter-test -d 'A glob limiting the tests to run'
complete -c libinput-test-suite -l filter-device -d 'A glob limiting the devices to run tests for'
complete -c libinput-test-suite -l filter-group -d 'A glob limiting the tests to (arbitrarily named) groups'
complete -c libinput-test-suite -l filter-deviceless -d 'FOR INTERNAL USE ONLY'
complete -c libinput-test-suite -s h -l help -d 'Print help'
complete -c libinput-test-suite -s j -l jobs -d 'Number of parallel processes to run.  Default: 8'
complete -c libinput-test-suite -l list -d 'List all test cases and the devices they are run for'
complete -c libinput-test-suite -l verbose -d 'Enable verbose output, including libinput debug messages'

