# libinput-measure-touch-size
# Autogenerated from man page /usr/share/man/man1/libinput-measure-touch-size.1.gz
complete -c libinput-measure-touch-size -l help -d 'Print help'
complete -c libinput-measure-touch-size -l touch-thresholds -d 'Set the logical touch size thresholds to  down and  up, respectively'
complete -c libinput-measure-touch-size -l palm-threshold -d 'Assume a palm threshold of N'

