# libinput-replay
# Autogenerated from man page /usr/share/man/man1/libinput-replay.1.gz
complete -c libinput-replay -l help -d 'Print help'
complete -c libinput-replay -l once -d 'Only replay the recording once, then exit'
complete -c libinput-replay -l replay-after -d 'Replay the recording after waiting for s seconds'

