# libinput-measure-touchpad-tap
# Autogenerated from man page /usr/share/man/man1/libinput-measure-touchpad-tap.1.gz
complete -c libinput-measure-touchpad-tap -l help -d 'Print help'
complete -c libinput-measure-touchpad-tap -l format -d 'Specify the data format to be printed.  The default (or if'

