# libinput-analyze-touch-down-state
# Autogenerated from man page /usr/share/man/man1/libinput-analyze-touch-down-state.1.gz
complete -c libinput-analyze-touch-down-state -l help -d 'Print help'
complete -c libinput-analyze-touch-down-state -l use-st -d 'Use the single-touch BTN_TOOL_ bits instead of the slot state'

