# libinput-debug-gui
# Autogenerated from man page /usr/share/man/man1/libinput-debug-gui.1.gz
complete -c libinput-debug-gui -l device -d 'Use the given device with the path backend'
complete -c libinput-debug-gui -l grab -d 'Exclusively grab all opened devices'
complete -c libinput-debug-gui -l help -d 'Print help'
complete -c libinput-debug-gui -l udev -d 'Use the udev backend to listen for device notifications on the given seat'
complete -c libinput-debug-gui -l verbose -d 'Use verbose output'

