# libtool
# Autogenerated from man page /usr/share/man/man1/libtool.1.gz
complete -c libtool -l config -d 'show all configuration variables'
complete -c libtool -l debug -d 'enable verbose shell tracing'
complete -c libtool -s n -l dry-run -d 'display commands without modifying any files'
complete -c libtool -l features -d 'display basic configuration information and exit'
complete -c libtool -l mode -d 'use operation mode MODE'
complete -c libtool -l no-warnings -d 'equivalent to \'-Wnone\''
complete -c libtool -l preserve-dup-deps -d 'don\'t remove duplicate dependency libraries'
complete -c libtool -l quiet -l silent -d 'don\'t print informational messages'
complete -c libtool -l tag -d 'use configuration variables from tag TAG'
complete -c libtool -s v -l verbose -d 'print more informational messages than default'
complete -c libtool -l version -d 'print version information'
complete -c libtool -s W -l warnings -d 'report the warnings falling in CATEGORY [all]'
complete -c libtool -s h -l help -l help-all -d 'print short, long, or detailed help message '
complete -c libtool -o march -o mtune -o O2 -o pipe -o fno-plt -o fexceptions -d '-Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=\\,format-security\\/         -fstack-…'
complete -c libtool -o Wp -o D_FORTIFY_SOURCE -o Wformat -o Werror -o fstack-clash-protection -o fcf-protection -s g -o ffile-prefix-map -o flto

