# libtoolize
# Autogenerated from man page /usr/share/man/man1/libtoolize.1.gz
complete -c libtoolize -s c -l copy -d 'copy files rather than symlinking them'
complete -c libtoolize -l debug -d 'enable verbose shell tracing'
complete -c libtoolize -s n -l dry-run -d 'print commands rather than running them'
complete -c libtoolize -s f -l force -d 'replace existing files'
complete -c libtoolize -s i -l install -d 'copy missing auxiliary files'
complete -c libtoolize -l ltdl -d 'install libltdl sources [default: libltdl]'
complete -c libtoolize -l no-warnings -d 'equivalent to \'-Wnone\''
complete -c libtoolize -l nonrecursive -d 'prepare ltdl for non-recursive make'
complete -c libtoolize -s q -l quiet -d 'work silently'
complete -c libtoolize -l recursive -d 'prepare ltdl for recursive make'
complete -c libtoolize -l subproject -d 'prepare ltdl to configure and build independently'
complete -c libtoolize -s v -l verbose -d 'verbosely report processing'
complete -c libtoolize -l version -d 'print version information and exit'
complete -c libtoolize -s W -l warnings -d 'report the warnings falling in CATEGORY [all]'
complete -c libtoolize -s h -l help -d 'print short or long help message . SS "Warning categories include:"'

