# linkicc
# Autogenerated from man page /usr/share/man/man1/linkicc.1.gz
complete -c linkicc -s a -d 'Observer adaptation state (abs. col.  only), (0. 1'
complete -c linkicc -s b -d 'Black point compensation'
complete -c linkicc -s c -d 'Precision (0=LowRes, 1=Normal, 2=Hi-res) [defaults to 1]'
complete -c linkicc -s d -d 'Description text (quotes can be used)'
complete -c linkicc -s h -d 'Show summary of options and examples (0=help, 1=Built-in profiles, 2=Examples…'
complete -c linkicc -s k -d 'Ink-limiting in % (CMYK only), (0. 400. 0, float value) [default 400. 0]'
complete -c linkicc -s l -d 'Use linearization curves (may affect accuracy)'
complete -c linkicc -s n -d 'Alternate way to set precision, number of CLUT points'
complete -c linkicc -s o -d 'Output devicelink profile [defaults to \'devicelink. icm\']'
complete -c linkicc -s r -d 'Profile version.  (CAUTION: may change the profile implementation), (2. 0. 4'
complete -c linkicc -s t -d 'Rendering intent . nf '
complete -c linkicc -s v -d 'Verbosity level, (0=None, 1=Normal, 2=High, 3=Very High) [defaults to 0]'
complete -c linkicc -s x -d 'Creatively, guess deviceclass of resulting profile'
complete -c linkicc -s y -d 'Copyright notice (quotes can be used) ["No copyright, use freely"]'
complete -c linkicc -s 8 -d 'Creates 8-bit devicelink.  BUILT-IN PROFILES'

