# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
complete -c login -s p
complete -c login -s f
complete -c login -s h
complete -c login -s H
complete -c login -l help
complete -c login -s V -l version

