# lsfd
# Autogenerated from man page /usr/share/man/man1/lsfd.1.gz
complete -c lsfd -l output
complete -c lsfd -s l -l threads
complete -c lsfd -s J -l json
complete -c lsfd -s n -l noheadings
complete -c lsfd -s o
complete -c lsfd -s r -l raw
complete -c lsfd -l notruncate
complete -c lsfd -s p -l pid
complete -c lsfd -o 'i[4' -l inet
complete -c lsfd -s Q -l filter
complete -c lsfd -s C -l counter
complete -c lsfd -l summary
complete -c lsfd -l debug-filter
complete -c lsfd -l dump-counters
complete -c lsfd -s h -l help
complete -c lsfd -s V -l version

