# lsinitcpio
# Autogenerated from man page /usr/share/man/man1/lsinitcpio.1.gz
complete -c lsinitcpio -s h -l help -d 'Output a short overview of available command-line switches'
complete -c lsinitcpio -s n -l nocolor -d 'Disable color output'
complete -c lsinitcpio -s V -l version -d 'Display version information'
complete -c lsinitcpio -s v -l verbose -d 'Be more verbose'
complete -c lsinitcpio -s a -l analyze
complete -c lsinitcpio -s c -l config
complete -c lsinitcpio -s l -l list
complete -c lsinitcpio -s x -l extract

