# lua
# Autogenerated from man page /usr/share/man/man1/lua.1.gz
complete -c lua -s e -d 'execute statement R stat '
complete -c lua -s i -d 'enter interactive mode after executing R script '
complete -c lua -s l -d 'require library  mod into global R mod '
complete -c lua -s v -d 'show version information'
complete -c lua -s E -d 'ignore environment variables'
complete -c lua -s W -d 'turn warnings on'

