# luac
# Autogenerated from man page /usr/share/man/man1/luac.1.gz
complete -c luac -s l -d 'produce a listing of the compiled bytecode for Lua\'s virtual machine'
complete -c luac -s o -d 'output to R file , instead of the default  luac. out '
complete -c luac -s p -d 'load files but do not generate any output file'
complete -c luac -s s -d 'strip debug information before writing the output file'
complete -c luac -s v -d 'show version information'

