# lzmadec
# Autogenerated from man page /usr/share/man/man1/lzmadec.1.gz
complete -c lzmadec -s d -l decompress -l uncompress -d 'Ignored for  xz (1) compatibility.   xzdec supports only decompression'
complete -c lzmadec -s k -l keep -d 'Ignored for  xz (1) compatibility.   xzdec never creates or removes any files'
complete -c lzmadec -s c -l stdout -l to-stdout -d 'Ignored for  xz (1) compatibility'
complete -c lzmadec -s q -l quiet -d 'Specifying this once does nothing since  xzdec never displays any warnings or…'
complete -c lzmadec -s Q -l no-warn -d 'Ignored for  xz (1) compatibility.   xzdec never uses the exit status 2'
complete -c lzmadec -s h -l help -d 'Display a help message and exit successfully'
complete -c lzmadec -s V -l version -d 'Display the version number of xzdec and liblzma.  EXIT STATUS'

