# makepkg-template
# Autogenerated from man page /usr/share/man/man1/makepkg-template.1.gz
complete -c makepkg-template -s p -l input -d 'Read the package script build script instead of the default'
complete -c makepkg-template -s o -l output -d 'Write the updated file to build script instead of overwriting the input file'
complete -c makepkg-template -s n -l newest -d 'Always use the newest available template file'
complete -c makepkg-template -l template-dir -d 'Change the dir where we are looking for template files'

