# mev
# Autogenerated from man page /usr/share/man/man1/mev.1.gz
complete -c mev -s C -d 'Select a virtual console to get events from'
complete -c mev -s d -d 'Choose a default mask'
complete -c mev -s e -d 'Choose the event mask.  By default any event is received'
complete -c mev -s E -d 'Enter emacs mode'
complete -c mev -s f -d 'Fit events inside the screen before reporting them'
complete -c mev -s i -d 'Interactive.  Accepts input from stdin to change connection parameters'
complete -c mev -s m -d 'Choose the minimum modifier mask'
complete -c mev -s M -d 'Choose the maximum modifier mask'
complete -c mev -s p -d 'Requests to draw the pointer during drags'

