# midicat
# Autogenerated from man page /usr/share/man/man1/midicat.1.gz
complete -c midicat -s d -d 'Dump transferred data in hex on stderr'
complete -c midicat -s i -d 'Read MIDI data from this file instead of receiving it from the MIDI port'
complete -c midicat -s o -d 'Write MIDI data to this file instead of sending it to the MIDI port'
complete -c midicat -s q -d 'Use this sndio 7 MIDI port for input/output'

