# mkfs.minix
# Autogenerated from man page /usr/share/man/man8/mkfs.minix.8.gz
complete -c 'mkfs.minix' -s c -l check
complete -c 'mkfs.minix' -s n -l namelength
complete -c 'mkfs.minix' -l lock
complete -c 'mkfs.minix' -s i -l inodes
complete -c 'mkfs.minix' -s l -l badblocks
complete -c 'mkfs.minix' -s 1
complete -c 'mkfs.minix' -s 2 -s v
complete -c 'mkfs.minix' -s 3
complete -c 'mkfs.minix' -s h -l help
complete -c 'mkfs.minix' -s V -l version

