# mkfs.bfs
# Autogenerated from man page /usr/share/man/man8/mkfs.bfs.8.gz
complete -c 'mkfs.bfs' -s N -l inodes
complete -c 'mkfs.bfs' -s V -l vname
complete -c 'mkfs.bfs' -s F -l fname
complete -c 'mkfs.bfs' -l lock
complete -c 'mkfs.bfs' -s v -l verbose
complete -c 'mkfs.bfs' -s c
complete -c 'mkfs.bfs' -s l
complete -c 'mkfs.bfs' -s h -l help
complete -c 'mkfs.bfs' -l version

