# mkfs.cramfs
# Autogenerated from man page /usr/share/man/man8/mkfs.cramfs.8.gz
complete -c 'mkfs.cramfs' -s v
complete -c 'mkfs.cramfs' -s E
complete -c 'mkfs.cramfs' -s b
complete -c 'mkfs.cramfs' -s e
complete -c 'mkfs.cramfs' -s N
complete -c 'mkfs.cramfs' -s i
complete -c 'mkfs.cramfs' -s n
complete -c 'mkfs.cramfs' -s p
complete -c 'mkfs.cramfs' -s s
complete -c 'mkfs.cramfs' -s z
complete -c 'mkfs.cramfs' -s l
complete -c 'mkfs.cramfs' -s h -l help
complete -c 'mkfs.cramfs' -s V -l version

