# msgexec
# Autogenerated from man page /usr/share/man/man1/msgexec.1.gz
complete -c msgexec -l newline -d 'add newline at the end of input '
complete -c msgexec -s i -l input -d 'input PO file'
complete -c msgexec -s D -l directory -d 'add DIRECTORY to list for input files search '
complete -c msgexec -s P -l properties-input -d 'input file is in Java . properties syntax'
complete -c msgexec -l stringtable-input -d 'input file is in NeXTstep/GNUstep . strings syntax . SS "Informative output:"'
complete -c msgexec -s h -l help -d 'display this help and exit'
complete -c msgexec -s V -l version -d 'output version information and exit AUTHOR Written by Bruno Haible'

