# msginit
# Autogenerated from man page /usr/share/man/man1/msginit.1.gz
complete -c msginit -s i -l input -d 'input POT file '
complete -c msginit -s o -l output-file -d 'write output to specified PO file '
complete -c msginit -s P -l properties-input -d 'input file is in Java . properties syntax'
complete -c msginit -l stringtable-input -d 'input file is in NeXTstep/GNUstep . strings syntax . SS "Output details:"'
complete -c msginit -s l -l locale -d 'set target locale'
complete -c msginit -l no-translator -d 'assume the PO file is automatically generated'
complete -c msginit -l color -d 'use colors and other text attributes always'
complete -c msginit -l style -d 'specify CSS style rule file for --color'
complete -c msginit -s p -l properties-output -d 'write out a Java . properties file'
complete -c msginit -l stringtable-output -d 'write out a NeXTstep/GNUstep . strings file'
complete -c msginit -s w -l width -d 'set output page width'
complete -c msginit -l no-wrap -d 'do not break long message lines, longer than the output page width, into seve…'
complete -c msginit -s h -l help -d 'display this help and exit'
complete -c msginit -s V -l version -d 'output version information and exit AUTHOR Written by Bruno Haible'

