# ncursesw6-config
# Autogenerated from man page /usr/share/man/man1/ncursesw6-config.1.gz
complete -c ncursesw6-config -l prefix -d 'echos the package-prefix of ncurses'
complete -c ncursesw6-config -l exec-prefix -d 'echos the executable-prefix of ncurses'
complete -c ncursesw6-config -l cflags -d 'echos the C compiler flags needed to compile with ncurses'
complete -c ncursesw6-config -l libs -d 'echos the libraries needed to link with ncurses'
complete -c ncursesw6-config -l version -d 'echos the release+patchdate version of ncurses'
complete -c ncursesw6-config -l abi-version -d 'echos the ABI version of ncurses'
complete -c ncursesw6-config -l mouse-version -d 'echos the mouse-interface version of ncurses'
complete -c ncursesw6-config -l bindir -d 'echos the directory containing ncurses programs'
complete -c ncursesw6-config -l datadir -d 'echos the directory containing ncurses data'
complete -c ncursesw6-config -l includedir -d 'echos the directory containing ncurses header files'
complete -c ncursesw6-config -l libdir -d 'echos the directory containing ncurses libraries'
complete -c ncursesw6-config -l mandir -d 'echos the directory containing ncurses manpages'
complete -c ncursesw6-config -l terminfo -d 'echos the $TERMINFO terminfo database path, e. g. , . RS /usr/share/terminfo '
complete -c ncursesw6-config -l terminfo-dirs -d 'echos the $TERMINFO_DIRS directory list, e. g. , . RS /usr/share/terminfo '
complete -c ncursesw6-config -l termpath -d 'echos the $TERMPATH termcap list, if support for termcap is configured'
complete -c ncursesw6-config -l help -d 'prints this message SEE ALSO curses(3X)'

