# ndptool
# Autogenerated from man page /usr/share/man/man8/ndptool.8.gz
complete -c ndptool -s h -l help -d 'Print help text to console and exit'
complete -c ndptool -s v -l verbose -d 'Increase output verbosity'
complete -c ndptool -s t -l msg-type -d 'Specified message type'
complete -c ndptool -s i -l ifname -d 'Specified interface name'
complete -c ndptool -s D -l dest -d 'Specified dest address in IPv6 header for NS/NA message'
complete -c ndptool -s T -l target -d 'Specified target address in ICMPv6 header for NS/NA message'
complete -c ndptool -s U -l unsolicited -d 'Send Unsolicited NA'

