# networkctl
# Autogenerated from man page /usr/share/man/man1/networkctl.1.gz
complete -c networkctl -s a -l all -d 'Show all links with status'
complete -c networkctl -s s -l stats -d 'Show link statistics with status'
complete -c networkctl -s l -l full -d 'Do not ellipsize the output'
complete -c networkctl -s n -l lines -d 'When used with status, controls the number of journal lines to show, counting…'
complete -c networkctl -l drop-in -d 'NAMEWhen used with edit, edit the drop-in file NAME instead of the main confi…'
complete -c networkctl -l no-reload -d 'When used with edit, systemd-networkd or systemd-udevd will not be reloaded a…'
complete -c networkctl -l json -d 'Shows output formatted as JSON'
complete -c networkctl -s h -l help -d 'Print a short help text and exit'
complete -c networkctl -l version -d 'Print a short version string and exit'
complete -c networkctl -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c networkctl -l no-pager -d 'Do not pipe output into a pager'

