# nl-classid-lookup
# Autogenerated from man page /usr/share/man/man8/nl-classid-lookup.8.gz
complete -c nl-classid-lookup -s h -l help -d 'Print help text to console and exit'
complete -c nl-classid-lookup -s v -l version -d 'Print versioning information to console and exit'
complete -c nl-classid-lookup -s r -l reverse -d 'Do a reverse lookup.  Lookup a classid and print its name'
complete -c nl-classid-lookup -l raw -d 'Print the raw classid in hexadecimal format, do not pretty print it'

