# nl-pktloc-lookup
# Autogenerated from man page /usr/share/man/man8/nl-pktloc-lookup.8.gz
complete -c nl-pktloc-lookup -s h -l help -d 'Print help text to console and exit'
complete -c nl-pktloc-lookup -s v -l version -d 'Print versioning information to console and exit'
complete -c nl-pktloc-lookup -s l -l list -d 'List all packet location definitions'
complete -c nl-pktloc-lookup -l u32 -d 'Prints the packet location definition in a special format that is understood …'

