# nl-qdisc-add
# Autogenerated from man page /usr/share/man/man8/nl-qdisc-add.8.gz
complete -c nl-qdisc-add -s h -l help -d 'Print help text to console and exit'
complete -c nl-qdisc-add -s v -l version -d 'Print versioning information to console and exit'
complete -c nl-qdisc-add -s q -l quiet -d 'Do not print informal notifications about actions taken to the console'
complete -c nl-qdisc-add -s d -l dev -d 'Network device the qdisc is attached to'
complete -c nl-qdisc-add -s p -l parent -d 'Identifier of the parent qdisc/class this qdisc is attached to'
complete -c nl-qdisc-add -s i -l id -d 'Identifier of qdisc.  It can be specified as classid or name'
complete -c nl-qdisc-add -l update -d 'Update qdisc if it already exists, otherwise attempting to add a qdisc which …'
complete -c nl-qdisc-add -l replace -d 'Replace or update qdisc if it already exists'
complete -c nl-qdisc-add -l update-only -d 'Update an existing qdisc but do not create it if it does not exist'
complete -c nl-qdisc-add -l replace-only -d 'Update or replace an existing qdisc but do not create it if it does exist'
complete -c nl-qdisc-add -l interactive -d 'The interactive mode requires confirmation by the user for each qdisc deleted'
complete -c nl-qdisc-add -l yes -d 'Make the default answer for interactive prompts be \'y\'es'
complete -c nl-qdisc-add -s k -l kind -d 'Only delete qdiscs of this type. SS nl-qdisc-list Options'
complete -c nl-qdisc-add -l details -d 'Show detailed information for each qdisc listed'
complete -c nl-qdisc-add -l stats -d 'Show statistics information for each qdisc listed'
complete -c nl-qdisc-add -s r -l recursive -d 'List all TC objects recurisvely attached to all qdiscs matching the filter'

