# nologin
# Autogenerated from man page /usr/share/man/man8/nologin.8.gz
complete -c nologin -s c -l command
complete -c nologin -l init-file
complete -c nologin -s i -l interactive
complete -c nologin -s l -l login
complete -c nologin -l noprofile
complete -c nologin -l norc
complete -c nologin -l posix
complete -c nologin -l rcfile
complete -c nologin -s r -l restricted
complete -c nologin -s h -l help
complete -c nologin -s V -l version

