# ocsptool
# Autogenerated from man page /usr/share/man/man1/ocsptool.1.gz
complete -c ocsptool -l load-issuer -d 'against its specified issuer certificate.  Verify response'
complete -c ocsptool -s i -l request-info -d 'The -Q parameter specify the name of the file containing the OCSP request, an…'
complete -c ocsptool -l no-nonce -d 'Verify signature in OCSP response To verify the signature in an OCSP response…'
complete -c ocsptool -l verify-response -d 'OCSP response in DER format from standard input, or from the file specified b…'
complete -c ocsptool -l load-trust -d 'in PEM format'
complete -c ocsptool -l load-signer -d 'one certificate and it will be used to verify the signature in the OCSP respo…'

