# omxregister-bellagio
# Autogenerated from man page /usr/share/man/man1/omxregister-bellagio.1.gz
complete -c omxregister-bellagio -s v -d 'Display a verbose output, listing all the components registered'
complete -c omxregister-bellagio -s h -d 'Display help'

