# oomctl
# Autogenerated from man page /usr/share/man/man1/oomctl.1.gz
complete -c oomctl -s h -l help -d 'Print a short help text and exit'
complete -c oomctl -l version -d 'Print a short version string and exit'
complete -c oomctl -l no-pager -d 'Do not pipe output into a pager'

