# openssl-srp.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-srp.1ssl.gz
complete -c 'openssl-srp.1ssl' -o help -d 'X Item "-help" Display an option summary'
complete -c 'openssl-srp.1ssl' -o verbose -d 'X Item "-verbose" Generate verbose output while processing'
complete -c 'openssl-srp.1ssl' -o add -d 'X Item "-add" Add a user and SRP verifier'
complete -c 'openssl-srp.1ssl' -o modify -d 'X Item "-modify" Modify the SRP verifier of an existing user'
complete -c 'openssl-srp.1ssl' -o delete -d 'X Item "-delete" Delete user from verifier file'
complete -c 'openssl-srp.1ssl' -o list -d 'X Item "-list" List users'
complete -c 'openssl-srp.1ssl' -o name -d 'X Item "-name" The particular SRP definition to use'
complete -c 'openssl-srp.1ssl' -o srpvfile -d 'X Item "-srpvfile file" If the config file is not specified, -srpvfile can be…'
complete -c 'openssl-srp.1ssl' -o gn -d 'X Item "-gn" Specifies the g and N values, using one of the strengths defined…'
complete -c 'openssl-srp.1ssl' -o userinfo -d 'X Item "-userinfo" specifies additional information to add when adding or mod…'
complete -c 'openssl-srp.1ssl' -o passin -o passout -d 'X Item "-passin arg, -passout arg" The password source for the input and outp…'
complete -c 'openssl-srp.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-srp.1ssl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-srp.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-srp.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-srp.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-srp.1ssl' -o config

