# openssl-storeutl.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-storeutl.1ssl.gz
complete -c 'openssl-storeutl.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-storeutl.1ssl' -o out -d 'X Item "-out filename" specifies the output filename to write to or standard …'
complete -c 'openssl-storeutl.1ssl' -o noout -d 'X Item "-noout" this option prevents output of the PEM data'
complete -c 'openssl-storeutl.1ssl' -o passin -d 'X Item "-passin arg" the key password source'
complete -c 'openssl-storeutl.1ssl' -o text -d 'X Item "-text" Prints out the objects in text form, similarly to the -text ou…'
complete -c 'openssl-storeutl.1ssl' -s r -d 'X Item "-r" Fetch objects recursively when possible'
complete -c 'openssl-storeutl.1ssl' -o certs -d 'X Item "-certs"'
complete -c 'openssl-storeutl.1ssl' -o keys -d 'X Item "-keys"'
complete -c 'openssl-storeutl.1ssl' -o crls -d 'X Item "-crls" '
complete -c 'openssl-storeutl.1ssl' -o subject -d 'X Item "-subject arg" Search for an object having the subject name arg'
complete -c 'openssl-storeutl.1ssl' -o issuer -d 'X Item "-issuer arg"'
complete -c 'openssl-storeutl.1ssl' -o serial -d 'X Item "-serial arg" '
complete -c 'openssl-storeutl.1ssl' -o alias -d 'X Item "-alias arg" Search for an object having the given alias'
complete -c 'openssl-storeutl.1ssl' -o fingerprint -d 'X Item "-fingerprint arg" Search for an object having the given fingerprint'
complete -c 'openssl-storeutl.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-storeutl.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-storeutl.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-storeutl.1ssl' -o digest
complete -c 'openssl-storeutl.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  SEE ALSO'

