# openssl-pkeyparam.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-pkeyparam.1ssl.gz
complete -c 'openssl-pkeyparam.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-pkeyparam.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read parameters fr…'
complete -c 'openssl-pkeyparam.1ssl' -o out -d 'X Item "-out filename" This specifies the output filename to write parameters…'
complete -c 'openssl-pkeyparam.1ssl' -o text -d 'X Item "-text" Prints out the parameters in plain text in addition to the enc…'
complete -c 'openssl-pkeyparam.1ssl' -o noout -d 'X Item "-noout" Do not output the encoded version of the parameters'
complete -c 'openssl-pkeyparam.1ssl' -o check -d 'X Item "-check" This option checks the correctness of parameters'
complete -c 'openssl-pkeyparam.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-pkeyparam.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-pkeyparam.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-pkeyparam.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  EXAMPLES'

