# openssl-rand.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-rand.1ssl.gz
complete -c 'openssl-rand.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-rand.1ssl' -o out -d 'X Item "-out file" Write to file instead of standard output'
complete -c 'openssl-rand.1ssl' -o base64 -d 'X Item "-base64" Perform base64 encoding on the output'
complete -c 'openssl-rand.1ssl' -o hex -d 'X Item "-hex" Show the output as a hex string'
complete -c 'openssl-rand.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-rand.1ssl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-rand.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-rand.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-rand.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  SEE ALSO'

