# openssl-sess_id.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-sess_id.1ssl.gz
complete -c 'openssl-sess_id.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-sess_id.1ssl' -o inform -o outform -d 'X Item "-inform DER|PEM, -outform DER|PEM|NSS" The input and output formats; …'
complete -c 'openssl-sess_id.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read session infor…'
complete -c 'openssl-sess_id.1ssl' -o out -d 'X Item "-out filename" This specifies the output filename to write session in…'
complete -c 'openssl-sess_id.1ssl' -o text -d 'X Item "-text" Prints out the various public or private key components in pla…'
complete -c 'openssl-sess_id.1ssl' -o cert -d 'X Item "-cert" If a certificate is present in the session it will be output u…'
complete -c 'openssl-sess_id.1ssl' -o noout -d 'X Item "-noout" This option prevents output of the encoded version of the ses…'
complete -c 'openssl-sess_id.1ssl' -o context

