# openssl-kdf.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-kdf.1ssl.gz
complete -c 'openssl-kdf.1ssl' -o help -d 'X Item "-help" Print a usage message'
complete -c 'openssl-kdf.1ssl' -o keylen -d 'X Item "-keylen num" The output size of the derived key'
complete -c 'openssl-kdf.1ssl' -o out -d 'X Item "-out filename" Filename to output to, or standard output by default'
complete -c 'openssl-kdf.1ssl' -o binary -d 'X Item "-binary" Output the derived key in binary form'
complete -c 'openssl-kdf.1ssl' -o cipher -d 'X Item "-cipher name" Specify the cipher to be used by the KDF'
complete -c 'openssl-kdf.1ssl' -o digest -d 'X Item "-digest name" Specify the digest to be used by the KDF'
complete -c 'openssl-kdf.1ssl' -o mac -d 'X Item "-mac name" Specify the MAC to be used by the KDF'
complete -c 'openssl-kdf.1ssl' -o kdfopt -d 'X Item "-kdfopt nm:v" Passes options to the KDF algorithm'
complete -c 'openssl-kdf.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-kdf.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-kdf.1ssl' -o propquery -d 'X Item "-propquery propq" '

