# openssl-dsaparam.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-dsaparam.1ssl.gz
complete -c 'openssl-dsaparam.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-dsaparam.1ssl' -o inform -d 'X Item "-inform DER|PEM" The DSA parameters input format; unspecified by defa…'
complete -c 'openssl-dsaparam.1ssl' -o outform -d 'X Item "-outform DER|PEM" The DSA parameters output format; the default is PEM'
complete -c 'openssl-dsaparam.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read parameters fr…'
complete -c 'openssl-dsaparam.1ssl' -o out -d 'X Item "-out filename" This specifies the output filename parameters to'
complete -c 'openssl-dsaparam.1ssl' -o noout -d 'X Item "-noout" This option inhibits the output of the encoded version of the…'
complete -c 'openssl-dsaparam.1ssl' -o text -d 'X Item "-text" This option prints out the DSA parameters in human readable fo…'
complete -c 'openssl-dsaparam.1ssl' -o genkey -d 'X Item "-genkey" This option will generate a DSA either using the specified o…'
complete -c 'openssl-dsaparam.1ssl' -o verbose -d 'X Item "-verbose" Print extra details about the operations being performed'
complete -c 'openssl-dsaparam.1ssl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-dsaparam.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-dsaparam.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-dsaparam.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-dsaparam.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  SEE ALSO'

