# openssl-version.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-version.1ssl.gz
complete -c 'openssl-version.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-version.1ssl' -s a -d 'X Item "-a" All information, this is the same as setting all the other flags'
complete -c 'openssl-version.1ssl' -s v -d 'X Item "-v" The current OpenSSL version'
complete -c 'openssl-version.1ssl' -s b -d 'X Item "-b" The date the current version of OpenSSL was built'
complete -c 'openssl-version.1ssl' -s o -d 'X Item "-o" Option information: various options set when the library was built'
complete -c 'openssl-version.1ssl' -s f -d 'X Item "-f" Compilation flags'
complete -c 'openssl-version.1ssl' -s p -d 'X Item "-p" Platform setting'
complete -c 'openssl-version.1ssl' -s d -d 'X Item "-d" OPENSSLDIR setting'
complete -c 'openssl-version.1ssl' -s e -d 'X Item "-e" ENGINESDIR settings'
complete -c 'openssl-version.1ssl' -s m -d 'X Item "-m" MODULESDIR settings'
complete -c 'openssl-version.1ssl' -s r -d 'X Item "-r" The random number generator source settings'
complete -c 'openssl-version.1ssl' -s c

