# openssl-dhparam.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-dhparam.1ssl.gz
complete -c 'openssl-dhparam.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-dhparam.1ssl' -o inform -o outform -d 'X Item "-inform DER|PEM, -outform DER|PEM" The input format and output format…'
complete -c 'openssl-dhparam.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read parameters fr…'
complete -c 'openssl-dhparam.1ssl' -o out -d 'X Item "-out filename" This specifies the output filename parameters to'
complete -c 'openssl-dhparam.1ssl' -o dsaparam -d 'X Item "-dsaparam" If this option is used, DSA rather than DH parameters are …'
complete -c 'openssl-dhparam.1ssl' -o check -d 'X Item "-check" Performs numerous checks to see if the supplied parameters ar…'
complete -c 'openssl-dhparam.1ssl' -s 2 -s 3 -s 5 -d 'X Item "-2, -3, -5" The generator to use, either 2, 3 or 5'
complete -c 'openssl-dhparam.1ssl' -o noout -d 'X Item "-noout" This option inhibits the output of the encoded version of the…'
complete -c 'openssl-dhparam.1ssl' -o text -d 'X Item "-text" This option prints out the DH parameters in human readable form'
complete -c 'openssl-dhparam.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-dhparam.1ssl' -o rand -o writerand -d 'X Item "-rand files, -writerand file" See "Random State Options" in openssl\\|…'
complete -c 'openssl-dhparam.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-dhparam.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-dhparam.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  NOTES'

