# openssl-ciphers.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-ciphers.1ssl.gz
complete -c 'openssl-ciphers.1ssl' -o help -d 'X Item "-help" Print a usage message'
complete -c 'openssl-ciphers.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-ciphers.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-ciphers.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-ciphers.1ssl' -s s -d 'X Item "-s" Only list supported ciphers: those consistent with the security l…'
complete -c 'openssl-ciphers.1ssl' -o psk -d 'X Item "-psk" When combined with -s includes cipher suites which require PSK'
complete -c 'openssl-ciphers.1ssl' -o srp -d 'X Item "-srp" When combined with -s includes cipher suites which require SRP'
complete -c 'openssl-ciphers.1ssl' -s v -d 'X Item "-v" Verbose output: For each cipher suite, list details as provided b…'
complete -c 'openssl-ciphers.1ssl' -s V -d 'X Item "-V" Like -v, but include the official cipher suite values in hex'
complete -c 'openssl-ciphers.1ssl' -o tls1_3 -o tls1_2 -o tls1_1 -o tls1 -o ssl3 -d 'X Item "-tls1_3, -tls1_2, -tls1_1, -tls1, -ssl3" In combination with the -s o…'
complete -c 'openssl-ciphers.1ssl' -o stdname -d 'X Item "-stdname" Precede each cipher suite by its standard name'
complete -c 'openssl-ciphers.1ssl' -o convert -d 'X Item "-convert name" Convert a standard cipher name to its OpenSSL name'
complete -c 'openssl-ciphers.1ssl' -o ciphersuites -d 'X Item "-ciphersuites val" Sets the list of TLSv1. 3 ciphersuites'

