# openssl-pkcs7.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-pkcs7.1ssl.gz
complete -c 'openssl-pkcs7.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-pkcs7.1ssl' -o inform -o outform -d 'X Item "-inform DER|PEM, -outform DER|PEM" The input and formats; the default…'
complete -c 'openssl-pkcs7.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read from or stand…'
complete -c 'openssl-pkcs7.1ssl' -o out -d 'X Item "-out filename" Specifies the output filename to write to or standard …'
complete -c 'openssl-pkcs7.1ssl' -o print -d 'X Item "-print" Print out the full PKCS7 object'
complete -c 'openssl-pkcs7.1ssl' -o print_certs -d 'X Item "-print_certs" Prints out any certificates or CRLs contained in the fi…'
complete -c 'openssl-pkcs7.1ssl' -o text -d 'X Item "-text" Prints out certificate details in full rather than just subjec…'
complete -c 'openssl-pkcs7.1ssl' -o noout -d 'X Item "-noout" Don\'t output the encoded version of the PKCS#7 structure (or …'
complete -c 'openssl-pkcs7.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-pkcs7.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-pkcs7.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-pkcs7.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  EXAMPLES'

