# openssl-s_time.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-s_time.1ssl.gz
complete -c 'openssl-s_time.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-s_time.1ssl' -o connect -d 'X Item "-connect host:port" This specifies the host and optional port to conn…'
complete -c 'openssl-s_time.1ssl' -o www -d 'X Item "-www page" This specifies the page to GET from the server'
complete -c 'openssl-s_time.1ssl' -o cert -d 'X Item "-cert certname" The certificate to use, if one is requested by the se…'
complete -c 'openssl-s_time.1ssl' -o key -d 'X Item "-key keyfile" The private key to use'
complete -c 'openssl-s_time.1ssl' -o verify -d 'X Item "-verify depth" The verify depth to use'
complete -c 'openssl-s_time.1ssl' -o new -d 'X Item "-new" Performs the timing test using a new session ID for each connec…'
complete -c 'openssl-s_time.1ssl' -o reuse -d 'X Item "-reuse" Performs the timing test using the same session ID; this can …'
complete -c 'openssl-s_time.1ssl' -o bugs -d 'X Item "-bugs" There are several known bugs in SSL and TLS implementations'
complete -c 'openssl-s_time.1ssl' -o cipher -d 'X Item "-cipher cipherlist" This allows the TLSv1'
complete -c 'openssl-s_time.1ssl' -o ciphersuites -d 'X Item "-ciphersuites val" This allows the TLSv1'
complete -c 'openssl-s_time.1ssl' -o time -d 'X Item "-time length" Specifies how long (in seconds) this command should est…'
complete -c 'openssl-s_time.1ssl' -o nameopt -d 'X Item "-nameopt option" This specifies how the subject or issuer names are d…'
complete -c 'openssl-s_time.1ssl' -o CAfile -o no-CAfile -o CApath -o no-CApath -o CAstore -o no-CAstore -d 'X Item "-CAfile file, -no-CAfile, -CApath dir, -no-CApath, -CAstore uri, -no-…'
complete -c 'openssl-s_time.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-s_time.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-s_time.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-s_time.1ssl' -o cafile -d 'X Item "-cafile file" This is an obsolete synonym for -CAfile'
complete -c 'openssl-s_time.1ssl' -o ssl3 -o tls1 -o tls1_1 -o tls1_2 -o tls1_3

