# openssl-info.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-info.1ssl.gz
complete -c 'openssl-info.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-info.1ssl' -o configdir -d 'X Item "-configdir" Outputs the default directory for OpenSSL configuration f…'
complete -c 'openssl-info.1ssl' -o enginesdir -d 'X Item "-enginesdir" Outputs the default directory for OpenSSL engine modules'
complete -c 'openssl-info.1ssl' -o modulesdir -d 'X Item "-modulesdir" Outputs the default directory for OpenSSL dynamically lo…'
complete -c 'openssl-info.1ssl' -o dsoext -d 'X Item "-dsoext" Outputs the DSO extension OpenSSL uses'
complete -c 'openssl-info.1ssl' -o dirnamesep -d 'X Item "-dirnamesep" Outputs the separator character between a directory spec…'
complete -c 'openssl-info.1ssl' -o listsep -d 'X Item "-listsep" Outputs the OpenSSL list separator character'
complete -c 'openssl-info.1ssl' -o seeds -d 'X Item "-seeds" Outputs the randomness seed sources'
complete -c 'openssl-info.1ssl' -o cpusettings

