# openssl-pkey.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-pkey.1ssl.gz
complete -c 'openssl-pkey.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-pkey.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-pkey.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-pkey.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-pkey.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-pkey.1ssl' -o check -d 'X Item "-check" This option checks the consistency of a key pair for both pub…'
complete -c 'openssl-pkey.1ssl' -o pubcheck -d 'X Item "-pubcheck" This option checks the correctness of either a public key …'
complete -c 'openssl-pkey.1ssl' -o in -d 'X Item "-in filename|uri" This specifies the input to read a key from or stan…'
complete -c 'openssl-pkey.1ssl' -o inform -d 'X Item "-inform DER|PEM|P12|ENGINE" The key input format; unspecified by defa…'
complete -c 'openssl-pkey.1ssl' -o passin -d 'X Item "-passin arg" The password source for the key input'
complete -c 'openssl-pkey.1ssl' -o pubin -d 'X Item "-pubin" By default a private key is read from the input'
complete -c 'openssl-pkey.1ssl' -o out -d 'X Item "-out filename" This specifies the output filename to save the encoded…'
complete -c 'openssl-pkey.1ssl' -o outform -d 'X Item "-outform DER|PEM" The key output format; the default is PEM'
complete -c 'openssl-pkey.1ssl' -o passout -d 'X Item "-passout arg" The password source for the output file'
complete -c 'openssl-pkey.1ssl' -o traditional -d 'X Item "-traditional" Normally a private key is written using standard format…'
complete -c 'openssl-pkey.1ssl' -o pubout -d 'X Item "-pubout" By default the private and public key is output; this option…'
complete -c 'openssl-pkey.1ssl' -o noout -d 'X Item "-noout" Do not output the key in encoded form'
complete -c 'openssl-pkey.1ssl' -o text -d 'X Item "-text" Output the various key components in plain text (possibly in a…'
complete -c 'openssl-pkey.1ssl' -o text_pub -d 'X Item "-text_pub" Output in text form only the public key components (also f…'
complete -c 'openssl-pkey.1ssl' -o ec_conv_form -d 'X Item "-ec_conv_form arg" This option only applies to elliptic-curve based k…'
complete -c 'openssl-pkey.1ssl' -o cipher
complete -c 'openssl-pkey.1ssl' -o ec_param_enc

