# openssl-crl2pkcs7.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-crl2pkcs7.1ssl.gz
complete -c 'openssl-crl2pkcs7.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-crl2pkcs7.1ssl' -o inform -d 'X Item "-inform DER|PEM" The input format of the CRL; the default is PEM'
complete -c 'openssl-crl2pkcs7.1ssl' -o outform -d 'X Item "-outform DER|PEM" The output format of the PKCS#7 object; the default…'
complete -c 'openssl-crl2pkcs7.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read a CRL from or…'
complete -c 'openssl-crl2pkcs7.1ssl' -o out -d 'X Item "-out filename" Specifies the output filename to write the PKCS#7 stru…'
complete -c 'openssl-crl2pkcs7.1ssl' -o certfile -d 'X Item "-certfile filename" Specifies a filename containing one or more certi…'
complete -c 'openssl-crl2pkcs7.1ssl' -o nocrl -d 'X Item "-nocrl" Normally a CRL is included in the output file'
complete -c 'openssl-crl2pkcs7.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-crl2pkcs7.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-crl2pkcs7.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  EXAMPLES'

