# openssl-verify.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-verify.1ssl.gz
complete -c 'openssl-verify.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-verify.1ssl' -o CRLfile -d 'X Item "-CRLfile filename|uri" The file or URI should contain one or more CRL…'
complete -c 'openssl-verify.1ssl' -o crl_download -d 'X Item "-crl_download" Attempt to download CRL information for certificates v…'
complete -c 'openssl-verify.1ssl' -o show_chain -d 'X Item "-show_chain" Display information about the certificate chain that has…'
complete -c 'openssl-verify.1ssl' -o verbose -d 'X Item "-verbose" Print extra information about the operations being performed'
complete -c 'openssl-verify.1ssl' -o trusted -d 'X Item "-trusted filename|uri" A file or URI of (more or less) trusted certif…'
complete -c 'openssl-verify.1ssl' -o untrusted -d 'X Item "-untrusted filename|uri" A file or URI of untrusted certificates to u…'
complete -c 'openssl-verify.1ssl' -o vfyopt -d 'X Item "-vfyopt nm:v" Pass options to the signature algorithm during verify o…'
complete -c 'openssl-verify.1ssl' -o nameopt -d 'X Item "-nameopt option" This specifies how the subject or issuer names are d…'
complete -c 'openssl-verify.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-verify.1ssl' -o CAfile -o no-CAfile -o CApath -o no-CApath -o CAstore -o no-CAstore -d 'X Item "-CAfile file, -no-CAfile, -CApath dir, -no-CApath, -CAstore uri, -no-…'
complete -c 'openssl-verify.1ssl' -o allow_proxy_certs -o attime -o no_check_time -o check_ss_sig -o crl_check -o crl_check_all -o explicit_policy -o extended_crl -o ignore_critical -o inhibit_any -o inhibit_map -o no_alt_chains -o partial_chain -o policy -o policy_check -o policy_print -o purpose -o suiteB_128 -o suiteB_128_only -o suiteB_192 -o trusted_first -o use_deltas -o auth_level -o verify_depth -o verify_email -o verify_hostname -o verify_ip -o verify_name -o x509_strict -o issuer_checks -d 'X Item "-allow_proxy_certs, -attime, -no_check_time, -check_ss_sig, -crl_chec…'
complete -c 'openssl-verify.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-verify.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-verify.1ssl' -o propquery -d 'X Item "-propquery propq" '

