# openssl-nseq.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-nseq.1ssl.gz
complete -c 'openssl-nseq.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-nseq.1ssl' -o in -d 'X Item "-in filename" This specifies the input filename to read or standard i…'
complete -c 'openssl-nseq.1ssl' -o out -d 'X Item "-out filename" Specifies the output filename or standard output by de…'
complete -c 'openssl-nseq.1ssl' -o toseq -d 'X Item "-toseq" Normally a Netscape certificate sequence will be input and th…'
complete -c 'openssl-nseq.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-nseq.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-nseq.1ssl' -o propquery -d 'See "Provider Options" in openssl(1), provider(7), and property(7).  EXAMPLES'

