# openssl-fipsinstall.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-fipsinstall.1ssl.gz
complete -c 'openssl-fipsinstall.1ssl' -o help -d 'X Item "-help" Print a usage message'
complete -c 'openssl-fipsinstall.1ssl' -o module -d 'X Item "-module filename" Filename of the FIPS module to perform an integrity…'
complete -c 'openssl-fipsinstall.1ssl' -o out -d 'X Item "-out configfilename" Filename to output the configuration data to; th…'
complete -c 'openssl-fipsinstall.1ssl' -o in -d 'X Item "-in configfilename" Input filename to load configuration data from'
complete -c 'openssl-fipsinstall.1ssl' -o verify -d 'X Item "-verify" Verify that the input configuration file contains the correc…'
complete -c 'openssl-fipsinstall.1ssl' -o provider_name -d 'X Item "-provider_name providername" Name of the provider inside the configur…'
complete -c 'openssl-fipsinstall.1ssl' -o section_name -d 'X Item "-section_name sectionname" Name of the section inside the configurati…'
complete -c 'openssl-fipsinstall.1ssl' -o mac_name -d 'X Item "-mac_name name" Specifies the name of a supported MAC algorithm which…'
complete -c 'openssl-fipsinstall.1ssl' -o macopt -d 'X Item "-macopt nm:v" Passes options to the MAC algorithm'
complete -c 'openssl-fipsinstall.1ssl' -o noout -d 'X Item "-noout" Disable logging of the self tests'
complete -c 'openssl-fipsinstall.1ssl' -o pedantic -d 'X Item "-pedantic" Configure the module so that it is strictly FIPS compliant…'
complete -c 'openssl-fipsinstall.1ssl' -o no_conditional_errors -d 'X Item "-no_conditional_errors" Configure the module to not enter an error st…'
complete -c 'openssl-fipsinstall.1ssl' -o no_security_checks -d 'X Item "-no_security_checks" Configure the module to not perform run-time sec…'
complete -c 'openssl-fipsinstall.1ssl' -o ems_check -d 'X Item "-ems_check" Configure the module to enable a run-time Extended Master…'
complete -c 'openssl-fipsinstall.1ssl' -o no_drbg_truncated_digests -d 'X Item "-no_drbg_truncated_digests" Configure the module to not allow truncat…'
complete -c 'openssl-fipsinstall.1ssl' -o self_test_onload -d 'X Item "-self_test_onload" Do not write the two fields related to the "test s…'
complete -c 'openssl-fipsinstall.1ssl' -o self_test_oninstall -d 'X Item "-self_test_oninstall" The converse of -self_test_oninstall'
complete -c 'openssl-fipsinstall.1ssl' -o quiet -d 'X Item "-quiet" Do not output pass/fail messages.  Implies -noout'
complete -c 'openssl-fipsinstall.1ssl' -o corrupt_desc -o corrupt_type -d 'X Item "-corrupt_desc selftest_description, -corrupt_type selftest_type" The …'
complete -c 'openssl-fipsinstall.1ssl' -o config

