# openssl-genpkey.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-genpkey.1ssl.gz
complete -c 'openssl-genpkey.1ssl' -o help -d 'X Item "-help" Print out a usage message'
complete -c 'openssl-genpkey.1ssl' -o out -d 'X Item "-out filename" Output the key to the specified file'
complete -c 'openssl-genpkey.1ssl' -o outform -d 'X Item "-outform DER|PEM" The output format, except when -genparam is given; …'
complete -c 'openssl-genpkey.1ssl' -o quiet -d 'X Item "-quiet" Do not output "status dots" while generating keys'
complete -c 'openssl-genpkey.1ssl' -o pass -d 'X Item "-pass arg" The output file password source'
complete -c 'openssl-genpkey.1ssl' -o algorithm -d 'X Item "-algorithm alg" Public key algorithm to use such as RSA, DSA, DH or D…'
complete -c 'openssl-genpkey.1ssl' -o pkeyopt -d 'X Item "-pkeyopt opt:value" Set the public key algorithm option opt to value'
complete -c 'openssl-genpkey.1ssl' -o genparam -d 'X Item "-genparam" Generate a set of parameters instead of a private key'
complete -c 'openssl-genpkey.1ssl' -o paramfile -d 'X Item "-paramfile filename" Some public key algorithms generate a private ke…'
complete -c 'openssl-genpkey.1ssl' -o text -d 'X Item "-text" Print an (unencrypted) text representation of private and publ…'
complete -c 'openssl-genpkey.1ssl' -o engine -d 'X Item "-engine id" See "Engine Options" in openssl\\|(1)'
complete -c 'openssl-genpkey.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-genpkey.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-genpkey.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-genpkey.1ssl' -o cipher
complete -c 'openssl-genpkey.1ssl' -o config

