# openssl-mac.1ssl
# Autogenerated from man page /usr/share/man/man1/openssl-mac.1ssl.gz
complete -c 'openssl-mac.1ssl' -o help -d 'X Item "-help" Print a usage message'
complete -c 'openssl-mac.1ssl' -o in -d 'X Item "-in filename" Input filename to calculate a MAC for, or standard inpu…'
complete -c 'openssl-mac.1ssl' -o out -d 'X Item "-out filename" Filename to output to, or standard output by default'
complete -c 'openssl-mac.1ssl' -o binary -d 'X Item "-binary" Output the MAC in binary form'
complete -c 'openssl-mac.1ssl' -o cipher -d 'X Item "-cipher name" Used by CMAC and GMAC to specify the cipher algorithm'
complete -c 'openssl-mac.1ssl' -o digest -d 'X Item "-digest name" Used by HMAC as an alphanumeric string (use if the key …'
complete -c 'openssl-mac.1ssl' -o macopt -d 'X Item "-macopt nm:v" Passes options to the MAC algorithm'
complete -c 'openssl-mac.1ssl' -o provider -d 'X Item "-provider name"'
complete -c 'openssl-mac.1ssl' -o provider-path -d 'X Item "-provider-path path"'
complete -c 'openssl-mac.1ssl' -o propquery -d 'X Item "-propquery propq" '
complete -c 'openssl-mac.1ssl' -o 'mac-algorithms\\fR' -d EXAMPLES

