# opj_decompress
# Autogenerated from man page /usr/share/man/man1/opj_decompress.1.gz
complete -c opj_decompress -s i -d '(jpeg2000 input file name)'
complete -c opj_decompress -s l -d 'n is the maximum number of quality layers to decode.  See LAYERS below)'
complete -c opj_decompress -s o -d '(output file name with extension)'
complete -c opj_decompress -s r -d '(n is the highest resolution level to be discarded.  See REDUCTION below)'
complete -c opj_decompress -s x -d '(use name as index file and fill it)'
complete -c opj_decompress -o ImgDir -d '(directory containing input files)'
complete -c opj_decompress -o OutFor -d '(extension for output files)'
complete -c opj_decompress -o jpip -d 'Embed index table box into the output JP2 file (compulsory for JPIP)'
complete -c opj_decompress -o TP -d 'Partition a tile into tile parts of different resolution levels (compulsory f…'
complete -c opj_decompress -s W

