# pacman-key
# Autogenerated from man page /usr/share/man/man8/pacman-key.8.gz
complete -c pacman-key -l config -d 'Use an alternate configuration file instead of the /etc/pacman. conf default'
complete -c pacman-key -l gpgdir -d 'Set an alternate home directory for GnuPG'
complete -c pacman-key -l keyserver -d 'Use the specified keyserver if the operation requires one'
complete -c pacman-key -s a -l add
complete -c pacman-key -s d -l delete
complete -c pacman-key -s e -l export
complete -c pacman-key -l edit-key
complete -c pacman-key -s f -l finger
complete -c pacman-key -s h -l help
complete -c pacman-key -l import
complete -c pacman-key -l import-trustdb
complete -c pacman-key -l init
complete -c pacman-key -s l -l list-keys
complete -c pacman-key -l list-sigs
complete -c pacman-key -l lsign-key
complete -c pacman-key -l nocolor
complete -c pacman-key -s r -l recv-keys
complete -c pacman-key -l refresh-keys
complete -c pacman-key -l populate
complete -c pacman-key -s u -l updatedb
complete -c pacman-key -l check-trustdb -d 'in GnuPG.  This operation can be specified with other operations'
complete -c pacman-key -s V -l version
complete -c pacman-key -s v -l verify

