# pacman-conf
# Autogenerated from man page /usr/share/man/man8/pacman-conf.8.gz
complete -c pacman-conf -s c -l config -d 'Specify an alternate configuration file'
complete -c pacman-conf -s R -l rootdir -d 'Specify an alternate installation root (default is /)'
complete -c pacman-conf -s r -l repo -d 'Query options for a specific repository'
complete -c pacman-conf -s v -l verbose -d 'Always shown directive names'
complete -c pacman-conf -s l -l repo-list -d 'List configured repositories'
complete -c pacman-conf -s h -l help -d 'Output syntax and command line options'
complete -c pacman-conf -s V -l version -d 'Display version and exit'

