# pacman
# Autogenerated from man page /usr/share/man/man8/pacman.8.gz
complete -c pacman -s b -l dbpath -d 'Specify an alternative database location (the default is /var/lib/pacman)'
complete -c pacman -s r -l root -d 'Specify an alternative installation root (default is /)'
complete -c pacman -s v -l verbose -d 'Output paths such as the Root, Conf File, DB Path, Cache Dirs, etc'
complete -c pacman -l arch -d 'Specify an alternate architecture'
complete -c pacman -l cachedir -d 'Specify an alternative package cache location (the default is /var/cache/pacm…'
complete -c pacman -l color -d 'Specify when to enable coloring.  Valid options are always, never, or auto'
complete -c pacman -l config -d 'Specify an alternate configuration file'
complete -c pacman -l debug -d 'Display debug messages'
complete -c pacman -l gpgdir -d 'Specify a directory of files used by GnuPG to verify package signatures (the …'
complete -c pacman -l hookdir -d 'Specify a alternative directory containing hook files (the default is /etc/pa…'
complete -c pacman -l logfile -d 'Specify an alternate log file'
complete -c pacman -l noconfirm -d 'Bypass any and all \\(lqAre you sure?\\(rq messages'
complete -c pacman -l confirm -d 'Cancels the effects of a previous --noconfirm'
complete -c pacman -l disable-download-timeout -d 'Disable defaults for low speed limit and timeout on downloads'
complete -c pacman -l sysroot -d 'Specify an alternative system root'
complete -c pacman -s D -l database
complete -c pacman -s Q -l query
complete -c pacman -s R -l remove
complete -c pacman -l nosave -d 'option is used.  See Remove Options below'
complete -c pacman -s S -l sync
complete -c pacman -s T -l deptest
complete -c pacman -s U -l upgrade
complete -c pacman -s F -l files
complete -c pacman -s V -l version
complete -c pacman -s h -l help
complete -c pacman -s d -l nodeps
complete -c pacman -l assume-installed
complete -c pacman -l dbonly
complete -c pacman -l noprogressbar
complete -c pacman -l noscriptlet
complete -c pacman -s p -l print
complete -c pacman -l print-format -d 'to specify how targets are displayed'
complete -c pacman -s w -l downloadonly
complete -c pacman -l asdeps
complete -c pacman -l asexplicit
complete -c pacman -l recursive -d 'remove operation'
complete -c pacman -l ignore
complete -c pacman -l ignoregroup
complete -c pacman -l needed
complete -c pacman -l overwrite
complete -c pacman -s c -l changelog
complete -c pacman -l deps
complete -c pacman -s t -d 'for listing real orphans - packages that were installed as dependencies but a…'
complete -c pacman -s e -l explicit
complete -c pacman -s g -l groups
complete -c pacman -s i -l info
complete -c pacman -s k -l check
complete -c pacman -s l -l list
complete -c pacman -s m -l foreign
complete -c pacman -s n -l native
complete -c pacman -s o -l owns
complete -c pacman -l file
complete -c pacman -s q -l quiet
complete -c pacman -s s -l search
complete -c pacman -l unrequired
complete -c pacman -s u -l upgrades
complete -c pacman -o Sy
complete -c pacman -l cascade
complete -c pacman -l unneeded
complete -c pacman -l clean
complete -c pacman -l sysupgrade
complete -c pacman -o Su -d 'will do a system upgrade and install/upgrade the "foo" package in the same op…'
complete -c pacman -s y -l refresh
complete -c pacman -s x -l regex
complete -c pacman -l machinereadable -d instead

