# pal2rgb
# Autogenerated from man page /usr/share/man/man1/pal2rgb.1.gz
complete -c pal2rgb -s C -d 'This option overrides the default behavior of pal2rgb in determining whether …'
complete -c pal2rgb -s p -d 'Explicitly select the planar configuration used in organizing data samples in…'
complete -c pal2rgb -s c -d 'Use the specified compression algorithm to encoded image data in the output f…'
complete -c pal2rgb -s r -d 'Explicitly specify the number of rows in each strip of the output file'

