# panelctl
# Autogenerated from man page /usr/share/man/man1/panelctl.1.gz
complete -c panelctl -s c -l commands -d 'Print command list (requires a dummy argument)'
complete -c panelctl -s d -l debug -d 'Debug mode'
complete -c panelctl -s g -l guid -d 'Specify GUID for the STB to control '
complete -c panelctl -s s -l specid -d 'Specify spec_id of STB to control'
complete -c panelctl -s v -l verbose -d 'Produce verbose output'
complete -c panelctl -s '?' -l help -d 'Give this help list'
complete -c panelctl -l usage -d 'Give a short usage message'
complete -c panelctl -s n -l swversion
complete -c panelctl -s V -l version -d 'Print program version'

