# pcap-config
# Autogenerated from man page /usr/share/man/man1/pcap-config.1.gz
complete -c pcap-config -l cflags -d 'option, pcap-config writes to the standard output the'
complete -c pcap-config -s I -d 'compiler flags required to include libpcap\'s header files.  When run with the'
complete -c pcap-config -l libs -d 'option, pcap-config writes to the standard output the'
complete -c pcap-config -s L -d and
complete -c pcap-config -s l -d 'linker flags required to link with libpcap, including'
complete -c pcap-config -l additional-libs -d 'option, pcap-config writes to the standard output the'
complete -c pcap-config -o lpcap -d 'flag to link with libpcap itself'
complete -c pcap-config -l static -d 'flag causes it to write flags appropriate for compiling with a statically-lin…'

