# pcre-config
# Autogenerated from man page /usr/share/man/man1/pcre-config.1.gz
complete -c pcre-config -l prefix -d 'Writes the directory prefix used in the PCRE installation for architecture in…'
complete -c pcre-config -l exec-prefix -d 'Writes the directory prefix used in the PCRE installation for architecture de…'
complete -c pcre-config -l version -d 'Writes the version number of the installed PCRE libraries to the standard out…'
complete -c pcre-config -l libs -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs16 -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs32 -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs-cpp -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l libs-posix -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre-config -l cflags -d 'Writes to the standard output the command line options required to compile fi…'
complete -c pcre-config -l cflags-posix -d 'Writes to the standard output the command line options required to compile fi…'

