# pcre2-config
# Autogenerated from man page /usr/share/man/man1/pcre2-config.1.gz
complete -c pcre2-config -l prefix -d 'Writes the directory prefix used in the PCRE2 installation for architecture i…'
complete -c pcre2-config -l exec-prefix -d 'Writes the directory prefix used in the PCRE2 installation for architecture d…'
complete -c pcre2-config -l version -d 'Writes the version number of the installed PCRE2 libraries to the standard ou…'
complete -c pcre2-config -l libs8 -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre2-config -l libs16 -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre2-config -l libs32 -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre2-config -l libs-posix -d 'Writes to the standard output the command line options required to link with …'
complete -c pcre2-config -l cflags -d 'Writes to the standard output the command line options required to compile fi…'
complete -c pcre2-config -l cflags-posix -d 'Writes to the standard output the command line options required to compile fi…'
complete -c pcre2-config -s I -d 'SEE ALSO pcre2(3) AUTHOR This manual page was originally written by Mark Bake…'

