# pcsc-spy
# Autogenerated from man page /usr/share/man/man1/pcsc-spy.1.gz
complete -c pcsc-spy -s d -l diffable -d 'Remove the variable parts (like handler values) from the output so that two e…'
complete -c pcsc-spy -s h -l help -d 'Display a short help text'
complete -c pcsc-spy -s n -l nocolor -d 'Disable the output colorization (if you want redirect the output in a file fo…'
complete -c pcsc-spy -s v -l version -d 'Print the version of the pcsc-spy program plus a copyright, a list of authors'

