# pg
# Autogenerated from man page /usr/share/man/man1/pg.1.gz
complete -c pg -o number
complete -c pg -s c
complete -c pg -s e
complete -c pg -s f
complete -c pg -s n
complete -c pg -s p
complete -c pg -s r
complete -c pg -s s
complete -c pg -s h -l help
complete -c pg -s V -l version

