# piconv.1perl
# Autogenerated from man page /usr/share/man/man1/piconv.1perl.gz
complete -c 'piconv.1perl' -s f -l from
complete -c 'piconv.1perl' -s t -l to
complete -c 'piconv.1perl' -s s -l string
complete -c 'piconv.1perl' -s l -l list
complete -c 'piconv.1perl' -s r -l resolve
complete -c 'piconv.1perl' -s C -l check
complete -c 'piconv.1perl' -s c
complete -c 'piconv.1perl' -s p -l perlqq
complete -c 'piconv.1perl' -l htmlcref
complete -c 'piconv.1perl' -l xmlcref
complete -c 'piconv.1perl' -s h -l help
complete -c 'piconv.1perl' -s D -l debug
complete -c 'piconv.1perl' -s S -l scheme

