# pidof
# Autogenerated from man page /usr/share/man/man1/pidof.1.gz
complete -c pidof -s s -d 'Single shot - this instructs the program to only return one pid'
complete -c pidof -s c -d 'Only return process ids that are running with the same root directory'
complete -c pidof -s q -d 'Quiet mode, suppress any output and only sets the exit status accordingly'
complete -c pidof -s w -d 'Show also processes that do not have visible command line (e. g'
complete -c pidof -s x -d 'Scripts too - this causes the program to also return process id\'s of shells r…'
complete -c pidof -s o -d 'Tells pidof to omit processes with that process id'
complete -c pidof -s S -d 'Use separator as a separator put between pids'

