# pipesz
# Autogenerated from man page /usr/share/man/man1/pipesz.1.gz
complete -c pipesz -s g -l get
complete -c pipesz -s s -l set
complete -c pipesz -s f -l file
complete -c pipesz -s n -l fd
complete -c pipesz -s i -l stdin
complete -c pipesz -s o -l stdout
complete -c pipesz -s e -l stderr
complete -c pipesz -s c -l check
complete -c pipesz -s q -l quiet
complete -c pipesz -s v -l verbose
complete -c pipesz -s h -l help
complete -c pipesz -s V -l version

