# pk12util
# Autogenerated from man page /usr/share/man/man1/pk12util.1.gz
complete -c pk12util -s i
complete -c pk12util -s l
complete -c pk12util -s o
complete -c pk12util -s c
complete -c pk12util -s C
complete -c pk12util -s d
complete -c pk12util -s h
complete -c pk12util -s k
complete -c pk12util -s K
complete -c pk12util -s m -l key-len
complete -c pk12util -s M
complete -c pk12util -l cert-key-len
complete -c pk12util -s n
complete -c pk12util -s P
complete -c pk12util -s r
complete -c pk12util -s v
complete -c pk12util -s w
complete -c pk12util -s W

