# pkgdata
# Autogenerated from man page /usr/share/man/man1/pkgdata.1.gz
complete -c pkgdata -s h -s '?' -l help -d 'Print help about usage and exit'
complete -c pkgdata -s v -l verbose -d 'Display extra informative messages during execution'
complete -c pkgdata -s c -l copyright -d 'Include a copyright notice in the binary data'
complete -c pkgdata -s C -l comment -d 'Includes the specified  comment in the resulting data instead of the ICU copy…'
complete -c pkgdata -s m -l mode -d 'Set the packaging  mode to be used by   pkgdata '
complete -c pkgdata -s O -l bldopt -d 'Specify options for the builder'
complete -c pkgdata -s p -l name -d 'Set the packaged file name to R name '
complete -c pkgdata -s e -l entrypoint -d 'Set the data entry point (used for linking against the data in a shared libra…'
complete -c pkgdata -s r -l revision -d 'Enable versioning of the shared library produced in  dll , or  library , mode'
complete -c pkgdata -s F -l rebuild -d 'Force the rebuilding of all data and their repackaging'
complete -c pkgdata -s I -l install -d 'Install the packaged file (or all the files in the  files mode)'
complete -c pkgdata -s s -l sourcedir -d 'Set the source directory to R source '
complete -c pkgdata -s d -l destdir -d 'Set the destination directory to R destination '
complete -c pkgdata -s n -d option
complete -c pkgdata -s T -l tempdir -d 'Set the directory used to generate temporary files to directory '

