# playerctl
# Autogenerated from man page /usr/share/man/man1/playerctl.1.gz
complete -c playerctl -s a -d 'Apply command to all available players'
complete -c playerctl -s F -d 'Block and output the updated query when it changes'
complete -c playerctl -s f -d 'Set the output of the current command to FORMAT.  See Format Strings'
complete -c playerctl -s h -d 'Print this help, then exit'
complete -c playerctl -s i -d 'Ignore the specific player NAME'
complete -c playerctl -s l -d 'List the names of running players that can be controlled'
complete -c playerctl -s p -d 'Control the specific player NAME'
complete -c playerctl -s s -d 'Silence some diagnostic and error messages'
complete -c playerctl -s V -d 'Print version number, then exit'

