# pluginviewer
# Autogenerated from man page /usr/share/man/man8/pluginviewer.8.gz
complete -c pluginviewer -s a -d 'List auxprop plugins'
complete -c pluginviewer -s s -d 'List server authentication (SASL) plugins'
complete -c pluginviewer -s c -d 'List client authentication (SASL) plugins'
complete -c pluginviewer -s b -d 'List client authentication (SASL) plugins'
complete -c pluginviewer -s e -d 'Assume that an external security layer (e. g'
complete -c pluginviewer -s m -d 'Limit listed SASL plugins to the ones included in the MECHS (space separated)…'
complete -c pluginviewer -s x -d 'Limit listed auxprop plugins to the one listed in the AUXPROP_MECHS (space se…'
complete -c pluginviewer -s f -d 'Set security flags'
complete -c pluginviewer -s p -d 'Specifies a colon-separated search path for plugins.  SEE ALSO'

