# pod2usage.1perl
# Autogenerated from man page /usr/share/man/man1/pod2usage.1perl.gz
complete -c 'pod2usage.1perl' -o help
complete -c 'pod2usage.1perl' -o man
complete -c 'pod2usage.1perl' -o exit
complete -c 'pod2usage.1perl' -o output
complete -c 'pod2usage.1perl' -o verbose
complete -c 'pod2usage.1perl' -o pathlist
complete -c 'pod2usage.1perl' -o formatter
complete -c 'pod2usage.1perl' -o utf8

