# pod2texi
# Autogenerated from man page /usr/share/man/man1/pod2texi.1.gz
complete -c pod2texi -l appendix-sections -d 'Use appendix sectioning commands (\\f(CW@appendix, '
complete -c pod2texi -l base-level -d 'Sets the level of the \\f(CW\\*(C`head1\\*(C\' commands'
complete -c pod2texi -l debug -d 'Set debugging level to \\s-1NUM\\s0'
complete -c pod2texi -l headings-as-sections -d 'Use headings commands (\\f(CW@heading, '
complete -c pod2texi -l help -d 'Display help and exit'
complete -c pod2texi -l menus -d 'Output node menus'
complete -c pod2texi -l output -d 'Name for the first manual, or the main manual if there is a main manual'
complete -c pod2texi -l no-section-nodes -d 'Use anchors for sections instead of nodes'
complete -c pod2texi -l no-fill-section-gaps -d 'Do not fill sectioning gaps with empty \\f(CW@unnumbered files'
complete -c pod2texi -l preamble -d 'Insert \\s-1STR\\s0 as top boilerplate before menu and includes'
complete -c pod2texi -l setfilename -d 'Use \\s-1STR\\s0 in top boilerplate before menu and includes for \\f(CW@setfilen…'
complete -c pod2texi -l subdir -d 'If there is a main manual with include files (each corresponding to an input …'
complete -c pod2texi -l unnumbered-sections -d 'Use unnumbered sectioning commands (\\f(CW@unnumbered, '
complete -c pod2texi -l top -d 'Name of the \\f(CW@top element for the main manual.   May contain Texinfo code'

