# pod2html.1perl
# Autogenerated from man page /usr/share/man/man1/pod2html.1perl.gz
complete -c 'pod2html.1perl' -l nobacklink -d 'cachedir 4   --cachedir=name Specify which directory is used for storing cache'
complete -c 'pod2html.1perl' -l noheader -d 'blocks.  help 4   --help Displays the usage message'
complete -c 'pod2html.1perl' -l norecurse -d 'title 4   --title=title Specify the title of the resulting HTML file'

