# podchecker.1perl
# Autogenerated from man page /usr/share/man/man1/podchecker.1perl.gz
complete -c 'podchecker.1perl' -o help
complete -c 'podchecker.1perl' -o man
complete -c 'podchecker.1perl' -o warnings -o nowarnings

