# ppm2tiff
# Autogenerated from man page /usr/share/man/man1/ppm2tiff.1.gz
complete -c ppm2tiff -s c -d 'Specify a compression scheme to use when writing image data: -c none for no c…'
complete -c ppm2tiff -s r -d 'Write data with a specified number of rows per strip; by default the number o…'
complete -c ppm2tiff -s R -d 'Mark the resultant image to have the specified X and Y resolution (in dots/in…'

