# psicc
# Autogenerated from man page /usr/share/man/man1/psicc.1.gz
complete -c psicc -s b -d 'Black point compensation (CRD only)'
complete -c psicc -s c -d 'Precision (0=LowRes, 1=Normal, 2=Hi-res) (CRD only) [defaults to 1]'
complete -c psicc -s i -d 'Input profile: Generates Color Space Array (CSA)'
complete -c psicc -s n -d 'Alternate way to set precision, number of CLUT points (CRD only)'
complete -c psicc -s o -d 'p Output profile: Generates Color Rendering Dictionary(CRD)'
complete -c psicc -s t -d 'Intent (0=Perceptual, 1=Colorimetric, 2=Saturation, 3=Absolute) [defaults to …'
complete -c psicc -s u -d 'Do NOT generate resource name on CRD'

