# psl-make-dafsa
# Autogenerated from man page /usr/share/man/man1/psl-make-dafsa.1.gz
complete -c psl-make-dafsa -l output-format -d 'cxx: (default) output is C/C++ code '
complete -c psl-make-dafsa -l encoding -d 'utf-8: (default) UTF-8 mode (output contains UTF-8 + punycode)'

