# psl
# Autogenerated from man page /usr/share/man/man1/psl.1.gz
complete -c psl -l is-public-suffix -d 'check if domains are public suffixes.  [default]'
complete -c psl -l is-cookie-domain-acceptable -d 'check if cookie-domain is acceptable for domains'
complete -c psl -l print-unreg-domain -d 'Returned data: the longest public suffix part for each domain'
complete -c psl -l print-reg-domain -d 'Returned data: the shortest private suffix part for each domain'
complete -c psl -l version -d 'show library version information'
complete -c psl -l print-info -d 'print info about library builtin data PUBLIC SUFFIX DATA By default, `psl\' wi…'
complete -c psl -l use-latest-data -d 'use the latest available PSL data [default]'
complete -c psl -l use-builtin-data -d 'use the builtin PSL data'
complete -c psl -l load-psl-file -d 'load PSL data from file SEE ALSO https://publicsuffix. org/ https://github'

