# ptargrep.1perl
# Autogenerated from man page /usr/share/man/man1/ptargrep.1perl.gz
complete -c 'ptargrep.1perl' -l basename -s b -d 'X Item "--basename (alias -b)" When matching files are extracted, ignore the …'
complete -c 'ptargrep.1perl' -l ignore-case -s i -d 'X Item "--ignore-case (alias -i)" Make pattern matching case-insensitive'
complete -c 'ptargrep.1perl' -l list-only -s l -d 'X Item "--list-only (alias -l)" Print the pathname of each matching file from…'
complete -c 'ptargrep.1perl' -l verbose -s v -d 'X Item "--verbose (alias -v)" Log debugging info to STDERR'
complete -c 'ptargrep.1perl' -l help -s '?'

