# pw-config
# Autogenerated from man page /usr/share/man/man1/pw-config.1.gz
complete -c pw-config -s h -l help -d 'Show help'
complete -c pw-config -l version -d 'Show version information'
complete -c pw-config -s n -l name -d 'Config Name (default \'pipewire. conf\')'
complete -c pw-config -s p -l prefix -d 'Config Prefix (default \'\')'
complete -c pw-config -s L -l no-newline -d 'Omit newlines after values'
complete -c pw-config -s r -l recurse -d 'Reformat config sections recursively'
complete -c pw-config -s N -l no-colors -d 'Disable color output'
complete -c pw-config -s C -l color -d 'whether to enable color support.  WHEN is never, always, or auto'

