# pw-link
# Autogenerated from man page /usr/share/man/man1/pw-link.1.gz
complete -c pw-link -s r -l remote -d 'The name the remote instance to monitor'
complete -c pw-link -s h -l help -d 'Show help'
complete -c pw-link -l version -d 'Show version information'
complete -c pw-link -s o -l output -d 'List output ports'
complete -c pw-link -s i -l input -d 'List output ports'
complete -c pw-link -s l -l links -d 'List links'
complete -c pw-link -s m -l monitor -d 'Monitor links and ports'
complete -c pw-link -s I -l id -d 'List IDs.  Also list the unique link and port ids'
complete -c pw-link -s v -l verbose -d 'Verbose port properties.  Also list the port-object-path and the port-alias'
complete -c pw-link -s L -l linger -d 'Linger.  Will create a link that exists after pw-link is destroyed'
complete -c pw-link -s P -l passive -d 'Passive link'
complete -c pw-link -s p -l props -d 'Properties as JSON object.  Give extra properties when creaing the link'
complete -c pw-link -s d -l disconnect -d 'Disconnect ports'

