# pw-top
# Autogenerated from man page /usr/share/man/man1/pw-top.1.gz
complete -c pw-top -s h -l help -d 'Show help'
complete -c pw-top -s r -l remote -d 'The name the remote instance to monitor'
complete -c pw-top -l version -d 'Show version information'

