# ranlib
# Autogenerated from man page /usr/share/man/man1/ranlib.1.gz
complete -c ranlib -s h -d 'X Item "-h"'
complete -c ranlib -s H -d 'X Item "-H"'
complete -c ranlib -l help -d 'X Item "--help" . PD Show usage information for ranlib'
complete -c ranlib -s v -d 'X Item "-v"'
complete -c ranlib -s V -d 'X Item "-V"'
complete -c ranlib -l version -d 'X Item "--version" . PD Show the version number of ranlib'
complete -c ranlib -s D -d 'X Item "-D" Operate in deterministic mode'
complete -c ranlib -s t -d 'X Item "-t" Update the timestamp of the symbol map of an archive'
complete -c ranlib -s U -d 'X Item "-U" Do not operate in deterministic mode'
complete -c ranlib -l enable-deterministic-archives -d 'default.   It can be disabled with the -U option, described below'

