# raw2tiff
# Autogenerated from man page /usr/share/man/man1/raw2tiff.1.gz
complete -c raw2tiff -s H -d 'Size of input image file header in bytes (0 by default)'
complete -c raw2tiff -s w -d 'Width of input image in pixels (can be guessed, see \\%Guessing the image geom…'
complete -c raw2tiff -s d -d 'type of samples in input image, where datatype may be one of: '
complete -c raw2tiff -s i -d 'type of sample interleaving in input image, where config may be one of: '
complete -c raw2tiff -s p -d 'photometric interpretation (color space) of the input image, where photo may …'
complete -c raw2tiff -s s -d 'swap bytes fetched from the input file'
complete -c raw2tiff -s L -d 'input data has LSB2MSB bit order (default)'
complete -c raw2tiff -s M -d 'input data has MSB2LSB bit order'
complete -c raw2tiff -s c -d 'Specify a compression scheme to use when writing image data: -c none for no c…'
complete -c raw2tiff -s b

