# rdjpgcom
# Autogenerated from man page /usr/share/man/man1/rdjpgcom.1.gz
complete -c rdjpgcom -o raw -d 'Normally rdjpgcom escapes non-printable characters in comments, for security …'
complete -c rdjpgcom -o verbose -d 'Causes rdjpgcom to also display the JPEG image dimensions'

