# recode-sr-latin
# Autogenerated from man page /usr/share/man/man1/recode-sr-latin.1.gz
complete -c recode-sr-latin -s h -l help -d 'display this help and exit'
complete -c recode-sr-latin -s V -l version -d 'output version information and exit AUTHOR Written by Danilo Segan and Bruno …'

