# rename
# Autogenerated from man page /usr/share/man/man1/rename.1.gz
complete -c rename -s s -l symlink
complete -c rename -s v -l verbose
complete -c rename -s n -l no-act
complete -c rename -s a -l all
complete -c rename -s l -l last
complete -c rename -s o -l no-overwrite
complete -c rename -s i -l interactive
complete -c rename -s h -l help
complete -c rename -s V -l version

