# renice
# Autogenerated from man page /usr/share/man/man1/renice.1.gz
complete -c renice -s n
complete -c renice -l priority
complete -c renice -l relative
complete -c renice -s g -l pgrp
complete -c renice -s p -l pid
complete -c renice -s u -l user
complete -c renice -s h -l help
complete -c renice -s V -l version

