# repo-remove
# Autogenerated from man page /usr/share/man/man8/repo-remove.8.gz
complete -c repo-remove -s q -l quiet
complete -c repo-remove -s s -l sign
complete -c repo-remove -s k -l key
complete -c repo-remove -s v -l verify
complete -c repo-remove -l nocolor
complete -c repo-remove -s n -l new
complete -c repo-remove -s R -l remove

