# repo-add
# Autogenerated from man page /usr/share/man/man8/repo-add.8.gz
complete -c repo-add -s q -l quiet
complete -c repo-add -s s -l sign
complete -c repo-add -s k -l key
complete -c repo-add -s v -l verify
complete -c repo-add -l nocolor
complete -c repo-add -s n -l new
complete -c repo-add -s R -l remove

