# rfkill
# Autogenerated from man page /usr/share/man/man8/rfkill.8.gz
complete -c rfkill -s J -l json
complete -c rfkill -s n -l noheadings
complete -c rfkill -s o -l output
complete -c rfkill -l output-all
complete -c rfkill -s r -l raw
complete -c rfkill -s h -l help
complete -c rfkill -s V -l version

