# rgb2ycbcr
# Autogenerated from man page /usr/share/man/man1/rgb2ycbcr.1.gz
complete -c rgb2ycbcr -s c -d 'Specify a compression scheme to use when writing image data: -c none for no c…'
complete -c rgb2ycbcr -s h -d 'Set the horizontal sampling dimension to one of: 1, 2 (default), or 4'
complete -c rgb2ycbcr -s r -d 'Write data with a specified number of rows per strip; by default the number o…'
complete -c rgb2ycbcr -s v -d 'Set the vertical sampling dimension to one of: 1, 2 (default), or 4'

