# saslpasswd2
# Autogenerated from man page /usr/share/man/man8/saslpasswd2.8.gz
complete -c saslpasswd2 -s p -d 'Pipe mode - saslpasswd2 will neither prompt for the password nor verify that …'
complete -c saslpasswd2 -s c -d 'Creates an entry for the user if the user doesn\'t already exist'
complete -c saslpasswd2 -s d -d 'Deletes the entry for the user'
complete -c saslpasswd2 -s n -d 'Don\'t set the plaintext userPassword property for the user'
complete -c saslpasswd2 -s u -d 'use  domain for user domain (realm)'
complete -c saslpasswd2 -s f -d 'use  file for sasldb'
complete -c saslpasswd2 -s a -d 'use  appname as application name'
complete -c saslpasswd2 -s v -d 'Print libsasl2 version number and exit.  SEE ALSO sasldblistusers2(8)'

