# sasldblistusers2
# Autogenerated from man page /usr/share/man/man8/sasldblistusers2.8.gz
complete -c sasldblistusers2 -s f -d 'use  file for sasldb'
complete -c sasldblistusers2 -s v -d 'Print libsasl2 version number and exit.  SEE ALSO saslpasswd2(8)'

