# scmp_sys_resolver
# Autogenerated from man page /usr/share/man/man1/scmp_sys_resolver.1.gz
complete -c scmp_sys_resolver -s a -d 'The architecture to use for resolving the system call'
complete -c scmp_sys_resolver -s t -d 'If necessary, translate the system call name to the proper system call number…'
complete -c scmp_sys_resolver -s h -d 'A simple one-line usage display'

