# seatd
# Autogenerated from man page /usr/share/man/man1/seatd.1.gz
complete -c seatd -s h -d 'Show help message and quit'
complete -c seatd -s n -d 'FD to notify readiness on.  A single newline will be written and the fd'
complete -c seatd -s u -d 'User to own the seatd socket'
complete -c seatd -s g -d 'Group to own the seatd socket'
complete -c seatd -s l -d 'Log-level to use.  Must be one of debug, info, error or silent.  Defaults'
complete -c seatd -s v -d 'Show the version number and quit'

