# seatd-launch
# Autogenerated from man page /usr/share/man/man1/seatd-launch.1.gz
complete -c seatd-launch -s l -d 'Log-level to pass to seatd.  See seatd(1) for information about'
complete -c seatd-launch -s h -d 'Show help message and quit'
complete -c seatd-launch -s v -d 'Show the version number and quit'

