# sendiso
# Autogenerated from man page /usr/share/man/man1/sendiso.1.gz
complete -c sendiso -s l -l loop -d 'Send dump file COUNT times.   Defaults to 1'
complete -c sendiso -s i -l infinite -d 'Send dump file in an endless loop'
complete -c sendiso -s s -l speed -d 'Send packets at speed SPEED, which can be given as 100, 200 and 400 (in Mbit/…'
complete -c sendiso -s p -l port -d 'Choose port PORT for sending'
complete -c sendiso -s h -l help -d 'Show help text and exit'

