# sensors-detect
# Autogenerated from man page /usr/share/man/man8/sensors-detect.8.gz
complete -c sensors-detect -l auto -d 'Run in automatic, non-interactive mode'
complete -c sensors-detect -l stat -d 'Display I2C address statistics'

