# setfattr
# Autogenerated from man page /usr/share/man/man1/setfattr.1.gz
complete -c setfattr -s n -l name -d 'Specifies the name of the extended attribute to set'
complete -c setfattr -s v -l value -d 'Specifies the new value of the extended attribute'
complete -c setfattr -s x -l remove -d 'Remove the named extended attribute entirely'
complete -c setfattr -s h -l no-dereference -d 'Do not follow symlinks'
complete -c setfattr -l restore -d 'Restores extended attributes from file'
complete -c setfattr -l raw -d 'Do not decode the attribute value'
complete -c setfattr -l version -d 'Print the version of  setfattr and exit'
complete -c setfattr -l help -d 'Print help explaining the command line options'
complete -c setfattr -l dump -d 'option.  If a dash (c'

