# signver
# Autogenerated from man page /usr/share/man/man1/signver.1.gz
complete -c signver -s A -d 'Displays all of the information in the PKCS#7 signature'
complete -c signver -s V -d 'Verifies the digital signature'
complete -c signver -s d -d 'Specify the database directory which contains the certificates and keys'
complete -c signver -s a -d 'Sets that the given signature file is in ASCII format'
complete -c signver -s i -d 'Gives the input file for the object with signed data'
complete -c signver -s o -d 'Gives the output file to which to write the results'
complete -c signver -s s -d 'Gives the input file for the digital signature'
complete -c signver -s v -d 'Enables verbose output'

