# slsh
# Autogenerated from man page /usr/share/man/man1/slsh.1.gz
complete -c slsh -l help -d 'Show a summary of options'
complete -c slsh -l version -d 'Show slsh version information'
complete -c slsh -s g -d 'Compile with debugging code, tracebacks, etc'
complete -c slsh -s n -d 'Don\'t load the personal initialization file'
complete -c slsh -l init -d 'Use this file instead of ~/. slshrc'
complete -c slsh -l no-readline -d 'Do not use a readline interface for the interactive mode'
complete -c slsh -s e -d 'Execute ``string\'\' as S-Lang code'
complete -c slsh -s i -d 'Force interactive mode'
complete -c slsh -s q -l quiet -d 'Startup quietly by not printing the version and copyright information'
complete -c slsh -s t -d 'Normally, slsh will call slsh_main if it is defined'

