# sndfile-metadata-set
# Autogenerated from man page /usr/share/man/man1/sndfile-metadata-set.1.gz
complete -c sndfile-metadata-set -l all -d 'all metadata'
complete -c sndfile-metadata-set -l bext-description -d description
complete -c sndfile-metadata-set -l bext-originator -d 'originator info'
complete -c sndfile-metadata-set -l bext-orig-ref -d 'originator reference'
complete -c sndfile-metadata-set -l bext-umid -d 'Unique Material Identifier'
complete -c sndfile-metadata-set -l bext-orig-date -d 'origination date'
complete -c sndfile-metadata-set -l bext-orig-time -d 'origination time'
complete -c sndfile-metadata-set -l bext-coding-hist -d 'coding history'
complete -c sndfile-metadata-set -l str-title -d title
complete -c sndfile-metadata-set -l str-copyright -d copyright
complete -c sndfile-metadata-set -l str-artist -d artist
complete -c sndfile-metadata-set -l str-comment -d comment
complete -c sndfile-metadata-set -l str-date -d 'creation date'
complete -c sndfile-metadata-set -l str-album -d album
complete -c sndfile-metadata-set -l str-license -d 'license El Pp sndfile-metadata-set sndfile-metadata-set sets bext and string …'
complete -c sndfile-metadata-set -l bext-time-raf -d 'time reference'
complete -c sndfile-metadata-set -l bext-auto-time-date -d 'Set the BEXT time and date to current'
complete -c sndfile-metadata-set -l bext-auto-time -d 'Set the BEXT time to current'
complete -c sndfile-metadata-set -l bext-auto-date -d 'Set the BEXT date to current'
complete -c sndfile-metadata-set -l str-auto-date -d 'Set the string date to current'

