# sndfile-convert
# Autogenerated from man page /usr/share/man/man1/sndfile-convert.1.gz
complete -c sndfile-convert -o override-sample-rate -d 'Make the input use sample rate of rate Hz'
complete -c sndfile-convert -o endian -d 'Make the output file use little endian data'
complete -c sndfile-convert -o normalize -d 'Normalize the audio data in the output file'
complete -c sndfile-convert -o pcms8 -d 'signed 8 bit pcm'
complete -c sndfile-convert -o pcmu8 -d 'unsigned 8 bit pcm'
complete -c sndfile-convert -o pcm16 -d '16 bit pcm'
complete -c sndfile-convert -o pcm24 -d '24 bit pcm'
complete -c sndfile-convert -o pcm32 -d '32 bit pcm'
complete -c sndfile-convert -o float32 -d '32 bit floating point'
complete -c sndfile-convert -o ulaw -d ULAW
complete -c sndfile-convert -o alaw -d ALAW
complete -c sndfile-convert -o ima-adpcm -d 'IMA ADPCM (WAV only)'
complete -c sndfile-convert -o ms-adpcm -d 'MS ADPCM (WAV only)'
complete -c sndfile-convert -o gsm610 -d 'GSM6. 10 (WAV only)'
complete -c sndfile-convert -o dwvw12 -d '12 bit DWVW (AIFF only)'
complete -c sndfile-convert -o dwvw16 -d '16 bit DWVW (AIFF only)'
complete -c sndfile-convert -o dwvw24 -d '24 bit DWVW (AIFF only)'
complete -c sndfile-convert -o vorbis -d 'Vorbis (OGG only) El Pp If no encoding is specified for the output file, sndf…'

