# speexdec
# Autogenerated from man page /usr/share/man/man1/speexdec.1.gz
complete -c speexdec -l enh -d 'Enable perceptual enhancement (default)'
complete -c speexdec -l no-enh -d 'Disable perceptual enhancement'
complete -c speexdec -l force-nb -d 'Force decoding in narrowband'
complete -c speexdec -l force-wb -d 'Force decoding in wideband'
complete -c speexdec -l force-uwb -d 'Force decoding in ultra-wideband'
complete -c speexdec -l mono -d 'Force decoding in mono'
complete -c speexdec -l stereo -d 'Force decoding in stereo'
complete -c speexdec -l rate -d 'Force decoding at sampling rate n Hz'
complete -c speexdec -l packet-loss -d 'Simulate n % random packet loss'
complete -c speexdec -s V -d 'Verbose mode (show bit-rate)'
complete -c speexdec -s h -l help -d 'This help'
complete -c speexdec -s v -l version -d 'Version information'
complete -c speexdec -l pf -d 'Deprecated, use --enh instead'
complete -c speexdec -l no-pf -d 'Deprecated, use --no-enh instead'

