# ssltap
# Autogenerated from man page /usr/share/man/man1/ssltap.1.gz
complete -c ssltap -s f -d 'Turn on fancy printing.  Output is printed in colored HTML'
complete -c ssltap -s h -d 'Turn on hex/ASCII printing'
complete -c ssltap -s l -d 'Turn on looping; that is, continue to accept connections rather than stopping…'
complete -c ssltap -s p -d 'Change the default rendezvous port (1924) to another port'
complete -c ssltap -s s -d 'Turn on SSL parsing and decoding'
complete -c ssltap -s v -d 'Print a version string for the tool'
complete -c ssltap -s x -d 'Turn on extra SSL hex dumps'
complete -c ssltap -l '>;' -d 'alloclen = 66 bytes    [ssl2]  ClientHelloV2 {             version = {0x03, 0…'
complete -c ssltap -l '>' -d 'SSLRecord {    0: 16 03 00 00  44                                   |'

