# streamzip.1perl
# Autogenerated from man page /usr/share/man/man1/streamzip.1perl.gz
complete -c 'streamzip.1perl' -o zip64
complete -c 'streamzip.1perl' -o zipfile
complete -c 'streamzip.1perl' -o member-name
complete -c 'streamzip.1perl' -o stream
complete -c 'streamzip.1perl' -o method
complete -c 'streamzip.1perl' -s 0 -s 1 -s 2 -s 3 -s 4 -s 5 -s 6 -s 7 -s 8 -s 9
complete -c 'streamzip.1perl' -o version
complete -c 'streamzip.1perl' -o help

