# systemd-sysupdate
# Autogenerated from man page /usr/share/man/man8/systemd-sysupdate.8.gz
complete -c systemd-sysupdate -l component -s C -d 'Selects the component to update.  Takes a component name as argument'
complete -c systemd-sysupdate -l definitions -d 'A path to a directory.  If specified, the transfer *'
complete -c systemd-sysupdate -l root -d 'Takes a path to a directory to use as root file system when searching for sys…'
complete -c systemd-sysupdate -l image -d 'Takes a path to a disk image file or device to mount and use in a similar fas…'
complete -c systemd-sysupdate -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c systemd-sysupdate -l instances-max -s m -d 'Takes a decimal integer greater than or equal to 2'
complete -c systemd-sysupdate -l sync -d 'Takes a boolean argument, defaults to yes'
complete -c systemd-sysupdate -l verify -d 'Takes a boolean argument, defaults to yes'
complete -c systemd-sysupdate -l reboot -d 'When used in combination with the update command and a new version is install…'
complete -c systemd-sysupdate -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-sysupdate -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-sysupdate -l json -d 'Shows output formatted as JSON'
complete -c systemd-sysupdate -s h -l help
complete -c systemd-sysupdate -l version

