# systemd-suspend.service
# Autogenerated from man page /usr/share/man/man8/systemd-suspend.service.8.gz
complete -c 'systemd-suspend.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-suspend.service' -l version -d 'Print a short version string and exit'

