# systemd-sysctl.service
# Autogenerated from man page /usr/share/man/man8/systemd-sysctl.service.8.gz
complete -c 'systemd-sysctl.service' -l prefix -d 'Only apply rules with the specified prefix'
complete -c 'systemd-sysctl.service' -l strict -d 'Always return non-zero exit code on failure (including invalid sysctl variabl…'
complete -c 'systemd-sysctl.service' -l cat-config -d 'Copy the contents of config files to standard output'
complete -c 'systemd-sysctl.service' -l no-pager -d 'Do not pipe output into a pager'
complete -c 'systemd-sysctl.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-sysctl.service' -l version -d 'Print a short version string and exit'

