# systemd-oomd.service
# Autogenerated from man page /usr/share/man/man8/systemd-oomd.service.8.gz
complete -c 'systemd-oomd.service' -l dry-run -d 'Do a dry run of systemd-oomd: when a kill is triggered, print it to the log i…'
complete -c 'systemd-oomd.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-oomd.service' -l version -d 'Print a short version string and exit'
complete -c 'systemd-oomd.service' -o '.slice'

