# systemd-binfmt.service
# Autogenerated from man page /usr/share/man/man8/systemd-binfmt.service.8.gz
complete -c 'systemd-binfmt.service' -l unregister -d 'If passed, instead of registering configured binary formats in the kernel, th…'
complete -c 'systemd-binfmt.service' -l cat-config -d 'Copy the contents of config files to standard output'
complete -c 'systemd-binfmt.service' -l no-pager -d 'Do not pipe output into a pager'
complete -c 'systemd-binfmt.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-binfmt.service' -l version -d 'Print a short version string and exit'

