# systemd-ac-power
# Autogenerated from man page /usr/share/man/man1/systemd-ac-power.1.gz
complete -c systemd-ac-power -s v -l verbose -d 'Show result as text instead of just returning success or failure'
complete -c systemd-ac-power -l low -d 'Instead of showing AC power state, show low battery state'
complete -c systemd-ac-power -s h -l help -d 'Print a short help text and exit'
complete -c systemd-ac-power -l version -d 'Print a short version string and exit'

