# systemd-battery-check.service
# Autogenerated from man page /usr/share/man/man8/systemd-battery-check.service.8.gz
complete -c 'systemd-battery-check.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-battery-check.service' -l version -d 'Print a short version string and exit'

