# systemd-bless-boot.service
# Autogenerated from man page /usr/share/man/man8/systemd-bless-boot.service.8.gz
complete -c 'systemd-bless-boot.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-bless-boot.service' -l version -d 'Print a short version string and exit'

