# systemd-notify
# Autogenerated from man page /usr/share/man/man1/systemd-notify.1.gz
complete -c systemd-notify -l ready -d 'Inform the invoking service manager about service start-up or configuration r…'
complete -c systemd-notify -l reloading -d 'Inform the invoking service manager about the beginning of a configuration re…'
complete -c systemd-notify -l stopping -d 'Inform the invoking service manager about the beginning of the shutdown phase…'
complete -c systemd-notify -l pid -d 'Inform the service manager about the main PID of the service'
complete -c systemd-notify -l uid -d 'Set the user ID to send the notification from'
complete -c systemd-notify -l status -d 'Send a free-form human readable status string for the daemon to the service m…'
complete -c systemd-notify -l booted -d 'Returns 0 if the system was booted up with systemd, non-zero otherwise'
complete -c systemd-notify -l no-block -d 'Do not synchronously wait for the requested operation to finish'
complete -c systemd-notify -l exec -d 'If specified systemd-notify will execute another command line after it comple…'
complete -c systemd-notify -l fd -d 'Send a file descriptor along with the notification message'
complete -c systemd-notify -l fdname -d 'Set a name to assign to the file descriptors passed via --fd= (see above)'
complete -c systemd-notify -s h -l help -d 'Print a short help text and exit'
complete -c systemd-notify -l version -d 'Print a short version string and exit'

