# systemd-creds
# Autogenerated from man page /usr/share/man/man1/systemd-creds.1.gz
complete -c systemd-creds -l system -d 'When specified with the list and cat commands operates on the credentials pas…'
complete -c systemd-creds -l transcode -d 'When specified with the cat or decrypt commands, transcodes the output before…'
complete -c systemd-creds -l newline -d 'When specified with cat or decrypt controls whether to add a trailing newline…'
complete -c systemd-creds -l pretty -s p -d 'When specified with encrypt controls whether to show the encrypted credential…'
complete -c systemd-creds -l name -d 'When specified with the encrypt command controls the credential name to embed…'
complete -c systemd-creds -l timestamp -d 'When specified with the encrypt command controls the timestamp to embed into …'
complete -c systemd-creds -l not-after -d 'When specified with the encrypt command controls the time when the credential…'
complete -c systemd-creds -l with-key -s H -s T -d 'When specified with the encrypt command controls the encryption/signature key…'
complete -c systemd-creds -l tpm2-device -d 'Controls the TPM2 device to use'
complete -c systemd-creds -l tpm2-pcrs -d 'Configures the TPM2 PCRs (Platform Configuration Registers) to bind the encry…'
complete -c systemd-creds -l tpm2-public-key -l tpm2-public-key-pcrs -d 'Configures a TPM2 signed PCR policy to bind encryption to, for use with the e…'
complete -c systemd-creds -l tpm2-signature -d 'Takes a path to a TPM2 PCR signature file as generated by the systemd-measure…'
complete -c systemd-creds -l quiet -s q -d 'When used with has-tpm2 suppresses the output, and only returns an exit statu…'
complete -c systemd-creds -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-creds -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-creds -l json -d 'Shows output formatted as JSON'
complete -c systemd-creds -s h -l help
complete -c systemd-creds -l version

