# systemd-sysext
# Autogenerated from man page /usr/share/man/man8/systemd-sysext.8.gz
complete -c systemd-sysext -l root -d 'Operate relative to the specified root directory, i. e'
complete -c systemd-sysext -l force -d 'When merging system extensions into /usr/ and /opt/ for sysext and /etc/ for …'
complete -c systemd-sysext -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c systemd-sysext -l noexec -d 'When merging configuration extensions into /etc/ the "MS_NOEXEC" mount flag i…'
complete -c systemd-sysext -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-sysext -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-sysext -l json -d 'Shows output formatted as JSON'
complete -c systemd-sysext -l directory -d 'switches and those that the service manager supports via RootDirectory=/RootI…'
complete -c systemd-sysext -s h -l help
complete -c systemd-sysext -l version

