# systemd-udevd.service
# Autogenerated from man page /usr/share/man/man8/systemd-udevd.service.8.gz
complete -c 'systemd-udevd.service' -s d -l daemon -d 'Detach and run in the background'
complete -c 'systemd-udevd.service' -s D -l debug -d 'Print debug messages to standard error'
complete -c 'systemd-udevd.service' -s c -l children-max -d 'Limit the number of events executed in parallel'
complete -c 'systemd-udevd.service' -s e -l exec-delay -d 'Delay the execution of each RUN{program} parameter by the given number of sec…'
complete -c 'systemd-udevd.service' -s t -l event-timeout -d 'Set the number of seconds to wait for events to finish'
complete -c 'systemd-udevd.service' -s s -l timeout-signal -d 'Set the signal which systemd-udevd will send to forked off processes after re…'
complete -c 'systemd-udevd.service' -s N -l resolve-names -d 'Specify when systemd-udevd should resolve names of users and groups'
complete -c 'systemd-udevd.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-udevd.service' -l version -d 'Print a short version string and exit'

