# systemd-cryptenroll
# Autogenerated from man page /usr/share/man/man1/systemd-cryptenroll.1.gz
complete -c systemd-cryptenroll -l password -d 'Enroll a regular password/passphrase'
complete -c systemd-cryptenroll -l recovery-key -d 'Enroll a recovery key'
complete -c systemd-cryptenroll -l unlock-key-file -d 'Use a file instead of a password/passphrase read from stdin to unlock the vol…'
complete -c systemd-cryptenroll -l unlock-fido2-device -d 'Use a FIDO2 device instead of a password/passphrase read from stdin to unlock…'
complete -c systemd-cryptenroll -l pkcs11-token-uri -d 'Enroll a PKCS#11 security token or smartcard (e. g.  a YubiKey)'
complete -c systemd-cryptenroll -l fido2-credential-algorithm -d 'Specify COSE algorithm used in credential generation'
complete -c systemd-cryptenroll -l fido2-device -d 'Enroll a FIDO2 security token that implements the "hmac-secret" extension (e'
complete -c systemd-cryptenroll -l fido2-with-client-pin -d 'When enrolling a FIDO2 security token, controls whether to require the user t…'
complete -c systemd-cryptenroll -l fido2-with-user-presence -d 'When enrolling a FIDO2 security token, controls whether to require the user t…'
complete -c systemd-cryptenroll -l fido2-with-user-verification -d 'When enrolling a FIDO2 security token, controls whether to require user verif…'
complete -c systemd-cryptenroll -l tpm2-device -d 'Enroll a TPM2 security chip'
complete -c systemd-cryptenroll -l tpm2-pcrs -d 'Configures the TPM2 PCRs (Platform Configuration Registers) to bind to when e…'
complete -c systemd-cryptenroll -l tpm2-with-pin -d 'When enrolling a TPM2 device, controls whether to require the user to enter a…'
complete -c systemd-cryptenroll -l tpm2-public-key -l tpm2-public-key-pcrs -l tpm2-signature -d 'Configures a TPM2 signed PCR policy to bind encryption to'
complete -c systemd-cryptenroll -l wipe-slot -d 'Wipes one or more LUKS2 key slots'
complete -c systemd-cryptenroll -s h -l help -d 'Print a short help text and exit'
complete -c systemd-cryptenroll -l version -d 'Print a short version string and exit'
complete -c systemd-cryptenroll -l key-file-offset -d or
complete -c systemd-cryptenroll -l key-file-size -d 'so this file has to only contain the full key'

