# teamdctl
# Autogenerated from man page /usr/share/man/man8/teamdctl.8.gz
complete -c teamdctl -s h -l help -d 'Print help text to console and exit'
complete -c teamdctl -s v -l verbosity -d 'Increase output verbosity'
complete -c teamdctl -s o -l oneline -d 'Force output to one line if possible'
complete -c teamdctl -s D -l force-dbus -d 'Force to use D-Bus interface'
complete -c teamdctl -s Z -l force-zmq -d 'Force to use ZMQ interface'
complete -c teamdctl -s U -l force-usock -d 'Force to use UNIX domain socket interface.  This is the default behavior'

