# texindex
# Autogenerated from man page /usr/share/man/man1/texindex.1.gz
complete -c texindex -s h -l help -d 'display this help and exit'
complete -c texindex -l version -d 'display version information and exit'

