# thumbnail
# Autogenerated from man page /usr/share/man/man1/thumbnail.1.gz
complete -c thumbnail -s w -d 'Specify the width of thumbnail images in pixels'
complete -c thumbnail -s h -d 'Specify the height of thumbnail images in pixels'
complete -c thumbnail -s c -d 'Specify a contrast curve to apply in generating the thumbnail images'

