# tiffmedian
# Autogenerated from man page /usr/share/man/man1/tiffmedian.1.gz
complete -c tiffmedian -s c -d 'Specify the compression to use for data written to the output file: -c none f…'
complete -c tiffmedian -s C -d 'Specify the number of entries to use in the generated colormap'
complete -c tiffmedian -s f -d 'Apply Floyd-Steinberg dithering before selecting a colormap entry'
complete -c tiffmedian -s r -d 'Specify the number of rows (scanlines) in each strip of data written to the o…'

