# tiffdump
# Autogenerated from man page /usr/share/man/man1/tiffdump.1.gz
complete -c tiffdump -s h -d 'Force numeric data to be printed in hexadecimal rather than the default decim…'
complete -c tiffdump -s m -d 'Change the number of indirect data items that are printed'
complete -c tiffdump -s o -d 'Dump the contents of the IFD at the a particular file offset'

