# tiffgt
# Autogenerated from man page /usr/share/man/man1/tiffgt.1.gz
complete -c tiffgt -s c -d 'Force image display in a colormap window'
complete -c tiffgt -s d -d 'Specify an image to display by directory number'
complete -c tiffgt -s e -d 'Enable reporting of error messages from the TIFF library'
complete -c tiffgt -s f -d 'Force tiffgt to run as a foreground process'
complete -c tiffgt -s l -d 'Force the presumed bit ordering to be LSB to MSB'
complete -c tiffgt -s m -d 'Force the presumed bit ordering to be MSB to LSB'
complete -c tiffgt -s o -d 'Specify an image to display by directory offset'
complete -c tiffgt -s p -d 'Override the value of the PhotometricInterpretation tag; the parameter may be…'
complete -c tiffgt -s r -d 'Force image display in a full color window'
complete -c tiffgt -s s -d 'Stop on the first read error'
complete -c tiffgt -s w -d 'Enable reporting of warning messages from the TIFF library'
complete -c tiffgt -s v -d 'Place information in the title bar describing what type of window (full color…'

