# tiff2rgba
# Autogenerated from man page /usr/share/man/man1/tiff2rgba.1.gz
complete -c tiff2rgba -s c -d 'Specify a compression scheme to use when writing image data: -c none for no c…'
complete -c tiff2rgba -s r -d 'Write data with a specified number of rows per strip; by default the number o…'
complete -c tiff2rgba -s b -d 'Process the image one block (strip/tile) at a time instead of by reading the …'
complete -c tiff2rgba -s n -d 'Drop the alpha component from the output file, producing a pure RGB file'
complete -c tiff2rgba -s M -d 'Set maximum memory allocation size (in MiB).  The default is 256MiB'

