# tiffcmp
# Autogenerated from man page /usr/share/man/man1/tiffcmp.1.gz
complete -c tiffcmp -s l -d 'List each byte of image data that differs between the files'
complete -c tiffcmp -s z -d 'List specified number of image data bytes that differs between the files'
complete -c tiffcmp -s t -d 'Ignore any differences in directory tags'

