# tiffdither
# Autogenerated from man page /usr/share/man/man1/tiffdither.1.gz
complete -c tiffdither -s c -d 'Specify the compression to use for data written to the output file: '
complete -c tiffdither -s f -d 'Specify the bit fill order to use in writing output data'
complete -c tiffdither -s r -d 'Make each strip have no more than the given number of rows'
complete -c tiffdither -s t -d 'Set the threshold value for dithering.  By default the threshold value is 128'

