# tiffinfo
# Autogenerated from man page /usr/share/man/man1/tiffinfo.1.gz
complete -c tiffinfo -s c -d 'Display the colormap and color/gray response curves, if present'
complete -c tiffinfo -s D -d 'In addition to displaying the directory tags, read and decompress all the dat…'
complete -c tiffinfo -s d -d 'In addition to displaying the directory tags, print each byte of decompressed…'
complete -c tiffinfo -s j -d 'Display any JPEG-related tags that are present'
complete -c tiffinfo -s o -d 'Set the initial TIFF directory according to the specified file offset'
complete -c tiffinfo -s s -d 'Display the offsets and byte counts for each data strip in a directory'
complete -c tiffinfo -s z -d 'Enable strip chopping when reading image data'
complete -c tiffinfo -s '#' -d 'Set the initial TIFF directory to #'

