# toast
# Autogenerated from man page /usr/share/man/man1/toast.1.gz
complete -c toast -s c -d '(cat) Write to the standard output; no files are changed'
complete -c toast -s d -d '(decode) Decode, rather than encode, the files'
complete -c toast -s f -d '(force) Force replacement of output files if they exist'
complete -c toast -s p -d '(precious) Do not delete the source files'
complete -c toast -s C -d '(LTP cut-off) Ignore most sample values when calculating the GSM long-term co…'
complete -c toast -s F -d '(fast) On systems with a floating point processor, but without a multiplicati…'
complete -c toast -s v -d '(version) outputs the version of toast (or untoast or tcat) to stdout and exi…'
complete -c toast -s h -d '(help) prints a short overview of the options'
complete -c toast -s u -d '(\\(*mU-law) 8 kHz, 8 bit \\(*mU-law encoding (file suffix . u)'
complete -c toast -s a -d '(A-law) 8 kHz, 8 bit A-law encoding (file suffix . A)'
complete -c toast -s s -d '(Sun audio) 8 kHz, 8 bit \\(*mU-law encoding with audio header (file suffix '
complete -c toast -s l -d '(linear) 8 kHz, 16 bit signed linear encoding in host byte order with 13 sign…'

