# toe.1m
# Autogenerated from man page /usr/share/man/man1/toe.1m.gz
complete -c 'toe.1m' -s a -d 'report on all of the terminal databases which ncurses would search, rather th…'
complete -c 'toe.1m' -s s -d 'sort the output by the entry names'
complete -c 'toe.1m' -s u -d 'says to write a report to the standard output, listing dependencies in the gi…'
complete -c 'toe.1m' -s U -d 'says to write a report to the standard output, listing reverse dependencies i…'
complete -c 'toe.1m' -o vn -d 'specifies that (verbose) output be written to standard error, showing toe\'s p…'
complete -c 'toe.1m' -s V -d 'reports the version of ncurses which was used in this program, and exits'
complete -c 'toe.1m' -l '>'
complete -c 'toe.1m' -l '-->' -d '*-+-:	9term     	Plan9 terminal emulator for X *---:	Eterm     	Eterm with xt…'

