# tracker3-endpoint
# Autogenerated from man page /usr/share/man/man1/tracker3-endpoint.1.gz
complete -c tracker3-endpoint -s b -l dbus-service -d 'Service name to use on the endpoint'
complete -c tracker3-endpoint -s d -l database-path -d 'The path where the database will be stored'
complete -c tracker3-endpoint -s o -l ontology -d 'The name of an ontology in $datadir/tracker/ontologies to use on the construc…'
complete -c tracker3-endpoint -s p -l ontology-path -d 'Full path to an ontology to use on the constructed database'
complete -c tracker3-endpoint -l session -d 'Use the session bus.  This is the default'
complete -c tracker3-endpoint -l system -d 'Use the system bus'
complete -c tracker3-endpoint -s l -l list -d 'List all SPARQL endpoints available in DBus'
complete -c tracker3-endpoint -l http-port -d 'Creates a HTTP endpoint that listens in the specified port'
complete -c tracker3-endpoint -l loopback -d 'Allows only HTTP connections in the loopback device'

