# tracker3-sql
# Autogenerated from man page /usr/share/man/man1/tracker3-sql.1.gz
complete -c tracker3-sql -s f -l file -d 'Use a file with SPARQL content to query'
complete -c tracker3-sql -s q -l query -d 'Use a sql string to query the database with'

