# tracker3-sparql
# Autogenerated from man page /usr/share/man/man1/tracker3-sparql.1.gz
complete -c tracker3-sparql -s f -l file -d 'Use a file with SPARQL content to query or update'
complete -c tracker3-sparql -s q -l query -d 'Use a sparql string to query the database with'
complete -c tracker3-sparql -s u -l update -d 'This has to be used with --query'
complete -c tracker3-sparql -s c -l list-classes -d 'Returns a list of classes which describe the ontology used for storing data'
complete -c tracker3-sparql -s x -l list-class-prefixes -d 'Returns a list of classes and their related prefixes'
complete -c tracker3-sparql -s p -l list-properties -d 'Returns a list of properties which pertain to a class'
complete -c tracker3-sparql -s n -l list-notifies -d 'Returns a list of classes which are notified over D-Bus about any changes tha…'
complete -c tracker3-sparql -s i -l list-indexes -d 'Returns a list of properties which are indexed in the database'
complete -c tracker3-sparql -s t -l tree -d 'Prints a tree showing all parent classes of class in the ontology'
complete -c tracker3-sparql -s s -l search -d 'Returns a list of classes and properties which partially match needle in the …'
complete -c tracker3-sparql -l get-shorthand -d 'Returns the shorthand for a class given by a URL.  For example:'
complete -c tracker3-sparql -l get-longhand -d 'Returns the longhand for a class given in the form of CLASS:PROPERTY'
complete -c tracker3-sparql -s g -l list-graphs

