# transicc
# Autogenerated from man page /usr/share/man/man1/transicc.1.gz
complete -c transicc -s b -d 'Black point compensation'
complete -c transicc -s c -d 'Precalculates transform (0=Off, 1=Normal, 2=Hi-res, 3=LoRes) [defaults to 1]'
complete -c transicc -s d -d 'Observer adaptation state (abs. col.  only), (0. 1'
complete -c transicc -s e -d 'Encoded representation of numbers is not float (Option -w=use 16 bits, Option…'
complete -c transicc -s g -d 'Marks out-of-gamut colors on softproof'
complete -c transicc -s i -d 'Input profile (defaults to sRGB)'
complete -c transicc -s l -d 'Transform by device-link profile'
complete -c transicc -s m -d 'SoftProof intent (0,1,2,3) [defaults to 0]'
complete -c transicc -s n -d 'Terse output, intended for pipe usage'
complete -c transicc -s o -d 'p Output profile (defaults to sRGB)'
complete -c transicc -s q -d 'Quantize CGATS to 8 bits'
complete -c transicc -s s -d 'Bounded mode'
complete -c transicc -o tNUM -d 'Rendering intent . nf '
complete -c transicc -s v -d 'Verbosity level, (0=None, 1=Normal, 2=High, 3=Very High) [defaults to 1]'
complete -c transicc -s w -d 'Use 16 bits'
complete -c transicc -s x -d Hexadecimal
complete -c transicc -s t -d 'Rendering intent 0=Perceptual [default] 1=Relative colorimetric 2=Saturation …'

