# tsget.1ssl
# Autogenerated from man page /usr/share/man/man1/tsget.1ssl.gz
complete -c 'tsget.1ssl' -s h -d 'X Item "-h server_url" The URL of the HTTP/HTTPS server listening for timesta…'
complete -c 'tsget.1ssl' -s e -d 'X Item "-e extension" If the -o option is not given this argument specifies t…'
complete -c 'tsget.1ssl' -s o -d 'X Item "-o output" This option can be specified only when just one request is…'
complete -c 'tsget.1ssl' -s v -d 'X Item "-v" The name of the currently processed request is printed on standar…'
complete -c 'tsget.1ssl' -s d -d 'X Item "-d" Switches on verbose mode for the underlying perl module WWW::Curl…'
complete -c 'tsget.1ssl' -s k -d 'X Item "-k private_key'
complete -c 'tsget.1ssl' -s p -d 'X Item "-p key_password" (HTTPS) Specifies the passphrase for the private key…'
complete -c 'tsget.1ssl' -s c -d 'X Item "-c client_cert'
complete -c 'tsget.1ssl' -s C -d 'X Item "-C CA_certs. pem" (HTTPS) The trusted CA certificate store'
complete -c 'tsget.1ssl' -s P -d 'X Item "-P CA_path" (HTTPS) The path containing the trusted CA certificates t…'
complete -c 'tsget.1ssl' -s r -d 'X Item "-r files" See "Random State Options" in openssl\\|(1) for more informa…'
complete -c 'tsget.1ssl' -s g -d 'X Item "-g EGD_socket" The name of an EGD socket to get random data from'

