# tunelp
# Autogenerated from man page /usr/share/man/man8/tunelp.8.gz
complete -c tunelp -s i -l irq
complete -c tunelp -s t -l time
complete -c tunelp -s c -l chars
complete -c tunelp -s w -l wait
complete -c tunelp -s a -l abort
complete -c tunelp -s o -l check-status
complete -c tunelp -s C -l careful
complete -c tunelp -s s -l status
complete -c tunelp -s r -l reset
complete -c tunelp -s q -l print-irq

