# usermod
# Autogenerated from man page /usr/share/man/man8/usermod.8.gz
complete -c usermod -s a -l append -d 'Add the user to the supplementary group(s).  Use only with the -G option'
complete -c usermod -s b -l badname -d 'Allow names that do not conform to standards'
complete -c usermod -s c -l commentCOMMENT -d 'update the comment field of the user in /etc/passwd, which is normally modifi…'
complete -c usermod -s d -l homeHOME_DIR -d 'The user\\*(Aqs new login directory'
complete -c usermod -s e -l expiredateEXPIRE_DATE -d 'The date on which the user account will be disabled'
complete -c usermod -s f -l inactiveINACTIVE -d 'defines the number of days after the password exceeded its maximum age during…'
complete -c usermod -s g -l gidGROUP -d 'The name or numerical ID of the user\\*(Aqs new primary group'
complete -c usermod -s G -l groupsGROUP1 -d 'A list of supplementary groups which the user is also a member of'
complete -c usermod -s l -l loginNEW_LOGIN -d 'The name of the user will be changed from LOGIN to NEW_LOGIN'
complete -c usermod -s L -l lock -d 'Lock a user\\*(Aqs password'
complete -c usermod -s m -l move-home -d 'moves the content of the user\\*(Aqs home directory to the new location'
complete -c usermod -s o -l non-unique -d 'allows to change the user ID to a non-unique value'
complete -c usermod -s p -l passwordPASSWORD -d 'defines a new password for the user'
complete -c usermod -s r -l remove -d 'Remove the user from named supplementary group(s)'
complete -c usermod -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c usermod -s P -l prefixPREFIX_DIR -d 'Apply changes within the directory tree starting with PREFIX_DIR and use as w…'
complete -c usermod -s s -l shellSHELL -d 'changes the user\\*(Aqs login shell'
complete -c usermod -s u -l uidUID -d 'The new value of the user\\*(Aqs ID'
complete -c usermod -s U -l unlock -d 'Unlock a user\\*(Aqs password'
complete -c usermod -s v -l add-subuidsFIRST-LAST -d 'Add a range of subordinate uids to the user\\*(Aqs account'
complete -c usermod -s V -l del-subuidsFIRST-LAST -d 'Remove a range of subordinate uids from the user\\*(Aqs account'
complete -c usermod -s w -l add-subgidsFIRST-LAST -d 'Add a range of subordinate gids to the user\\*(Aqs account'
complete -c usermod -s W -l del-subgidsFIRST-LAST -d 'Remove a range of subordinate gids from the user\\*(Aqs account'
complete -c usermod -s Z -l selinux-userSEUSER -d 'defines the SELinux user to be mapped with LOGIN'
complete -c usermod -l comment
complete -c usermod -l home
complete -c usermod -l expiredate
complete -c usermod -l inactive
complete -c usermod -l gid
complete -c usermod -l groups
complete -c usermod -l login
complete -c usermod -l password
complete -c usermod -l root
complete -c usermod -l prefix
complete -c usermod -l shell
complete -c usermod -l uid
complete -c usermod -l add-subuids
complete -c usermod -l del-subuids
complete -c usermod -l add-subgids
complete -c usermod -l del-subgids
complete -c usermod -l selinux-user

