# userdbctl
# Autogenerated from man page /usr/share/man/man1/userdbctl.1.gz
complete -c userdbctl -l output -d 'Choose the output mode, takes one of "classic", "friendly", "table", "json"'
complete -c userdbctl -l json -d 'Selects JSON output mode (like --output=json) and selects the precise display…'
complete -c userdbctl -l service -s s -d 'Controls which services to query for users/groups'
complete -c userdbctl -l with-nss -d 'Controls whether to include classic glibc/NSS user/group lookups in the output'
complete -c userdbctl -l with-varlink -d 'Controls whether to include Varlink user/group lookups in the output, i. e'
complete -c userdbctl -l with-dropin -d 'Controls whether to include user/group lookups in the output that are defined…'
complete -c userdbctl -l synthesize -d 'Controls whether to synthesize records for the root and nobody users/groups i…'
complete -c userdbctl -s N -d 'This option is short for --with-nss=no --synthesize=no'
complete -c userdbctl -l multiplexer -d 'Controls whether to do lookups via the multiplexer service (if specified as t…'
complete -c userdbctl -l chain -d 'When used with the ssh-authorized-keys command, this will allow passing an ad…'
complete -c userdbctl -l no-pager -d 'Do not pipe output into a pager'
complete -c userdbctl -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c userdbctl -s h -l help -d 'Print a short help text and exit'
complete -c userdbctl -l version -d 'Print a short version string and exit'

