# v4l2-tracer
# Autogenerated from man page /usr/share/man/man1/v4l2-tracer.1.gz
complete -c v4l2-tracer -s c -l compact -d 'Write minimal whitespace in JSON file'
complete -c v4l2-tracer -s g -l debug -d 'Turn on verbose reporting plus additional debug info'
complete -c v4l2-tracer -s h -l help -d 'Display this message'
complete -c v4l2-tracer -s r -l raw -d 'Write decoded video frame data to JSON file'
complete -c v4l2-tracer -s v -l verbose -d 'Turn on verbose reporting'
complete -c v4l2-tracer -s y -l yuv -d 'Write decoded video frame data to yuv file. SS Retrace Options'
complete -c v4l2-tracer -s d -l device -d 'Use a different video device than specified in the trace file'
complete -c v4l2-tracer -s m -l media -d 'Use a different media device than specified in the trace file'

