# vlock
# Autogenerated from man page /usr/share/man/man1/vlock.1.gz
complete -c vlock -s a -o all -d 'without the invoker\'s password'
complete -c vlock -l all -d 'Lock all console sessions and disable VC switching'
complete -c vlock -s c -l current -d 'Lock the current session (this is the default)'
complete -c vlock -s h -l help -d 'Print a brief help message'
complete -c vlock -s v -l version -d 'Print the version number of vlock'

