# waitpid
# Autogenerated from man page /usr/share/man/man1/waitpid.1.gz
complete -c waitpid -s v -l verbose
complete -c waitpid -s t -l timeout
complete -c waitpid -s e -l exited
complete -c waitpid -s c -l count
complete -c waitpid -s h -l help
complete -c waitpid -s V -l version

