# webpmux
# Autogenerated from man page /usr/share/man/man1/webpmux.1.gz
complete -c webpmux -o loop -d 'Loop the frames n number of times'
complete -c webpmux -o bgcolor -d 'Background color of the canvas'
complete -c webpmux -o duration -d '     set the duration to \'d\' for the whole animation'

