# webpinfo
# Autogenerated from man page /usr/share/man/man1/webpinfo.1.gz
complete -c webpinfo -o version -d 'Print the version number (as major. minor. revision) and exit'
complete -c webpinfo -o quiet -d 'Do not show chunk parsing information'
complete -c webpinfo -o diag -d 'Show parsing error diagnosis'
complete -c webpinfo -o summary -d 'Show chunk stats summary'
complete -c webpinfo -o bitstream_info -d 'Parse bitstream header'
complete -c webpinfo -s h -o help -d 'A short usage summary'
complete -c webpinfo -s H -o longhelp -d 'Detailed usage instructions'

