# which
# Autogenerated from man page /usr/share/man/man1/which.1.gz
complete -c which -l all -s a -d 'Print all matching executables in PATH, not just the first'
complete -c which -l read-alias -s i -d 'Read aliases from stdin, reporting matching ones on stdout'
complete -c which -l skip-alias -d 'Ignore option \\`--read-alias\', if any'
complete -c which -l read-functions -d 'Read shell function definitions from stdin, reporting matching ones on stdout'
complete -c which -l skip-functions -d 'Ignore option \\`--read-functions\', if any'
complete -c which -l skip-dot -d 'Skip directories in PATH that start with a dot'
complete -c which -l skip-tilde -d 'Skip directories in PATH that start with a tilde and executables which reside…'
complete -c which -l show-dot -d 'If a directory in PATH starts with a dot and a matching executable was found …'
complete -c which -l show-tilde -d 'Output a tilde when a directory matches the HOME directory'
complete -c which -l tty-only -d 'Stop processing options on the right if not on tty'
complete -c which -l version -s v -s V -d 'Print version information on standard output then exit successfully'
complete -c which -l help -d 'Print usage information on standard output then exit successfully'

