# wrjpgcom
# Autogenerated from man page /usr/share/man/man1/wrjpgcom.1.gz
complete -c wrjpgcom -o replace -d 'Delete any existing COM blocks from the file'
complete -c wrjpgcom -o comment -d 'Supply text for new COM block on command line'
complete -c wrjpgcom -o cfile -d 'Read text for new COM block from named file'

