# xkbcli-interactive-wayland
# Autogenerated from man page /usr/share/man/man1/xkbcli-interactive-wayland.1.gz
complete -c xkbcli-interactive-wayland -o '\\-help' -d 'Print help and exit El SEE ALSO xkbcli 1, xkbcli\\-interactive\\-evdev 1, xkbcl…'

