# xkbcli-list
# Autogenerated from man page /usr/share/man/man1/xkbcli-list.1.gz
complete -c xkbcli-list -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-list -o '\\-verbose' -d 'Increase verbosity, use multiple times for debugging output'
complete -c xkbcli-list -o '\\-ruleset' -d 'Load the ruleset with the given name'
complete -c xkbcli-list -o '\\-skip\\-default\\-paths' -d 'Do not load the default XKB include paths'
complete -c xkbcli-list -o '\\-load\\-exotic' -d 'Load exotic (extra) layouts El SEE ALSO xkbcli 1, https://xkbcommon'

