# xkbcli-interactive-evdev
# Autogenerated from man page /usr/share/man/man1/xkbcli-interactive-evdev.1.gz
complete -c xkbcli-interactive-evdev -o '\\-help' -d 'Print help and exit'
complete -c xkbcli-interactive-evdev -o '\\-rules' -d 'The XKB ruleset'
complete -c xkbcli-interactive-evdev -o '\\-model' -d 'The XKB model'
complete -c xkbcli-interactive-evdev -o '\\-layout' -d 'The XKB layout'
complete -c xkbcli-interactive-evdev -o '\\-variant' -d 'The XKB layout variant'
complete -c xkbcli-interactive-evdev -o '\\-option' -d 'The XKB options'
complete -c xkbcli-interactive-evdev -o '\\-keymap' -d 'Specify a keymap path'
complete -c xkbcli-interactive-evdev -o '\\-report\\-state\\-changes' -d 'Report changes to the keyboard state'
complete -c xkbcli-interactive-evdev -o '\\-enable\\-compose' -d 'Enable Compose functionality'
complete -c xkbcli-interactive-evdev -o '\\-consumed\\-mode' -d 'Set the consumed modifiers mode (default: xkb)'
complete -c xkbcli-interactive-evdev -o '\\-without\\-x11\\-offset' -d 'Don\'t add an offset of 8 when converting an evdev keycode to an XKB keycode'

