# xkbcli-how-to-type
# Autogenerated from man page /usr/share/man/man1/xkbcli-how-to-type.1.gz
complete -c xkbcli-how-to-type -o '\\-keysym' -d 'Treat the argument as a keysym, not a Unicode codepoint'
complete -c xkbcli-how-to-type -o '\\-rules' -d 'The XKB ruleset'
complete -c xkbcli-how-to-type -o '\\-model' -d 'The XKB model'
complete -c xkbcli-how-to-type -o '\\-layout' -d 'The XKB layout'
complete -c xkbcli-how-to-type -o '\\-variant' -d 'The XKB layout variant'
complete -c xkbcli-how-to-type -o '\\-options' -d 'The XKB options El SEE ALSO xkbcli 1, https://xkbcommon'

