# xmlcatalog
# Autogenerated from man page /usr/share/man/man1/xmlcatalog.1.gz
complete -c xmlcatalog -l add -d 'Add an entry to CATALOGFILE.  TYPE indicates the type of entry'
complete -c xmlcatalog -l convert -d 'Convert SGML catalog to XML'
complete -c xmlcatalog -l create -d 'Create a new XML catalog'
complete -c xmlcatalog -l del -d 'Remove entries from CATALOGFILE matching VALUE(S)'
complete -c xmlcatalog -l noout -d 'Save output to the named file rather than outputting to stdout'
complete -c xmlcatalog -l no-super-update -d 'Do not update the SGML super catalog'
complete -c xmlcatalog -l shell -d 'Run a shell allowing interactive queries on catalog file CATALOGFILE'
complete -c xmlcatalog -l sgml -d 'Uses SGML super catalogs for --add and --del options'
complete -c xmlcatalog -s v -l verbose -d 'Output debugging information'

