# xsubpp.1perl
# Autogenerated from man page /usr/share/man/man1/xsubpp.1perl.gz
complete -c 'xsubpp.1perl' -o hiertype -d 'X Item "-hiertype" Retains \'::\' in type names so that C++ hierarchical types …'
complete -c 'xsubpp.1perl' -o except -d 'X Item "-except" Adds exception handling stubs to the C code'
complete -c 'xsubpp.1perl' -o typemap -d 'X Item "-typemap typemap" Indicates that a user-supplied typemap should take …'
complete -c 'xsubpp.1perl' -o output -d 'X Item "-output filename" Specifies the name of the output file to generate'
complete -c 'xsubpp.1perl' -s v -d 'X Item "-v" Prints the xsubpp version number to standard output, then exits'
complete -c 'xsubpp.1perl' -o prototypes -d 'X Item "-prototypes" By default xsubpp will not automatically generate protot…'
complete -c 'xsubpp.1perl' -o noversioncheck -d 'X Item "-noversioncheck" Disables the run time test that determines if the ob…'
complete -c 'xsubpp.1perl' -o nolinenumbers -d 'X Item "-nolinenumbers" Prevents the inclusion of \'#line\' directives in the o…'
complete -c 'xsubpp.1perl' -o nooptimize -d 'X Item "-nooptimize" Disables certain optimizations'
complete -c 'xsubpp.1perl' -o noinout -d 'X Item "-noinout" Disable recognition of \\f(CW\\*(C`IN\\*(C\', \\f(CW\\*(C`OUT_LIS…'
complete -c 'xsubpp.1perl' -o noargtypes -d 'X Item "-noargtypes" Disable recognition of ANSI-like descriptions of functio…'
complete -c 'xsubpp.1perl' -o C++ -d 'X Item "-C++" Currently doesn\'t do anything at all'
complete -c 'xsubpp.1perl' -s s -o strip

