# Xwayland
# Autogenerated from man page /usr/share/man/man1/Xwayland.1.gz
complete -c Xwayland -o decorate -d 'Add decorations to the Xwayland root window when running rootful'
complete -c Xwayland -o eglstream -d 'Use EGLStream backend for NVidia GPUs'
complete -c Xwayland -o fullscreen -d 'Set the Xwayland window fullscreen when running rootful'
complete -c Xwayland -o geometry -d 'Sets the geometry of the Xwayland window to WxH when running rootful'
complete -c Xwayland -o host-grab -d 'Disable host keyboard shorcuts and confine the pointer when running rootful'
complete -c Xwayland -o initfd -d 'Add the given fd as a listen socket for initialization of X clients'
complete -c Xwayland -o listen -d 'deprecated, use -listenfd instead'
complete -c Xwayland -o listenfd -d 'Add given fd as a listen socket'
complete -c Xwayland -o noTouchPointerEmulation -d 'Disable touch pointer emulation'
complete -c Xwayland -o force-xrandr-emulation -d 'Force additional non-native modes to be exposed when viewporter is not suppor…'
complete -c Xwayland -o rootless -d 'Run Xwayland rootless, so that X clients integrate seamlessly with Wayland cl…'
complete -c Xwayland -o shm -d 'Force the shared memory backend instead of glamor (if available) for passing …'
complete -c Xwayland -o verbose -d 'Sets the verbosity level for information printed on stderr'
complete -c Xwayland -o version -d 'Show the server version and exit'
complete -c Xwayland -o wm -d 'This option is used by the Wayland server to pass Xwayland the socket where t…'

