# xzdec
# Autogenerated from man page /usr/share/man/man1/xzdec.1.gz
complete -c xzdec -s d -l decompress -l uncompress -d 'Ignored for  xz (1) compatibility.   xzdec supports only decompression'
complete -c xzdec -s k -l keep -d 'Ignored for  xz (1) compatibility.   xzdec never creates or removes any files'
complete -c xzdec -s c -l stdout -l to-stdout -d 'Ignored for  xz (1) compatibility'
complete -c xzdec -s q -l quiet -d 'Specifying this once does nothing since  xzdec never displays any warnings or…'
complete -c xzdec -s Q -l no-warn -d 'Ignored for  xz (1) compatibility.   xzdec never uses the exit status 2'
complete -c xzdec -s h -l help -d 'Display a help message and exit successfully'
complete -c xzdec -s V -l version -d 'Display the version number of xzdec and liblzma.  EXIT STATUS'

