# zipdetails.1perl
# Autogenerated from man page /usr/share/man/man1/zipdetails.1perl.gz
complete -c 'zipdetails.1perl' -s h
complete -c 'zipdetails.1perl' -l redact
complete -c 'zipdetails.1perl' -l scan
complete -c 'zipdetails.1perl' -l utc
complete -c 'zipdetails.1perl' -s v
complete -c 'zipdetails.1perl' -l version

